# Generated by Django 5.2.17 on 2026-08-13 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=150)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='contractors/logos/')),
                ('years_in_business', models.PositiveIntegerField(default=0)),
                ('service_areas', models.TextField(blank=True)),
                ('office_address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_document', models.FileField(blank=True, null=True, upload_to='verification/contractors/gst/')),
                ('business_document', models.FileField(blank=True, null=True, upload_to='verification/contractors/business/')),
                ('number_of_painters', models.PositiveIntegerField(default=0)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PainterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('skills', models.TextField(blank=True, help_text='Example: Interior, Exterior, Texture, Spray Painting')),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekly_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_locations', models.TextField(blank=True)),
                ('willing_to_travel', models.BooleanField(default=False)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='verification/painters/aadhaar/')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('experience_document', models.FileField(blank=True, null=True, upload_to='verification/painters/experience/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='painter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
