# Generated by Django 5.2.17 on 2026-08-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contractorprofile_painterprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bharathuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='bharathuser',
            name='badge_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bharathuser',
            name='bharath_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bharathuser',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='painterprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
