# Generated by Django 5.2.17 on 2026-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bharathuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bharathuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='verification_qr/'),
        ),
    ]
