# Generated by Django 5.2.17 on 2026-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bharathuser_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bharathuser',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='bharathuser',
            name='bharath_qr',
            field=models.ImageField(blank=True, null=True, upload_to='badges/qr/'),
        ),
    ]
