# Generated by Django 5.2.17 on 2026-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_painterprofile_personal_and_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='default_measurement_unit',
            field=models.CharField(choices=[('FEET', 'Feet'), ('METRES', 'Metres')], default='FEET', max_length=10),
        ),
    ]
