# Generated by Django 5.2.17 on 2026-09-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contractorprofile_quotation_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='bharathuser',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
