# Generated by Django 5.2.17 on 2026-09-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_completed_project_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='extra_social_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='google_business_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='pinterest_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='website',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='bharathuser',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='painterprofile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
