# Generated by Django 5.2.17 on 2026-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_contractorprofile_bank_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorcompletedproject',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
