# Generated by Django 5.2.17 on 2026-10-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_contractorcompletedproject_completed_on'),
        ('quotations', '0109_servicecategory_contractor_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('about', models.TextField(blank=True)),
                ('service_areas', models.TextField(blank=True)),
                ('base_location', models.CharField(blank=True, max_length=180)),
                ('years_in_business', models.PositiveIntegerField(default=0)),
                ('team_size', models.PositiveIntegerField(default=0)),
                ('workspace_name_override', models.CharField(blank=True, max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('accepts_subcontract_work', models.BooleanField(default=False)),
                ('network_opt_in', models.BooleanField(default=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('brand_snapshot', models.JSONField(blank=True, default=dict)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('completed_work_orders', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_services', models.ManyToManyField(blank=True, related_name='provider_additional_services', to='quotations.servicecategory')),
                ('core_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_core_services', to='quotations.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderServiceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_claims', to='quotations.servicecategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_claims', to='accounts.providerprofile')),
                ('work_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_claims', to='quotations.workdescription')),
            ],
            options={
                'ordering': ['category__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'category', 'work_description'), name='unique_provider_service_claim')],
            },
        ),
    ]
