# Generated by Django 5.2.17 on 2026-10-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_providerprofile_providerserviceclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('purpose', models.CharField(max_length=30)),
                ('provider', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted by provider'), ('FAILED', 'Failed')], max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='purpose',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password reset'), ('RECOVERY_EMAIL', 'Recovery email verification'), ('REGISTRATION_EMAIL', 'Registration email verification'), ('CUSTOMER_ACTIVATION', 'Customer activation email verification'), ('ADMIN_TEST', 'Admin test (no authentication access)')], default='PASSWORD_RESET', max_length=30),
        ),
        migrations.CreateModel(
            name='EmailOTPSetup',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('DJANGO', 'Django email / SMTP'), ('RESEND', 'Resend'), ('SENDGRID', 'SendGrid')], default='DJANGO', max_length=20)),
                ('encrypted_api_key', models.TextField(blank=True, editable=False)),
                ('sender_domain', models.CharField(blank=True, max_length=253)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(default='Bharath Painters', max_length=150)),
                ('frontend_url', models.URLField(blank=True)),
                ('backend_url', models.URLField(blank=True)),
                ('otp_length', models.PositiveSmallIntegerField(default=6)),
                ('expiry_minutes', models.PositiveSmallIntegerField(default=10)),
                ('resend_seconds', models.PositiveIntegerField(default=60)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('max_per_hour', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email & OTP Setup',
                'verbose_name_plural': 'Email & OTP Setup',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='email_setup_singleton')],
            },
        ),
    ]
