# Generated by Django 5.2.17 on 2026-08-27 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('target_url', models.URLField(blank=True)),
                ('placement', models.CharField(choices=[('CUSTOMER_DASHBOARD', 'Customer dashboard'), ('CUSTOMER_PORTAL', 'All customer portal pages')], default='CUSTOMER_DASHBOARD', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audience', models.CharField(choices=[('CONTRACTOR', 'Contractor'), ('PAINTER', 'Paint Applicator')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('FREE', 'Free'), ('MONTHLY', 'Monthly'), ('DATE_RANGE', 'Selected dates'), ('CUSTOM', 'Customized')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quotation_limit', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True)),
                ('employee_limit', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True)),
                ('features', models.TextField(blank=True, help_text='Enter one feature per line.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('audience', 'price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.billingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', '-created_at'),
            },
        ),
    ]
