# Generated by Django 5.2.17 on 2026-08-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_packagerequest_amount_packagerequest_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='applicator_access',
            field=models.CharField(choices=[('NONE', 'No access'), ('VIEW', 'View availability'), ('CONTACT', 'View and contact'), ('BOOK', 'View, contact and book')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='availability_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='booking_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='contractor_job_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='contractor_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='job_post_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='job_seeking_post_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='location_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='validity',
            field=models.CharField(choices=[('ONE_MONTH', '1 month'), ('THREE_MONTHS', '3 months'), ('SIX_MONTHS', '6 months'), ('ONE_YEAR', '1 year'), ('CUSTOM_DATES', 'Custom dates')], default='ONE_MONTH', max_length=20),
        ),
    ]
