# Generated by Django 5.2.17 on 2026-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingplan_applicator_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
