# Generated by Django 5.2.17 on 2026-08-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_packagerequest_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='measurement_access',
            field=models.BooleanField(default=False),
        ),
    ]
