# Generated by Django 5.2.17 on 2026-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingplan_measurement_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='messages_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='property_creation_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='ratings_reviews_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='register_applicator_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='seeking_applicators_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='work_schedules_access',
            field=models.BooleanField(default=False),
        ),
    ]
