# Generated by Django 5.2.17 on 2026-08-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billingplan_messages_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingplan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
