import { useEffect, useState } from "react";
import { Save, X } from "lucide-react";
import api from "../api/client";

export default function AdminDirectoryModal({ type, item, mode, close, saved }) {
  const [form, setForm] = useState({}); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { setForm(type === "contractors" ? { company: item.company_name || "", name: item.owner_name || "", mobile: item.mobile || "", email: item.email || "", service_areas: item.service_areas || "", address: item.office_address || "", number_of_painters: item.number_of_painters || 0 } : { name: item.name || "", mobile: item.mobile || "", email: item.email || "", availability: item.availability || "AVAILABLE", experience_years: item.experience_years || 0, skills: item.skills || "", locations: item.preferred_locations || "", daily_wage: item.daily_wage || "", weekly_wage: item.weekly_wage || "" }); }, [item, type]);
  const input = "mt-1.5 w-full rounded-xl border px-3 py-2.5 outline-none focus:border-slate-950";
  const change = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value }));
  async function submit(event) { event.preventDefault(); setSaving(true); setError(""); try { await api.patch(`/quotations/admin-dashboard/${type}/${item.id}/`, form); await saved(); close(); } catch (requestError) { setError(Object.values(requestError.response?.data || {}).flat().join(" ") || "Profile could not be updated."); } finally { setSaving(false); } }
  const fields = type === "contractors" ? [["company", "Company"], ["name", "Owner"], ["mobile", "Mobile"], ["email", "Email"], ["number_of_painters", "Applicator count"], ["service_areas", "Service areas"], ["address", "Office address"]] : [["name", "Name"], ["mobile", "Mobile"], ["email", "Email"], ["availability", "Availability"], ["experience_years", "Experience years"], ["skills", "Skills"], ["locations", "Preferred locations"], ["daily_wage", "Daily wage"], ["weekly_wage", "Weekly wage"]];
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/50"><div className="h-full w-full max-w-2xl overflow-y-auto bg-white shadow-2xl"><header className="sticky top-0 flex items-center justify-between border-b bg-white p-6"><div><p className="text-sm font-semibold text-amber-600">{mode === "edit" ? "Edit profile" : "Profile details"}</p><h2 className="mt-1 text-2xl font-bold">{type === "contractors" ? item.company_name : item.name}</h2></div><button onClick={close} className="rounded-lg p-2 hover:bg-slate-100"><X /></button></header><form onSubmit={submit} className="grid gap-5 p-6 sm:grid-cols-2">{fields.map(([name, label]) => <label key={name} className={`text-sm font-semibold ${["service_areas", "address", "skills", "locations"].includes(name) ? "sm:col-span-2" : ""}`}>{label}{["service_areas", "address", "skills", "locations"].includes(name) ? <textarea rows="3" disabled={mode !== "edit"} name={name} value={form[name] ?? ""} onChange={change} className={`${input} disabled:bg-slate-50`} /> : name === "availability" ? <select disabled={mode !== "edit"} name={name} value={form[name] ?? ""} onChange={change} className={`${input} disabled:bg-slate-50`}><option>AVAILABLE</option><option>BUSY</option><option>OFFLINE</option></select> : <input disabled={mode !== "edit"} type={["number_of_painters", "experience_years", "daily_wage", "weekly_wage"].includes(name) ? "number" : name === "email" ? "email" : "text"} min={name !== "email" ? "0" : undefined} name={name} value={form[name] ?? ""} onChange={change} className={`${input} disabled:bg-slate-50`} />}</label>)}{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</p>}{mode === "edit" && <div className="flex justify-end border-t pt-5 sm:col-span-2"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 font-semibold text-white"><Save className="h-4 w-4" />{saving ? "Saving..." : "Save changes"}</button></div>}</form></div></div>;
}
