import { useId, useRef, useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, BadgeCheck, Building2, MapPin, UserRound, Star, BriefcaseBusiness, PaintRoller, Heart, Share2, Phone, MessageCircle, FileText, Users, X, ChevronLeft, ChevronRight, House, Droplets, Hammer } from 'lucide-react';
import useAuth from '../context/useAuth';
import { profileImageStyle } from '../utils/profileImagePosition';
import './contractor-portfolio.css';

export default function ContractorPortfolio({ data, actions, stats, owner = false, page = false, contextActions = {} }) {
  const card=data.digital_card;
  const {user}=useAuth();
  const navigate=useNavigate();
  const sectionId=useId();
  const [section,setSection]=useState('overview');
  const [expanded,setExpanded]=useState(false);
  const [gallery,setGallery]=useState(null);
  const [notice,setNotice]=useState('');
  const bookmarkKey=`bp-profile-favourite-${user?.id || 'visitor'}-${card.bharath_id}`;
  const [favourite,setFavourite]=useState(()=>{try{return localStorage.getItem(bookmarkKey)==='1';}catch{return false;}});
  const projects=Array.isArray(card.projects)?card.projects:[];
  const photos=projects.filter(project=>project.photo);
  const cover=card.background || photos[0]?.photo || card.logo || card.owner_photo;
  const services=[...new Set([...(card.services||[]),...(card.work_skills||[])])];
  const locations=card.service_areas||[];
  const sections=[['overview','Overview'],['services','Services'],['projects','Projects'],['reviews','Reviews']];
  const about=card.about || '';
  const phone=String(card.mobile||'').replace(/[^+0-9]/g,'');
  const digits=phone.replace(/\D/g,'');
  const whatsapp=digits.length===10?`91${digits}`:digits;
  const show=value=>section==='overview'||section===value;
  async function share(){try{if(!data.profile_url)throw new Error();if(navigator.share)await navigator.share({title:card.title,url:data.profile_url});else{await navigator.clipboard.writeText(data.profile_url);setNotice('Profile link copied.');}}catch(error){if(error.name!=='AbortError')setNotice('This profile could not be shared. Please try again.');}}
  function bookmark(){try{localStorage.setItem(bookmarkKey,favourite?'0':'1');setFavourite(!favourite);}catch{setNotice('This device could not save your favourite.');}}
  function back(){if(window.history.state?.idx>0)navigate(-1);else navigate(user?.role==='CUSTOMER'?'/customer-dashboard':'/contractor-network');}
  const Heading=owner||page?'h1':'h2';
  return <article className="contractor-portfolio contractor-profile-page contractor-profile-container" aria-label="Contractor digital profile">
    {(owner||page) && <header className="contractor-profile-header"><button type="button" onClick={back} aria-label="Back"><ArrowLeft size={18}/></button><Heading>Contractor Profile</Heading><div>{!owner && <button type="button" onClick={bookmark} aria-pressed={favourite} aria-label={favourite?'Remove contractor from favourites on this device':'Save contractor to favourites on this device'}><Heart size={19} fill={favourite?'currentColor':'none'}/></button>}<button type="button" onClick={share} aria-label="Share profile"><Share2 size={18}/></button></div></header>}
    <div className={`contractor-profile-hero ${!card.background&&photos.length>2?'has-gallery':''}`}>{cover?<button type="button" className="contractor-profile-cover-button" onClick={()=>!card.background&&photos.length&&setGallery(0)} disabled={!!card.background||!photos.length} aria-label="View project photos"><img src={cover} alt={`${card.title} profile background`} style={card.background?profileImageStyle(card.background_position):undefined}/></button>:<div className="contractor-profile-neutral-cover"><PaintRoller size={32}/></div>}{photos.length>1&&<button type="button" className="contractor-profile-image-counter" onClick={()=>setGallery(0)} aria-label={`View all ${photos.length} project photos`}>1/{photos.length}</button>}{!card.background&&photos.length>2&&<div className="contractor-profile-hero-thumbnails">{photos.slice(1,3).map((project,index)=><button type="button" key={project.id} onClick={()=>setGallery(index+1)} aria-label={`View ${project.title}`}><img src={project.photo} alt=""/>{index===1&&photos.length>3&&<span>+{photos.length-3}</span>}</button>)}</div>}{owner&&<Link className="contractor-profile-change-background" to="/settings?tab=business&edit=background#profile-background">Change background</Link>}</div>
    <div className="contractor-profile-main">
      <div className="contractor-profile-avatar-row"><div className="contractor-profile-avatar">{card.owner_photo?<img src={card.owner_photo} alt={card.owner_name||'Contractor'} style={profileImageStyle(card.owner_photo_position)}/>:<UserRound size={32}/>}</div>{card.verified&&<span className="contractor-profile-verified"><BadgeCheck size={13}/>Verified</span>}</div>
      <div className="contractor-profile-identity"><h2>{card.title}</h2><p>{card.profession_label || card.services?.[0] || 'Contractor'}</p><div className="contractor-profile-meta">{card.customer_reviews?.count>0&&<span><Star size={16}/><strong>{card.customer_reviews.rating}</strong> ({card.customer_reviews.count} reviews)</span>}{card.years_in_business>0&&<span><BriefcaseBusiness size={15}/>{card.years_in_business} Years Exp</span>}</div>{locations.length>0&&<p className="contractor-profile-location"><MapPin size={14}/>{locations[0]}</p>}</div>
      {owner?<><div className="contractor-profile-owner-edit"><Link to="/settings">Edit Profile</Link></div>{actions&&<div className="portfolio-actions contractor-profile-owner-actions">{actions}</div>}</>:<div className="contractor-profile-actions">
        {phone&&<a className="primary" href={`tel:${phone}`}><Phone size={15}/>Call</a>}
        {contextActions.onMessage?<button type="button" onClick={contextActions.onMessage} disabled={contextActions.busy}><MessageCircle size={15}/>Message</button>:whatsapp&&<a href={`https://wa.me/${whatsapp}`} target="_blank" rel="noopener noreferrer" aria-label="Message on WhatsApp"><MessageCircle size={15}/>Message</a>}
        {contextActions.quoteHref&&<Link className="primary request-quote" to={contextActions.quoteHref}><FileText size={15}/>Request Quote</Link>}
        {contextActions.assignHref&&<Link className="primary request-quote" to={contextActions.assignHref}><BriefcaseBusiness size={15}/>Assign Work</Link>}
      </div>}
      {notice&&<p role="status" className="contractor-profile-notice">{notice}</p>}
      <nav className="contractor-profile-tabs" aria-label="Profile sections">{sections.map(([value,label])=><button className="contractor-profile-tab" key={value} type="button" aria-pressed={section===value} onClick={()=>setSection(value)}>{label}</button>)}</nav>
      <div id={sectionId} className="contractor-profile-sections">
        {section==='overview'&&<section><h3>About</h3>{about?<><p className={`contractor-profile-about ${expanded?'expanded':''}`}>{about}</p>{about.length>180&&<button className="contractor-profile-text-link" type="button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Read less':'Read more'}</button>}</>:<p className="contractor-profile-muted">Business description has not been added yet.</p>}
        <div className="contractor-profile-stats">{card.years_in_business>0&&<Fact icon={BriefcaseBusiness} value={card.years_in_business} label="Years Experience"/>}{card.workers>0&&<Fact icon={Users} value={card.workers} label="Team Members"/>}{projects.length>0&&<Fact icon={FileText} value={projects.length} label="Projects Completed"/>}{locations.length>0&&<Fact icon={MapPin} value={locations[0]} label="Service Area"/>}{stats?.active>0&&<Fact icon={BriefcaseBusiness} value={stats.active} label="Active together"/>}</div></section>}
        {show('services')&&<section><SectionHeading title="Services Offered" onAll={section==='overview'?()=>setSection('services'):null}/>{services.length?<ul className="contractor-profile-services">{(section==='overview'?services.slice(0,6):services).map(service=>{const Icon=serviceIcon(service);return <li className="contractor-profile-service-card" key={service}><Icon size={20}/><span>{service}</span></li>;})}</ul>:<p className="contractor-profile-muted">No services added yet.</p>}</section>}
        {show('projects')&&<section><SectionHeading title={section==='overview'?'Recent Projects':'Completed Projects'} onAll={section==='overview'?()=>setSection('projects'):null}/>{projects.length?section==='overview'?<div className="contractor-profile-projects">{projects.slice(0,4).map(project=><ProjectPreview key={project.id} project={project} onView={()=>{setSection('projects');}}/>)}</div>:<div className="contractor-profile-project-list">{projects.map(project=><article key={project.id}>{project.photo&&<button type="button" onClick={()=>setGallery(photos.findIndex(item=>item.id===project.id))} aria-label={`View ${project.title}`}><img src={project.photo} alt={project.title}/></button>}<div><h4>{project.title}</h4>{project.location&&<p><MapPin size={12}/>{project.location}</p>}{project.completed_on_display&&<small>Completed {project.completed_on_display}</small>}{project.description&&<p>{project.description}</p>}{project.work_completed&&<p>{project.work_completed}</p>}</div></article>)}</div>:<p className="contractor-profile-muted">No project photos added yet.</p>}</section>}
        {(section==='overview'||section==='services')&&<section><h3>Service Area</h3>{locations.length?<ul className="contractor-profile-service-areas">{locations.map((location,index)=><li className="contractor-profile-service-area" key={`${location}-${index}`}>{location}</li>)}</ul>:<p className="contractor-profile-muted">No service areas added yet.</p>}</section>}
        {section==='overview'&&<section className="contractor-profile-trust"><h3>Trust &amp; Verification</h3>{card.verified?<p><BadgeCheck size={16}/>Bharath verified profile</p>:<p className="contractor-profile-muted">Verification has not been confirmed.</p>}<details><summary>Profile identity &amp; QR</summary><div>{card.logo&&<img className="contractor-profile-business-logo" src={card.logo} alt={`${card.title} logo`} style={profileImageStyle(card.logo_position)}/>}<span>{card.bharath_id}</span>{data.qr_image&&<a href={data.qr_image} target="_blank" rel="noreferrer" aria-label="Open verification QR code"><img src={data.qr_image} alt="Verification QR code"/></a>}</div></details></section>}
        {show('reviews')&&<section><SectionHeading title="Reviews" onAll={section==='overview'?()=>setSection('reviews'):null}/>{card.customer_reviews?.count>0&&<p className="contractor-profile-rating"><Star size={16}/><strong>{card.customer_reviews.rating}</strong> / 5 ({card.customer_reviews.count} reviews)</p>}{card.customer_reviews?.items?.length?<div className="contractor-profile-reviews">{card.customer_reviews.items.map(review=><article key={review.id}><div><strong>{review.customer_name}</strong><span aria-label={`${review.rating} out of 5 stars`}>{'\u2605'.repeat(Math.min(5,Math.max(0,Number(review.rating)||0)))}</span></div>{review.date&&<small>{new Date(review.date).toLocaleDateString('en-IN')}</small>}{review.comment&&<p>{review.comment}</p>}</article>)}</div>:<p className="contractor-profile-muted">No reviews yet.</p>}</section>}
      </div>
    </div>
    {gallery!==null&&photos[gallery]&&<ProjectGallery photos={photos} index={gallery} onChange={setGallery} onClose={()=>setGallery(null)}/>}
  </article>;
}
function Fact({icon:Icon,value,label}){return <div><Icon size={19}/><span><strong>{value}</strong><small>{label}</small></span></div>;}
function SectionHeading({title,onAll}){return <div className="contractor-profile-section-heading"><h3>{title}</h3>{onAll&&<button type="button" onClick={onAll}>View All</button>}</div>;}
function ProjectPreview({project,onView}){return <button type="button" className="contractor-profile-project-card" onClick={onView}>{project.photo?<img src={project.photo} alt={project.title}/>:<span className="contractor-profile-project-placeholder"><BriefcaseBusiness size={22}/></span>}<strong>{project.title}</strong>{project.location&&<small>{project.location}</small>}</button>;}
function serviceIcon(label){const value=label.toLowerCase();if(/water|plumb/.test(value))return Droplets;if(/exterior|building/.test(value))return Building2;if(/interior|home/.test(value))return House;if(/wood|carpent/.test(value))return Hammer;if(/paint|texture/.test(value))return PaintRoller;return BriefcaseBusiness;}
function ProjectGallery({photos,index,onChange,onClose}){const dialogRef=useRef(null);useEffect(()=>{const dialog=dialogRef.current;dialog.showModal();return()=>{if(dialog.open)dialog.close();};},[]);return <dialog ref={dialogRef} className="contractor-profile-gallery" onCancel={onClose} aria-label="Project photos"><header><strong>{photos[index].title}</strong><button type="button" onClick={onClose} aria-label="Close project photos"><X size={20}/></button></header><img src={photos[index].photo} alt={photos[index].title}/><footer><button type="button" onClick={()=>onChange((index-1+photos.length)%photos.length)} aria-label="Previous photo"><ChevronLeft size={20}/></button><span>{index+1}/{photos.length}</span><button type="button" onClick={()=>onChange((index+1)%photos.length)} aria-label="Next photo"><ChevronRight size={20}/></button></footer></dialog>;}
