import { useCallback, useEffect, useState } from "react";
import { Check, Download, History, Inbox, X } from "lucide-react";
import api from "../api/client";
import { previewPdf } from "./PdfPreview";

const OPEN_STATUSES=["PENDING","AWAITING_PAYMENT","PAYMENT_SUBMITTED"];
const HISTORY_STATUSES=["APPROVED","REJECTED","CANCELLED"];

export default function PackageRequests(){
 const [items,setItems]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[tab,setTab]=useState("OPEN");
 const load=useCallback(()=>api.get("/billing/package-requests/").then(({data})=>{setItems(data);setError("")}).catch(()=>setError("Package requests could not be loaded.")),[]); useEffect(()=>{load()},[load]);
 const decide=async(id,decision)=>{const note=decision==="REJECTED"?window.prompt("Reason for rejection:")||"":"";try{const{data}=await api.patch("/billing/package-requests/",{request_id:id,decision,admin_note:note});setMessage(data.message);await load()}catch(err){setError(err.response?.data?.detail||"Request could not be updated.")}};
 const download=async item=>{try{const response=await api.get(`/billing/package-requests/${item.id}/document/`,{responseType:"blob"});previewPdf(response.data,`${item.receipt_number||item.invoice_number}.pdf`)}catch{setError("Billing document could not be previewed.")}};
 const open=items.filter(item=>OPEN_STATUSES.includes(item.status)); const history=items.filter(item=>HISTORY_STATUSES.includes(item.status)); const shown=tab==="OPEN"?open:history;
 return <section className="rounded-2xl border bg-white p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-amber-600">Registrations and payments</p><h2 className="mt-1 text-xl font-bold">{tab==="OPEN"?"Package requests":"Package request history"}</h2></div><div className="flex gap-2"><Tab active={tab==="OPEN"} click={()=>setTab("OPEN")} icon={Inbox} label="Requests" count={open.length}/><Tab active={tab==="HISTORY"} click={()=>setTab("HISTORY")} icon={History} label="History" count={history.length}/></div></div>
 {message&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-y bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">User</th><th className="p-3">Plan / dates</th><th className="p-3">Amount</th><th className="p-3">Payment evidence</th><th className="p-3">Status</th><th className="p-3 text-right">Action</th></tr></thead><tbody className="divide-y">{shown.map(item=><RequestRow key={item.id} item={item} decide={decide} download={download}/>)}</tbody></table>{!shown.length&&<p className="p-8 text-center text-sm text-slate-400">{tab==="OPEN"?"No pending package requests.":"No completed request history."}</p>}</div>
 </section>;
}
function Tab({active,click,icon:Icon,label,count}){return <button onClick={click} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${active?"bg-slate-950 text-white":"bg-slate-100 text-slate-600"}`}><Icon className="h-4 w-4"/>{label}<span className={`rounded-full px-2 py-0.5 text-xs ${active?"bg-white/15":"bg-white"}`}>{count}</span></button>}
function RequestRow({item,decide,download}){const actionable=["PENDING","PAYMENT_SUBMITTED"].includes(item.status);return <tr><td className="p-3"><p className="font-semibold">{item.contractor}</p><p className="text-xs text-slate-500">{item.role==="PAINTER"?"Paint Applicator":"Contractor"} · {item.mobile} · {item.bharath_id||"No ID"}</p></td><td className="p-3"><b>{item.plan_name}</b><small className="block text-slate-500">{item.start_date||"—"} to {item.end_date||"ongoing"}{item.is_renewal?" · Renewal":""}</small></td><td className="p-3">₹{Number(item.amount||0).toLocaleString("en-IN")}</td><td className="p-3"><b>{String(item.payment_status).replaceAll("_"," ")}</b><small className="block text-slate-500">{item.payment_mode||"—"}{item.payment_reference?` · ${item.payment_reference}`:""}</small></td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.status==="APPROVED"?"bg-emerald-50 text-emerald-700":item.status==="REJECTED"||item.status==="CANCELLED"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{item.status.replaceAll("_"," ")}</span></td><td className="p-3"><div className="flex justify-end gap-2">{actionable&&<><button onClick={()=>decide(item.id,"APPROVED")} className="flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><Check className="h-4 w-4"/>Confirm & activate</button><button onClick={()=>decide(item.id,"REJECTED")} className="flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-600"><X className="h-4 w-4"/>Reject</button></>}<button onClick={()=>download(item)} className="rounded-lg border p-2" title="Download document"><Download className="h-4 w-4"/></button></div></td></tr>}
