import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, PackagePlus, Pencil, Search, X } from "lucide-react";
import api from "../api/client";
import DirectoryPagination, { paginate } from "./DirectoryPagination";

const today=()=>new Date().toISOString().slice(0,10);
export default function PackageAssignments({plans}){
 const [users,setUsers]=useState([]),[search,setSearch]=useState(""),[role,setRole]=useState("CONTRACTOR"),[membership,setMembership]=useState("ALL"),[sortBy,setSortBy]=useState("NAME_ASC"),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[message,setMessage]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false),[viewing,setViewing]=useState(null),[assigning,setAssigning]=useState(null),[editing,setEditing]=useState(null);
 const load=useCallback(()=>api.get("/billing/assignments/").then(({data})=>{setUsers(data);setError("")}).catch(()=>setError("Users could not be loaded.")),[]); useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();const rows=users.filter(u=>u.role===role&&(membership==="ALL"||u.membership_status===membership)&&(!q||`${u.name} ${u.mobile} ${u.bharath_id||""}`.toLowerCase().includes(q)));return rows.sort((a,b)=>compareUsers(a,b,sortBy))},[users,role,membership,search,sortBy]);
 const {pageRows,totalPages,safePage}=paginate(filtered,page,pageSize);
 useEffect(()=>{setPage(1)},[role,membership,search,sortBy]);
 useEffect(()=>{if(page!==safePage)setPage(safePage)},[page,safePage]);
 const rolePlans=user=>plans.filter(p=>p.audience===user.role&&p.is_active!==false);
 const openAssign=user=>setAssigning({user,plan_id:"",start_date:today(),end_date:""});
 const openEdit=user=>setEditing({user,plan_id:String(user.plan?.id||""),start_date:user.subscription?.start_date||today(),end_date:user.subscription?.end_date||"",is_active:user.subscription?.is_active!==false});
 const assign=async event=>{event.preventDefault();setSaving(true);setError("");try{const{data}=await api.post("/billing/assignments/",{user_id:assigning.user.id,plan_id:assigning.plan_id,start_date:assigning.start_date,end_date:assigning.end_date||null});setMessage(data.message);setAssigning(null);await load()}catch(err){setError(readError(err,"Package could not be assigned."))}finally{setSaving(false)}};
 const update=async event=>{event.preventDefault();setSaving(true);setError("");try{const{data}=await api.patch(`/billing/assignments/${editing.user.subscription.id}/`,{plan_id:editing.plan_id,start_date:editing.start_date,end_date:editing.end_date||null,is_active:editing.is_active});setMessage(data.message);setEditing(null);await load()}catch(err){setError(readError(err,"Subscription could not be updated."))}finally{setSaving(false)}};
 const chooseRole=value=>{setRole(value);setMembership("ALL");setSearch("")};
 return <section className="overflow-hidden rounded-2xl border bg-white"><header className="border-b p-6"><p className="text-sm font-semibold text-amber-600">User subscriptions</p><h2 className="mt-1 text-xl font-bold">Select a user to assign a package</h2><p className="mt-1 text-sm text-slate-500">Package and validity dates are selected in the popup after choosing the user.</p></header>
 <div className="border-b p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="flex gap-2"><RoleButton active={role==="CONTRACTOR"} click={()=>chooseRole("CONTRACTOR")} label="Contractors" count={users.filter(u=>u.role==="CONTRACTOR").length}/><RoleButton active={role==="PAINTER"} click={()=>chooseRole("PAINTER")} label="Paint Applicators" count={users.filter(u=>u.role==="PAINTER").length}/></div><label className="relative flex-1"><Search className="absolute left-4 top-3.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, mobile number or Bharath ID" className="w-full rounded-xl border py-3 pl-11 pr-4"/></label><select value={sortBy} onChange={e=>setSortBy(e.target.value)} className="rounded-xl border bg-white px-4 py-3 text-sm font-semibold"><option value="NAME_ASC">Name A–Z</option><option value="NAME_DESC">Name Z–A</option><option value="PACKAGE_ASC">Package A–Z</option><option value="STATUS">Membership status</option><option value="EXPIRY_ASC">Expiry: earliest first</option><option value="EXPIRY_DESC">Expiry: latest first</option></select></div><div className="mt-4 flex flex-wrap gap-2"><StatusButton active={membership==="ALL"} click={()=>setMembership("ALL")} label="All" count={users.filter(u=>u.role===role).length}/><StatusButton active={membership==="ACTIVE_PAID"} click={()=>setMembership("ACTIVE_PAID")} label="Active paid" count={users.filter(u=>u.role===role&&u.membership_status==="ACTIVE_PAID").length}/><StatusButton active={membership==="INACTIVE"} click={()=>setMembership("INACTIVE")} label="Inactive" count={users.filter(u=>u.role===role&&u.membership_status==="INACTIVE").length}/><StatusButton active={membership==="FREE"} click={()=>setMembership("FREE")} label="Free plans" count={users.filter(u=>u.role===role&&u.membership_status==="FREE").length}/></div>{message&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div>
 <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">User</th><th className="p-4">Contact</th><th className="p-4">Current package</th><th className="p-4">Membership</th><th className="p-4">Valid until</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{pageRows.map(user=><tr key={user.id} className="hover:bg-slate-50"><td className="p-4"><p className="font-bold">{user.name}</p><p className="mt-1 text-xs text-slate-500">{user.bharath_id||"ID not generated"}</p></td><td className="p-4 text-slate-600">{user.mobile}</td><td className="p-4"><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">{user.plan?.name||"Default access"}</span></td><td className="p-4"><Membership value={user.membership_status}/></td><td className="p-4 text-slate-600">{user.subscription?.end_date||user.latest_subscription?.end_date||"No expiry"}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={()=>openAssign(user)} className="flex items-center gap-2 rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white"><PackagePlus className="h-4 w-4"/>Assign package</button><IconButton title="View" click={()=>setViewing(user)} icon={Eye}/><IconButton disabled={!user.subscription} title="Edit" click={()=>openEdit(user)} icon={Pencil}/></div></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center text-sm text-slate-400">No matching users found.</p>}</div><DirectoryPagination total={filtered.length} page={safePage} totalPages={totalPages} pageSize={pageSize} setPage={setPage} setPageSize={setPageSize}/>
 {assigning&&<Modal title="Assign package" subtitle={`${assigning.user.name} · ${assigning.user.mobile}`} close={()=>setAssigning(null)}><SubscriptionForm state={assigning} setState={setAssigning} plans={rolePlans(assigning.user)} saving={saving} submit={assign} button="Assign package"/></Modal>}
 {editing&&<Modal title="Edit subscription" subtitle={`${editing.user.name} · ${editing.user.mobile}`} close={()=>setEditing(null)}><SubscriptionForm state={editing} setState={setEditing} plans={rolePlans(editing.user)} saving={saving} submit={update} button="Update subscription" editing/></Modal>}
 {viewing&&<Modal title="Package details" subtitle={`${viewing.name} · ${viewing.mobile}`} close={()=>setViewing(null)}><Details user={viewing}/></Modal>}
 </section>;
}
function SubscriptionForm({state,setState,plans,saving,submit,button,editing}){return <form onSubmit={submit} className="space-y-5"><Field label="Select package"><select required value={state.plan_id} onChange={e=>setState({...state,plan_id:e.target.value})}><option value="">Choose package</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name} · ₹{Number(plan.price||0).toLocaleString("en-IN")} · {validity(plan.validity)}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Start date"><input required type="date" value={state.start_date} onChange={e=>setState({...state,start_date:e.target.value})}/></Field><Field label="End date" hint="Leave empty to calculate from package"><input type="date" min={state.start_date} value={state.end_date} onChange={e=>setState({...state,end_date:e.target.value})}/></Field></div>{editing&&<label className="flex items-center gap-3 rounded-xl border p-4"><input type="checkbox" checked={state.is_active} onChange={e=>setState({...state,is_active:e.target.checked})}/><span className="font-semibold">Subscription is active</span></label>}<button disabled={saving} className="w-full rounded-xl bg-slate-950 py-3 font-bold text-white disabled:opacity-50">{saving?"Saving...":button}</button></form>}
function Modal({title,subtitle,close,children}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex justify-between"><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><button onClick={close} className="rounded-lg p-2 hover:bg-slate-100"><X/></button></div>{children}</div></div>}
function Details({user}){const subscription=user.subscription;return <div className="grid gap-3 text-sm sm:grid-cols-2"><Detail label="Bharath ID" value={user.bharath_id||"—"}/><Detail label="Portal" value={user.role==="PAINTER"?"Paint Applicator":"Contractor"}/><Detail label="Package" value={user.plan?.name||"Default access"}/><Detail label="Price" value={user.plan?`₹${Number(user.plan.price||0).toLocaleString("en-IN")}`:"—"}/><Detail label="Start date" value={subscription?.start_date||"—"}/><Detail label="Valid until" value={subscription?.end_date||"No expiry"}/><Detail label="Status" value={subscription?.is_active===false?"Inactive":subscription?"Active":"Default"}/></div>}
function RoleButton({active,click,label,count}){return <button onClick={click} className={`flex items-center gap-2 whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold ${active?"bg-slate-950 text-white":"bg-slate-100 text-slate-600"}`}>{label}<span className={`rounded-full px-2 py-0.5 text-xs ${active?"bg-white/15":"bg-white"}`}>{count}</span></button>}
function StatusButton({active,click,label,count}){return <button onClick={click} className={`rounded-full px-3 py-1.5 text-xs font-bold ${active?"bg-amber-500 text-slate-950":"bg-slate-100 text-slate-600"}`}>{label} {count}</button>}
function Membership({value}){const styles=value==="ACTIVE_PAID"?"bg-emerald-50 text-emerald-700":value==="INACTIVE"?"bg-red-50 text-red-700":"bg-blue-50 text-blue-700";return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${styles}`}>{value==="ACTIVE_PAID"?"ACTIVE PAID":value==="INACTIVE"?"INACTIVE":"FREE PLAN"}</span>}
function IconButton({icon:Icon,click,...props}){return <button {...props} onClick={click} className="rounded-lg border p-2 disabled:opacity-30"><Icon className="h-4 w-4"/></button>}
function Field({label,hint,children}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span>{children}{hint&&<span className="mt-1 block text-xs text-slate-400">{hint}</span>}</label>}
function Detail({label,value}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>}
function validity(value){return({ONE_MONTH:"1 month",THREE_MONTHS:"3 months",SIX_MONTHS:"6 months",ONE_YEAR:"1 year",CUSTOM_DATES:"Custom dates"})[value]||"1 month"}
function readError(error,fallback){const data=error.response?.data||{};return data.detail||data.user_id||data.plan_id||data.end_date||fallback}
function compareUsers(a,b,sortBy){const text=(value)=>String(value||"").toLowerCase();const expiry=user=>user.subscription?.end_date||user.latest_subscription?.end_date||"9999-12-31";if(sortBy==="NAME_DESC")return text(b.name).localeCompare(text(a.name));if(sortBy==="PACKAGE_ASC")return text(a.plan?.name).localeCompare(text(b.plan?.name))||text(a.name).localeCompare(text(b.name));if(sortBy==="STATUS")return text(a.membership_status).localeCompare(text(b.membership_status))||text(a.name).localeCompare(text(b.name));if(sortBy==="EXPIRY_ASC")return expiry(a).localeCompare(expiry(b));if(sortBy==="EXPIRY_DESC")return expiry(b).localeCompare(expiry(a));return text(a.name).localeCompare(text(b.name))}
