# Generated by Django 5.2.17 on 2026-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='calculation_type',
            field=models.CharField(choices=[('WALL', 'Wall Area'), ('CEILING', 'Ceiling Area'), ('WALL_CEILING', 'Wall + Ceiling'), ('DOOR', 'Door Area'), ('WINDOW', 'Window Area'), ('CUSTOM', 'Custom Quantity'), ('DAILY', 'Daily Labour'), ('WEEKLY', 'Weekly Labour')], default='CUSTOM', max_length=30),
        ),
    ]
