# Generated by Django 5.2.17 on 2026-08-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_servicetype_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationroom',
            name='door_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='door_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='door_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='window_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='window_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='window_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
