# Generated by Django 5.2.17 on 2026-08-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotationroom_door_count_quotationroom_door_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='calculation_type',
            field=models.CharField(choices=[('WALL', 'Wall Area'), ('CEILING', 'Ceiling Area'), ('WALL_CEILING', 'Wall + Ceiling Area'), ('DOOR', 'Door Area'), ('WINDOW', 'Window Area'), ('CUSTOM', 'Custom Quantity')], default='CUSTOM', max_length=20),
        ),
    ]
