# Generated by Django 5.2.17 on 2026-08-16 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_alter_servicetype_calculation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('PHONE', 'Phone'), ('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('GOOGLE', 'Google'), ('REFERRAL', 'Referral'), ('WALK_IN', 'Walk In'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow Up'), ('SITE_VISIT', 'Site Visit'), ('QUOTATION_SENT', 'Quotation Sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('NOTE', 'Note'), ('SITE_VISIT', 'Site Visit'), ('MEETING', 'Meeting')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('follow_up_date', models.DateTimeField(auto_now_add=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='quotations.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='quotations.customer')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_history', to='quotations.property')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customer_work/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quotations.customerworkhistory')),
            ],
        ),
    ]
