# Generated by Django 5.2.17 on 2026-08-17 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_customer_next_follow_up_customer_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('window_count', models.PositiveIntegerField(default=0)),
                ('window_width', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('window_height', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('door_count', models.PositiveIntegerField(default=0)),
                ('door_width', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('door_height', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('wall_area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ceiling_area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('window_area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('door_area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paintable_area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='quotations.property')),
            ],
        ),
    ]
