# Generated by Django 5.2.17 on 2026-08-17 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_propertyroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationroom',
            name='property_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_rooms', to='quotations.propertyroom'),
        ),
    ]
