
# Generated by Django 5.2.17 on 2026-08-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quotations",
            "0007_quotationroom_property_room",
        ),
    ]

    operations = [

        migrations.AddField(
            model_name="quotation",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Fixed Amount"),
                    ("PERCENTAGE", "Percentage"),
                ],
                default="FIXED",
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name="quotation",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
            ),
        ),

        migrations.AddField(
            model_name="quotation",
            name="gst_mode",
            field=models.CharField(
                choices=[
                    ("GST_EXTRA", "GST Extra"),
                    ("GST_INCLUDED", "GST Included"),
                    ("NO_GST", "No GST"),
                ],
                default="GST_EXTRA",
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name="quotationitem",
            name="calculation_method",
            field=models.CharField(
                choices=[
                    ("AREA", "Area Based"),
                    ("LUMPSUM", "Lumpsum"),
                    ("MANUAL", "Manual Quantity"),
                ],
                default="AREA",
                max_length=20,
            ),
        ),
    ]

