# Generated by Django 5.2.17 on 2026-08-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_preserve_existing_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area', models.CharField(choices=[('INTERIOR', 'Interior'), ('EXTERIOR', 'Exterior')], max_length=10)),
                ('surface_type', models.CharField(choices=[('WALL', 'Wall'), ('CEILING', 'Ceiling'), ('BALCONY_SOFFIT', 'Balcony ceiling'), ('STAIR_SOFFIT', 'Staircase ceiling'), ('PORCH_CEILING', 'Porch ceiling'), ('WATERPROOFING', 'Floor / terrace waterproofing'), ('PARAPET', 'Parapet wall'), ('OTHER', 'Other / manual')], max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manual_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('finish', models.CharField(blank=True, max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_surfaces', to='quotations.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_surfaces', to='quotations.propertyroom')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_type', models.CharField(choices=[('DOOR', 'Door'), ('WINDOW', 'Window'), ('WARDROBE', 'Wardrobe'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deduction_mode', models.CharField(choices=[('FULL', 'Full deduction'), ('IGNORE', 'Ignore deduction'), ('PERCENTAGE', 'Partial deduction')], default='FULL', max_length=15)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('separate_finish', models.CharField(blank=True, max_length=120)),
                ('separate_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='quotations.measurementsurface')),
            ],
        ),
    ]
