# Generated by Django 5.2.17 on 2026-08-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_measurementsurface_measurementopening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('1RK', '1 RK'), ('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('4BHK', '4 BHK'), ('VILLA', 'Villa'), ('OFFICE', 'Office'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
    ]
