# Generated by Django 5.2.17 on 2026-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementopening',
            name='effect',
            field=models.CharField(choices=[('DEDUCT', 'Deduct'), ('ADD', 'Add')], default='DEDUCT', max_length=10),
        ),
    ]
