# Generated by Django 5.2.17 on 2026-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_measurementopening_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='measurement_type',
            field=models.CharField(choices=[('INTERIOR', 'Interior'), ('EXTERIOR', 'Exterior')], default='INTERIOR', max_length=10),
        ),
    ]
