# Generated by Django 5.2.17 on 2026-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_property_measurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='calculation_type',
            field=models.CharField(choices=[('WALL', 'Wall Area'), ('CEILING', 'Ceiling Area'), ('WALL_CEILING', 'Wall + Ceiling Area'), ('DOOR', 'Door Area'), ('WINDOW', 'Window Area'), ('WARDROBE', 'Wardrobe Area'), ('WATERPROOFING', 'Waterproofing Area'), ('CUSTOM', 'Custom Quantity')], default='CUSTOM', max_length=20),
        ),
    ]
