# Generated by Django 5.2.17 on 2026-08-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_alter_servicetype_calculation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyroom',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_rooms', to='quotations.area'),
        ),
    ]
