# Generated by Django 5.2.17 on 2026-08-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0023_alter_quotation_status_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('ACCEPTED', 'Accepted'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'Work in progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled'), ('REVISION_REQUESTED', 'Revision Requested')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('SITE_VISIT', 'Site Visit'), ('QUOTATION', 'Quotation'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
    ]
