# Generated by Django 5.2.17 on 2026-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0030_service_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='measurement_unit',
            field=models.CharField(choices=[('FEET', 'Feet'), ('METRES', 'Metres')], default='FEET', max_length=10),
        ),
    ]
