# Generated by Django 5.2.17 on 2026-09-07 09:54

from django.db import migrations, models


def issue_existing_drafts(apps, schema_editor):
    Invoice = apps.get_model('quotations', 'Invoice')
    Invoice.objects.filter(status='DRAFT').update(status='ISSUED')


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0054_invoice_measurement_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(issue_existing_drafts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('PART_PAID', 'Part paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=20),
        ),
    ]
