# Generated by Django 5.2.17 on 2026-09-07 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_existing_payments(apps, schema_editor):
    Invoice = apps.get_model('quotations', 'Invoice')
    InvoicePayment = apps.get_model('quotations', 'InvoicePayment')
    for invoice in Invoice.objects.filter(amount_paid__gt=0):
        InvoicePayment.objects.create(
            invoice=invoice,
            received_date=invoice.invoice_date,
            amount=invoice.amount_paid,
            payment_mode=invoice.payment_mode or 'OTHER',
            payment_reference=invoice.payment_reference or '',
            notes='Opening payment migrated from invoice total.',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0055_invoice_payment_mode_invoice_payment_received_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='quotations.invoice')),
            ],
            options={
                'ordering': ('received_date', 'id'),
            },
        ),
        migrations.RunPython(migrate_existing_payments, migrations.RunPython.noop),
    ]
