# Generated by Django 5.2.17 on 2026-09-11 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_lead_references(apps, schema_editor):
    Lead = apps.get_model("quotations", "Lead")
    from collections import defaultdict
    by_year = defaultdict(int)
    for lead in Lead.objects.order_by("created_at", "pk"):
        year = lead.created_at.year if lead.created_at else 2026
        by_year[year] += 1
        lead.reference_no = f"OPP-{year}-{by_year[year]:06d}"
        lead.save(update_fields=["reference_no"])


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0058_quotation_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='client_type',
            field=models.CharField(blank=True, choices=[('HOMEOWNER', 'Homeowner'), ('TENANT', 'Tenant'), ('COMPANY', 'Company'), ('PROPERTY_MANAGER', 'Property Manager'), ('INTERIOR_DESIGNER', 'Interior Designer'), ('ARCHITECT', 'Architect'), ('BUILDER', 'Builder'), ('REAL_ESTATE_AGENT', 'Real Estate Agent'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='quotations.lead'),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='outcome',
            field=models.CharField(blank=True, choices=[('INTERESTED', 'Interested'), ('CALL_LATER', 'Call Later'), ('WAITING_DECISION', 'Waiting for Decision'), ('REVISED_QUOTE', 'Need Revised Quote'), ('NEGOTIATION', 'Price Negotiation'), ('SITE_VISIT_REQUIRED', 'Site Visit Required'), ('NOT_INTERESTED', 'Not Interested'), ('COMPETITOR', 'Competitor Selected'), ('NO_RESPONSE', 'No Response'), ('WON', 'Won'), ('LOST', 'Lost')], max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('PRICE', 'Price Too High'), ('COMPETITOR', 'Competitor Selected'), ('POSTPONED', 'Customer Postponed'), ('NO_RESPONSE', 'No Response'), ('BUDGET', 'Budget Issue'), ('SERVICE_UNAVAILABLE', 'Service Not Available'), ('DUPLICATE', 'Duplicate Enquiry'), ('INVALID', 'Invalid Enquiry'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='quotations.property'),
        ),
        migrations.AddField(
            model_name='lead',
            name='reference_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='site_visit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('GOOGLE_SEARCH', 'Google Search'), ('GOOGLE_PROFILE', 'Google Business Profile'), ('GOOGLE_ADS', 'Google Ads'), ('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('PHONE', 'Phone Call'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('REFERRAL', 'Referral'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('WALK_IN', 'Walk-in'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='follow_up_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('NOTE', 'Note'), ('SITE_VISIT', 'Site Visit'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('OFFICE_MEETING', 'Office Meeting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow Up'), ('SITE_VISIT', 'Site Visit'), ('MEASUREMENT', 'Measurement'), ('QUOTATION', 'Quotation'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstagehistory',
            name='to_stage',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow Up'), ('SITE_VISIT', 'Site Visit'), ('MEASUREMENT', 'Measurement'), ('QUOTATION', 'Quotation'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=40)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_mobile', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_site_visits', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_site_visits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='quotations.customer')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='quotations.lead')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to='quotations.property')),
            ],
            options={
                'ordering': ('-scheduled_date', '-created_at'),
            },
        ),
        migrations.RunPython(populate_lead_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lead',
            name='reference_no',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
