# Generated by Django 5.2.17 on 2026-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0059_customer_alternate_mobile_customer_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='reference_no',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
