# Generated by Django 5.2.17 on 2026-09-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0060_alter_sitevisit_reference_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="revision_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisions",
                to="quotations.quotation",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
