# Generated by Django 5.2.17 on 2026-09-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0063_quotation_measurement_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('locality', models.CharField(blank=True, max_length=160)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('map_url', models.URLField(blank=True, max_length=1000)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Apartment communities',
                'ordering': ('name', 'locality'),
                'constraints': [models.UniqueConstraint(fields=('name', 'pincode'), name='unique_apartment_community_name_pincode')],
            },
        ),
    ]
