# Generated by Django 5.2.17 on 2026-09-14 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0069_global_customer_connections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propertymeasurement',
            constraint=models.UniqueConstraint(condition=models.Q(('contractor__isnull', False)), fields=('property', 'contractor', 'version'), name='unique_area_calculation_version_per_contractor'),
        ),
    ]
