# Generated by Django 5.2.17 on 2026-09-14 17:33

from django.db import migrations


def backfill_relationship_scope(apps, schema_editor):
    Measurement = apps.get_model("quotations", "PropertyMeasurement")
    Quotation = apps.get_model("quotations", "Quotation")
    for measurement in Measurement.objects.filter(connection__isnull=True).select_related("property"):
        measurement.connection_id = measurement.property.connection_id
        measurement.contractor_id = measurement.contractor_id or measurement.property.contractor_id
        measurement.created_by_id = measurement.created_by_id or measurement.contractor_id
        measurement.save(update_fields=("connection", "contractor", "created_by"))
    for quotation in Quotation.objects.filter(connection__isnull=True).select_related("property"):
        quotation.connection_id = quotation.property.connection_id
        quotation.save(update_fields=("connection",))


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0070_propertymeasurement_unique_area_calculation_version_per_contractor'),
    ]

    operations = [
        migrations.RunPython(backfill_relationship_scope, migrations.RunPython.noop),
    ]
