# Generated by Django 5.2.17 on 2026-09-16 10:26

from django.db import migrations, models


def backfill_document_snapshots(apps, schema_editor):
    Quotation = apps.get_model('quotations', 'Quotation')
    QuotationRoom = apps.get_model('quotations', 'QuotationRoom')
    QuotationItem = apps.get_model('quotations', 'QuotationItem')
    Invoice = apps.get_model('quotations', 'Invoice')
    ContractorProfile = apps.get_model('accounts', 'ContractorProfile')

    profiles = {
        profile.user_id: profile
        for profile in ContractorProfile.objects.all()
    }
    for quotation in Quotation.objects.select_related('contractor', 'customer', 'property').iterator():
        contractor = quotation.contractor
        customer = quotation.customer
        property_obj = quotation.property
        profile = profiles.get(contractor.id)
        contractor_name = ' '.join(
            value for value in [contractor.first_name, contractor.last_name] if value
        )
        contractor_snapshot = {
            'bharath_id': contractor.bharath_id,
            'company_name': profile.company_name if profile else contractor_name,
            'owner_name': profile.owner_name if profile else contractor_name,
            'mobile': contractor.mobile,
            'email': contractor.email,
            'company_logo': profile.company_logo.name if profile and profile.company_logo else '',
            'office_address': profile.office_address if profile else '',
            'service_areas': profile.service_areas if profile else '',
            'gst_number': profile.gst_number if profile else '',
            'pan_number': profile.pan_number if profile else '',
            'is_verified': contractor.is_verified,
            'verification_status': contractor.verification_status,
        }
        customer_snapshot = {
            'bharath_id': customer.bharath_id,
            'name': customer.name,
            'mobile': customer.mobile,
            'email': customer.email,
        }
        property_snapshot = {
            'name': property_obj.name or property_obj.property_type,
            'property_type': property_obj.property_type,
            'measurement_type': property_obj.measurement_type,
            'flat_number': property_obj.flat_number,
            'block_name': property_obj.block_name,
            'address': property_obj.address,
            'city': property_obj.city,
            'pincode': property_obj.pincode,
        }
        Quotation.objects.filter(pk=quotation.pk).update(
            contractor_snapshot=contractor_snapshot,
            customer_snapshot=customer_snapshot,
            property_snapshot=property_snapshot,
        )

    for room in QuotationRoom.objects.select_related(
        'quotation__property', 'property_room__room_type'
    ).iterator():
        room_type_name = room.name
        if room.property_room_id and room.property_room.room_type_id:
            room_type_name = room.property_room.room_type.name
        elif room.quotation.property.measurement_type == 'EXTERIOR':
            room_type_name = 'Exterior'
        QuotationRoom.objects.filter(pk=room.pk).update(
            room_type_name_snapshot=room_type_name
        )

    for item in QuotationItem.objects.select_related(
        'service_category', 'service_type', 'paint_type', 'paint_brand', 'unit'
    ).iterator():
        QuotationItem.objects.filter(pk=item.pk).update(
            service_category_name_snapshot=item.custom_service_category or (
                item.service_category.name if item.service_category else ''
            ),
            service_name_snapshot=item.custom_service_type or (
                item.service_type.name if item.service_type else ''
            ),
            product_type_name_snapshot=item.custom_product_type or (
                item.paint_type.name if item.paint_type else ''
            ),
            product_type_features_snapshot=(
                item.paint_type.key_features if item.paint_type else ''
            ),
            brand_name_snapshot=item.custom_brand or (
                item.paint_brand.name if item.paint_brand else ''
            ),
            unit_name_snapshot=item.custom_unit or (
                item.unit.name if item.unit else ''
            ),
        )

    quotations = {
        quotation.pk: quotation
        for quotation in Quotation.objects.all()
    }
    for invoice in Invoice.objects.iterator():
        quotation = quotations.get(invoice.quotation_id)
        if quotation:
            Invoice.objects.filter(pk=invoice.pk).update(
                contractor_snapshot=quotation.contractor_snapshot,
                quotation_number_snapshot=quotation.quotation_number,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0076_quotation_show_product_key_features'),
        ('accounts', '0002_contractorprofile_painterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contractor_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quotation_number_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contractor_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='property_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='brand_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_type_features_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_type_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='service_category_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='service_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_name_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='room_type_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(backfill_document_snapshots, migrations.RunPython.noop),
    ]
