# Generated by Django 5.2.17 on 2026-09-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0077_invoice_contractor_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painttype',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
