# Generated by Django 5.2.17 on 2026-09-16 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0078_painttype_default_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT_TO_CUSTOMER', 'Sent to customer'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('customer_response_note', models.TextField(blank=True)),
                ('requested_date', models.DateField(default=django.utils.timezone.localdate)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_changes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_changes', to='quotations.customer')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_changes', to='quotations.quotation')),
            ],
            options={
                'ordering': ('-requested_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WorkChangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ADD_WORK', 'Add work'), ('REMOVE_WORK', 'Remove work'), ('CHANGE_SERVICE', 'Change service'), ('CHANGE_MATERIAL', 'Change material'), ('CHANGE_QUANTITY', 'Change quantity')], max_length=24)),
                ('area_name', models.CharField(blank=True, max_length=150)),
                ('original_service_snapshot', models.CharField(blank=True, max_length=180)),
                ('new_service_snapshot', models.CharField(blank=True, max_length=180)),
                ('original_material_snapshot', models.CharField(blank=True, max_length=180)),
                ('new_material_snapshot', models.CharField(blank=True, max_length=180)),
                ('original_brand_snapshot', models.CharField(blank=True, max_length=180)),
                ('new_brand_snapshot', models.CharField(blank=True, max_length=180)),
                ('unit_snapshot', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('original_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('changed_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('old_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_changes_to_brand', to='quotations.paintbrand')),
                ('new_product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_changes_to_product', to='quotations.painttype')),
                ('new_service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_changes_to_service', to='quotations.servicetype')),
                ('original_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_changes_from_brand', to='quotations.paintbrand')),
                ('original_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_change_lines', to='quotations.quotationitem')),
                ('original_product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_changes_from_product', to='quotations.painttype')),
                ('original_service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_changes_from_service', to='quotations.servicetype')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_change_lines', to='quotations.quotationroom')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_change_lines', to='quotations.unit')),
                ('work_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.workchange')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('changed_quantity__gte', 0)), name='work_change_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('completed_quantity__gte', 0)), name='work_change_completed_nonnegative')],
            },
        ),
    ]
