# Generated by Django 5.2.17 on 2026-09-19 13:43

from django.db import migrations, models


def backfill_deduction_targets(apps, schema_editor):
    MeasurementOpening = apps.get_model("quotations", "MeasurementOpening")
    for opening in MeasurementOpening.objects.select_related("surface").all().iterator():
        opening.deduct_from_surface_type = opening.surface.surface_type
        opening.deduct_from_group_name = (
            opening.surface.area_group_name
            if opening.surface.surface_type == "OTHER"
            else ""
        )
        opening.save(update_fields=("deduct_from_surface_type", "deduct_from_group_name"))


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0081_measurementsurface_area_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementopening',
            name='deduct_from_group_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='measurementopening',
            name='deduct_from_surface_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyroom',
            name='section',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(backfill_deduction_targets, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='measurementopening',
            name='opening_type',
            field=models.CharField(choices=[('DOOR', 'Door'), ('WINDOW', 'Window'), ('OPENING', 'Opening'), ('VENT', 'Vent'), ('SKYLIGHT', 'Skylight'), ('STAIR_OPENING', 'Stair opening'), ('GATE', 'Gate'), ('GRILL', 'Grill'), ('WARDROBE', 'Wardrobe'), ('CEILING', 'Ceiling'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='measurementsurface',
            name='surface_type',
            field=models.CharField(choices=[('WALL', 'Wall'), ('CEILING', 'Ceiling'), ('FLOOR', 'Floor'), ('WOOD_WORK', 'Wood Work'), ('TILE', 'Tile / Tiling'), ('WALLPAPER', 'Wallpaper'), ('METAL', 'Metal'), ('GLASS', 'Glass'), ('DOOR', 'Paintable door'), ('WINDOW', 'Paintable window'), ('COLUMN', 'Column'), ('BEAM', 'Beam'), ('GATE', 'Gate'), ('GRILL', 'Grill'), ('BALCONY_SOFFIT', 'Balcony ceiling'), ('STAIR_SOFFIT', 'Staircase ceiling'), ('PORCH_CEILING', 'Porch ceiling'), ('WATERPROOFING', 'Floor / terrace waterproofing'), ('PARAPET', 'Parapet wall'), ('OTHER', 'Other / manual')], max_length=30),
        ),
    ]
