# Generated by Django 5.2.17 on 2026-09-19 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_surface_types(apps, schema_editor):
    SurfaceType = apps.get_model("quotations", "MeasurementSurfaceType")
    for name in (
        "Wall", "Ceiling", "Floor", "Gate", "Grill",
        "Texture", "Wood Work", "Tile / Tiling", "Wallpaper",
        "Metal", "Glass", "Column", "Beam",
    ):
        SurfaceType.objects.get_or_create(name=name, created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0082_measurementopening_deduct_from_group_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSurfaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Measurement surface type',
                'verbose_name_plural': 'Measurement surface types',
            },
        ),
        migrations.RunPython(seed_surface_types, migrations.RunPython.noop),
    ]
