# Generated by Django 5.2.17 on 2026-09-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0084_customer_activation_and_invoice_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymeasurement',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
