# Generated by Django 5.2.17 on 2026-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0102_platform_integration_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
