# Generated by Django 5.2.17 on 2026-09-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0103_property_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contractor_hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
