# Generated by Django 5.2.17 on 2026-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0104_property_contractor_hidden_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='accepted_via_receipt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
