# Generated by Django 5.2.17 on 2026-10-01 05:14

from django.db import migrations, models


MASTER_MODELS = (
    "area",
    "measurementsurfacetype",
    "paintbrand",
    "painttype",
    "servicecategory",
    "servicetype",
    "unit",
    "workdescription",
)


def seed_sort_order(apps, schema_editor):
    """Give existing rows a stable order based on their primary key.

    The list endpoints previously had no ordering, so responses came back in
    primary-key order. Without this every row would land on sort_order=0 and the
    new order_by would fall back to alphabetical, silently reshuffling every
    dropdown that consumes these tables.
    """
    for model_name in MASTER_MODELS:
        model = apps.get_model("quotations", model_name)
        for index, pk in enumerate(model.objects.order_by("pk").values_list("pk", flat=True), start=1):
            model.objects.filter(pk=pk).update(sort_order=index)
    apartment = apps.get_model("quotations", "apartmentcommunity")
    for index, pk in enumerate(apartment.objects.order_by("pk").values_list("pk", flat=True), start=1):
        apartment.objects.filter(pk=pk).update(sort_order=index)


def clear_sort_order(apps, schema_editor):
    for model_name in MASTER_MODELS:
        apps.get_model("quotations", model_name).objects.update(sort_order=0)
    apps.get_model("quotations", "apartmentcommunity").objects.update(sort_order=0)


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0105_quotation_accepted_via_receipt_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentcommunity',
            options={'ordering': ('sort_order', 'name', 'locality'), 'verbose_name_plural': 'Apartment communities'},
        ),
        migrations.AlterModelOptions(
            name='workdescription',
            options={'ordering': ('service_type__name', 'sort_order', 'name')},
        ),
        migrations.AddField(
            model_name='apartmentcommunity',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurementsurfacetype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paintbrand',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='painttype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workdescription',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_sort_order, clear_sort_order),
    ]
