# Generated by Django 5.2.17 on 2026-10-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0106_alter_apartmentcommunity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataSortPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=64)),
                ('entry_id', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_data_sort_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'entry_id'),
                'unique_together': {('user', 'section', 'entry_id')},
            },
        ),
    ]
