# Generated by Django 5.2.17 on 2026-10-01 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0108_support_ticket_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='contractor_label',
            field=models.CharField(default='Painter', help_text='Role label, e.g. "Painter" or "Contractor".', max_length=60),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='employee_plural_label',
            field=models.CharField(default='Employees', max_length=60),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='employee_singular_label',
            field=models.CharField(default='Employee', max_length=60),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(choices=[('PAINT_ROLLER', 'Paint roller'), ('BRUSH', 'Brush'), ('SPRAY', 'Spray'), ('WATERPROOFING', 'Waterproofing'), ('PUTTY', 'Putty and wall care'), ('INTERIOR', 'Interior design'), ('ELECTRICAL', 'Electrical'), ('PLUMBING', 'Plumbing'), ('CARPENTRY', 'Carpentry'), ('HVAC', 'HVAC'), ('FLOORING', 'Flooring'), ('FURNITURE', 'Furniture'), ('LANDSCAPING', 'Landscaping'), ('GENERAL', 'General handyman')], default='PAINT_ROLLER', max_length=30),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_provider_selectable',
            field=models.BooleanField(default=True, help_text='Contractors can add this service to their profile.'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordering hint used when a profile lists its services.'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='units',
            field=models.ManyToManyField(blank=True, help_text='Units offered by this service.', related_name='service_categories', to='quotations.unit'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='workspace_name',
            field=models.CharField(default='Bharath Painters', help_text='Workspace name shown when this is the core service.', max_length=150),
        ),
        migrations.CreateModel(
            name='ContractorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONNECTED', 'Connected'), ('REJECTED', 'Rejected'), ('RECONNECT_PENDING', 'Reconnect pending'), ('DISCONNECTED', 'Disconnected'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('status_before_block', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONNECTED', 'Connected'), ('REJECTED', 'Rejected'), ('RECONNECT_PENDING', 'Reconnect pending'), ('DISCONNECTED', 'Disconnected'), ('BLOCKED', 'Blocked')], max_length=20)),
                ('discover_method', models.CharField(blank=True, choices=[('SEARCH', 'Search'), ('COMPLETED_WORK', 'Completed work together'), ('INVITATION', 'Invitation'), ('REFERRAL', 'Referral')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=150)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('is_favourite', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('completed_work_orders', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_connections_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_connections_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('requester', models.F('recipient')), _negated=True), name='contractor_connection_not_self'), models.UniqueConstraint(fields=('requester', 'recipient'), name='unique_contractor_connection_pair')],
            },
        ),
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=20)),
                ('handling', models.CharField(choices=[('INTERNAL', 'In-house'), ('OUTSOURCED', 'Outsourced')], default='INTERNAL', max_length=20)),
                ('measurement_version', models.PositiveIntegerField(blank=True, null=True)),
                ('category_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('work_description_snapshot', models.CharField(blank=True, max_length=200)),
                ('unit_name_snapshot', models.CharField(blank=True, max_length=40)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scopes', to='quotations.servicecategory')),
                ('measurement_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scopes', to='quotations.propertymeasurement')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='quotations.quotation')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scopes', to='quotations.unit')),
                ('work_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scopes', to='quotations.workdescription')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('quotation', 'reference'), name='unique_project_scope_reference_per_quotation')],
            },
        ),
    ]
