# Generated by Django 5.2.17 on 2026-10-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0114_quotationitem_specification_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount_mode',
            field=models.CharField(choices=[('OVERALL', 'Overall'), ('LINE', 'Per line')], default='OVERALL', max_length=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
