import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import React from "react";
import { create, act } from "react-test-renderer";
import { transformWithOxc } from "vite";
import { measurement } from "./fixtures.js";

// Compile the isolated JSX in memory; no application entry point or generated source edits.
const sourceUrl = new URL("./QuotationGroupingTest.jsx", import.meta.url);
const source = (await fs.readFile(sourceUrl, "utf8")).replace(/^import\s+["'][^"']+\.css["'];?\s*$/gm, "");
const transformed = await transformWithOxc(source, sourceUrl.pathname, { jsx: { runtime: "automatic" } });
const code = transformed.code.replace(/from\s+(["'])([^"']+)\1/g, (_match, _quote, specifier) => `from ${JSON.stringify(specifier.startsWith(".") ? new URL(specifier, sourceUrl).href : import.meta.resolve(specifier))}`);
const { default: QuotationGroupingTest } = await import(`data:text/javascript;base64,${Buffer.from(code).toString("base64")}`);
const text = (node) => typeof node === "string" || typeof node === "number" ? String(node) : (node?.children || []).map(text).join("");
const byText = (root, type, label) => root.findAllByType(type).find((node) => text(node) === label);
const containing = (root, type, label) => root.findAllByType(type).find((node) => text(node).startsWith(label));

test("isolated UI supports grouping, duplicate prevention, special edits and pricing without API calls", async () => {
  const previousDocument = globalThis.document;
  const previousFetch = globalThis.fetch;
  const previousAct = globalThis.IS_REACT_ACT_ENVIRONMENT;
  const measurementBefore = JSON.stringify(measurement);
  let apiCalls = 0;
  globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  globalThis.fetch = () => { apiCalls += 1; throw new Error("The isolated module must not call APIs."); };
  globalThis.document = { body: { style: { overflow: "" } }, activeElement: { focus() {} }, addEventListener() {}, removeEventListener() {} };
  let view;
  try {
    await act(async () => { view = create(React.createElement(QuotationGroupingTest), { createNodeMock: () => ({ querySelector: () => ({ focus() {} }), querySelectorAll: () => [] }) }); });
    assert.match(text(view.root), /ISOLATED TEST MODULE/);
    assert.equal(view.root.findAllByType("input").length, 0, "Measurements are read-only");
    const nav = async (index) => act(async () => view.root.findByType("nav").findAllByType("button")[index].props.onClick());
    const click = async (label) => act(async () => { const scope = view.root.findAllByProps({ role: "dialog" })[0] || view.root; const button = byText(scope, "button", label); assert.ok(button, label); button.props.onClick(); });
    await act(async () => view.root.findByProps({ "aria-label": "View original measurement records for Bedroom 1" }).props.onClick());
    const recordsDialog = view.root.findByProps({ role: "dialog" });
    assert.match(text(recordsDialog), /Bedroom 1/);
    assert.match(text(recordsDialog), /Wall 4/);
    assert.match(text(recordsDialog), /125 sqft/);
    assert.equal(recordsDialog.findAllByType("input").length, 0);
    await click("Close");
    assert.equal(view.root.findAllByProps({ role: "dialog" }).length, 0);
    await nav(1);
    await click("Create Paint Group");
    assert.equal(view.root.findAllByProps({ role: "dialog" }).length, 1);
    assert.equal(view.root.findAllByType("input").filter((node) => node.props.type === "number").length, 0, "No manual area or pricing input in grouping");
    assert.equal(view.root.findAllByType("input").filter((node) => node.props.type === "checkbox").length, 7);
    assert.equal(view.root.findAllByType("label").some((node) => /Wall [1-4]/.test(text(node))), false, "Normal grouping hides individual walls");
    for (const name of ["Bedroom 1", "Bedroom 2", "Bedroom 3"]) await act(async () => containing(view.root, "label", name).findByType("input").props.onChange());
    assert.match(text(view.root), /Selected: 3 Rooms/);
    assert.match(text(view.root), /Total Area: 1,300 sqft/);
    await click("Continue");
    const nameInput = containing(view.root, "label", "Group Name").findByType("input");
    await act(async () => nameInput.props.onChange({ target: { value: "Bedrooms Walls" } }));
    assert.ok(containing(view.root, "label", "Product"));
    assert.ok(view.root.findByProps({ "aria-label": "Assignment rate" }));
    assert.match(text(containing(view.root, "label", "Type of service")), /Painting/);
    await click("Save Paint Group");
    assert.equal(view.root.findAllByProps({ role: "dialog" }).length, 0);
    assert.match(text(view.root), /Bedrooms Walls/);
    assert.match(text(view.root), /1,300 sqft/);
    await click("Room contribution details");
    assert.match(text(view.root.findByProps({ role: "dialog" })), /Bedroom 1/);
    assert.match(text(view.root.findByProps({ role: "dialog" })), /470 sqft/);
    await click("Close");
    await click("Add General Service");
    assert.match(text(view.root.findByProps({ role: "dialog" })), /Plumbing/);
    assert.match(text(view.root.findByProps({ role: "dialog" })), /Carpentry/);
    await act(async () => containing(view.root, "label", "Brand").findByType("select").props.onChange({ target: { value: "2" } }));
    assert.match(text(containing(view.root, "label", "Product")), /CPVC Pipe/);
    await act(async () => containing(view.root, "label", "Product").findByType("select").props.onChange({ target: { value: "7" } }));
    assert.equal(containing(view.root, "label", "Surface"), undefined);
    await act(async () => containing(view.root, "label", "Description").findByType("textarea").props.onChange({ target: { value: "Repair kitchen tap" } }));
    await click("Save General Service");
    assert.match(text(view.root), /Plumbing/);
    const plumbingCard = view.root.findAllByType("article").find((node) => text(node).startsWith("Plumbing"));
    assert.match(text(plumbingCard), /CPVC Pipe/);
    assert.match(text(plumbingCard), /Berger/);
    assert.match(text(plumbingCard), /Surface/);
    await act(async () => byText(plumbingCard, "button", "Edit").props.onClick());
    assert.equal(containing(view.root, "label", "Product").findByType("select").props.value, 7);
    assert.equal(containing(view.root, "label", "Brand").findByType("select").props.value, 2);
    assert.equal(containing(view.root, "label", "Surface"), undefined);
    await click("Cancel");

    await click("Create Paint Group");
    const assignedBedroom = containing(view.root, "label", "Bedroom 1");
    assert.equal(assignedBedroom.findByType("input").props.disabled, true);
    assert.match(text(assignedBedroom), /Assigned - Tractor Emulsion/);
    await click("Select all");
    assert.match(text(view.root), /Selected: 4 Rooms/);
    assert.match(text(view.root), /Total Area: 1,270 sqft/);
    assert.equal(containing(view.root, "label", "Bedroom 1").findByType("input").props.checked, false);
    await click("Clear selection");
    assert.match(text(view.root), /Selected: 0 Rooms/);
    const surface = containing(view.root, "label", "1. Select Surface").findByType("select");
    await act(async () => surface.props.onChange({ target: { value: "CEILING" } }));
    await click("Select all");
    assert.match(text(view.root), /Selected: 7 Rooms/);
    assert.match(text(view.root), /Total Area: 780 sqft/);
    await act(async () => surface.props.onChange({ target: { value: "DOOR" } }));
    await click("Select all");
    assert.match(text(view.root), /Selected: 1 Rooms/);
    assert.match(text(view.root), /Total Area: 24 sqft/);
    await click("Cancel");

    const bedroomsCard = view.root.findAllByType("article").find((node) => text(node).startsWith("Bedrooms Walls"));
    await act(async () => byText(bedroomsCard, "button", "Edit").props.onClick());
    await click("Select all");
    assert.match(text(view.root), /Selected: 7 Rooms/);
    assert.match(text(view.root), /Total Area: 2,570 sqft/);
    await click("Cancel");

    await click("Load example");
    assert.match(text(view.root), /1,175 sqft/);
    assert.match(text(view.root), /125 sqft/);
    const specialCard = view.root.findAllByType("article").find((node) => text(node).startsWith("Texture Wall"));
    await act(async () => byText(specialCard, "button", "Edit").props.onClick());
    assert.ok(containing(view.root, "label", "Wall 4"));
    await act(async () => containing(view.root, "label", "Wall 4").findByType("input").props.onChange());
    await act(async () => containing(view.root, "label", "Wall 3").findByType("input").props.onChange());
    await click("Continue");
    await click("Save Special Wall");
    assert.match(text(view.root), /1,190 sqft/);
    const editedCard = view.root.findAllByType("article").find((node) => text(node).startsWith("Texture Wall"));
    await act(async () => byText(editedCard, "button", "Delete").props.onClick());
    assert.match(text(view.root), /1,300 sqft/);

    await click("Load example");
    assert.equal(view.root.findByType("nav").findAllByType("button").length, 3);
    assert.match(text(view.root), /40,835/);
    const editBedrooms = async () => { const card = view.root.findAllByType("article").find((node) => text(node).startsWith("Bedrooms Walls")); await act(async () => byText(card, "button", "Edit").props.onClick()); await click("Continue"); };
    await editBedrooms();
    assert.match(text(containing(view.root, "label", "Type of service")), /Painting/);
    let tractorRate = view.root.findByProps({ "aria-label": "Assignment rate" });
    await act(async () => tractorRate.props.onChange({ target: { value: "11" } }));
    assert.match(text(view.root.findByProps({ role: "dialog" })), /12,925/);
    await click("Save Paint Group");
    assert.match(text(view.root), /42,010/);
    await editBedrooms();
    tractorRate = view.root.findByProps({ "aria-label": "Assignment rate" });
    await act(async () => tractorRate.props.onChange({ target: { value: "-1" } }));
    await click("Save Paint Group");
    assert.match(text(view.root), /Enter a non-negative rate/);
    await act(async () => tractorRate.props.onChange({ target: { value: "" } }));
    await click("Save Paint Group");
    assert.equal(view.root.findAllByType("button").find((node) => text(node) === "Continue").props.disabled, true);
    await nav(2);
    assert.match(text(view.root), /Enter a valid rate for each line first/);
    await editBedrooms();
    tractorRate = view.root.findByProps({ "aria-label": "Assignment rate" });
    await act(async () => tractorRate.props.onChange({ target: { value: "10" } }));
    await click("Save Paint Group");
    await nav(2);
    assert.match(text(view.root), /Final quotation test preview/);
    await act(async () => view.root.findByProps({ "aria-label": "View details for Bedrooms Walls" }).props.onClick());
    const finalDialog = view.root.findByProps({ role: "dialog" });
    assert.match(text(finalDialog), /Bedrooms Walls/);
    assert.match(text(finalDialog), /Tractor Emulsion/);
    assert.match(text(finalDialog), /Description \/ treatment/);
    assert.match(text(finalDialog), /1,175/);
    assert.match(text(finalDialog), /11,750/);
    assert.equal(finalDialog.findAllByType("input").length, 0);
    await click("Close");
    await act(async () => view.root.findByProps({ "aria-label": "Edit Bedrooms Walls" }).props.onClick());
    assert.match(text(view.root.findByProps({ role: "dialog" })), /Edit Paint Group/);
    await click("Cancel");
    await click("Inspect sample payload and measurement references");
    const payload = JSON.parse(text(view.root.findByType("pre")));
    assert.equal(payload.items[0].quantity, 1175);
    assert.equal(payload.test_trace[0].contributions[0].quantity, 345);
    assert.equal(payload.test_trace[0].contributions[0].measurement_version, 3);
    assert.equal(apiCalls, 0);
    assert.equal(JSON.stringify(measurement), measurementBefore);
    assert.equal(document.body.style.overflow, "");
  } finally {
    if (view) await act(async () => view.unmount());
    globalThis.document = previousDocument;
    globalThis.fetch = previousFetch;
    globalThis.IS_REACT_ACT_ENVIRONMENT = previousAct;
  }
});
