import hashlib
import json
from django.conf import settings


POLICY_VERSION = "2026-09-25"
EFFECTIVE_DATE = "25 September 2026"
LEGAL_CONTACT_EMAIL = settings.LEGAL_CONTACT_EMAIL
LEGAL_OPERATOR_NAME = settings.LEGAL_OPERATOR_NAME
LEGAL_OPERATOR_ADDRESS = settings.LEGAL_OPERATOR_ADDRESS


COMMON_TERMS = [
    {
        "title": "1. Agreement and eligibility",
        "body": (
            "These Terms govern use of the Bharath Painters website, progressive web application, "
            "mobile experience and related services (the Platform). By registering, you confirm that "
            "you are at least 18 years old, legally capable of entering a contract, and that the "
            "information you provide is accurate and belongs to you or is provided with lawful authority."
        ),
    },
    {
        "title": "2. Account security",
        "body": (
            "You must protect your password, OTP, recovery email and device access; use a unique password; "
            "log out from shared devices; and notify Bharath Painters promptly about suspected unauthorised "
            "access. Never share an OTP or password. You are responsible for activity performed through your "
            "account unless you promptly report compromise. Bharath Painters may require re-verification, "
            "suspend access, revoke sessions or reset credentials to protect users and the Platform."
        ),
    },
    {
        "title": "3. Permitted use and prohibited conduct",
        "body": (
            "Use the Platform only for lawful painting, property, quotation, scheduling, workforce and payment "
            "record activities. You must not impersonate another person; submit false documents; harass, threaten "
            "or exploit users; post sexual-abuse, drug-trafficking, hateful or illegal content; scrape or sell "
            "personal data; bypass permissions; probe security; upload malware; automate abusive traffic; reverse "
            "engineer protected components; manipulate ratings, invoices or records; or use the Platform for fraud."
        ),
    },
    {
        "title": "4. Platform records and electronic communications",
        "body": (
            "You agree that quotations, acceptances, connection requests, schedules, work updates, invoices, "
            "receipts, messages and notices may be created and delivered electronically. Keep your mobile number "
            "and email current. Records generated by the Platform support business administration but do not "
            "replace professional tax, accounting, legal, engineering or safety advice."
        ),
    },
    {
        "title": "5. Independent transactions",
        "body": (
            "Unless expressly stated otherwise, contractors and Paint Applicators are independent users and are "
            "not employees, agents or partners of Bharath Painters. Customers and service providers remain "
            "responsible for scope, measurements, site conditions, materials, pricing, taxes, permits, safety, "
            "insurance, payment, workmanship, cancellation and dispute resolution. Verify identities, scope and "
            "payment details before proceeding."
        ),
    },
    {
        "title": "6. Safety and lawful work",
        "body": (
            "Users must follow applicable labour, workplace, building, environmental, fire, hazardous-material, "
            "consumer, tax and local rules. Contractors must provide safe working conditions, appropriate training "
            "and protective equipment. Paint Applicators must follow lawful safety instructions and report unsafe "
            "conditions. No Platform feature authorises unsafe or unlawful work."
        ),
    },
    {
        "title": "7. Content and intellectual property",
        "body": (
            "You retain ownership of content you lawfully upload. You grant Bharath Painters a limited licence to "
            "host, process, reproduce and transmit that content only to operate, secure, support and improve the "
            "Platform and fulfil authorised transactions. Do not upload content that infringes privacy, copyright, "
            "trade marks or other rights. Platform software, branding and original design remain protected."
        ),
    },
    {
        "title": "8. Availability, changes and third-party services",
        "body": (
            "The Platform may use hosting, email, maps, messaging, payment and other third-party services. Their "
            "availability and separate terms may apply. Features may be maintained, changed or temporarily "
            "unavailable. Reasonable care will be used, but uninterrupted or error-free operation is not guaranteed. "
            "Keep independent copies of important business, tax and project records."
        ),
    },
    {
        "title": "9. Enforcement, suspension and termination",
        "body": (
            "Bharath Painters may investigate misuse and restrict or terminate accounts to protect users, comply "
            "with law, respond to security incidents or enforce these Terms. Users may stop using the Platform and "
            "request account closure, subject to lawful retention, unresolved transactions and fraud-prevention needs."
        ),
    },
    {
        "title": "10. Liability and statutory rights",
        "body": (
            "Nothing in these Terms excludes liability or consumer/data-protection rights that cannot lawfully be "
            "excluded. To the extent permitted by law, Bharath Painters is not responsible for indirect loss or for "
            "disputes, conduct, workmanship, delays or payment failures between independent users. Any limitation "
            "will be interpreted only to the extent permitted under applicable Indian law."
        ),
    },
    {
        "title": "11. Complaints, governing law and changes",
        "body": (
            f"Contact {LEGAL_CONTACT_EMAIL} for account, privacy, safety or grievance support. These Terms are "
            "governed by applicable laws of India. Courts with lawful jurisdiction over the Platform operator's "
            "registered office will have jurisdiction, subject to mandatory consumer remedies. Material policy "
            "changes will be versioned and, where required, presented for fresh acknowledgement or consent."
        ),
    },
]


ROLE_TERMS = {
    "CUSTOMER": {
        "title": "Customer responsibilities",
        "body": (
            "Confirm that property details, access permissions, measurements and instructions are accurate. Review "
            "quotation versions before acceptance, approve only intended contractor connections, protect occupants "
            "and valuables during work, and pay only against verified records. A contractor cannot access another "
            "contractor's private relationship data merely because both serve you."
        ),
    },
    "CONTRACTOR": {
        "title": "Contractor responsibilities",
        "body": (
            "You confirm authority to operate the registered business and remain responsible for licences, tax "
            "details, staff, subcontractors, wages, safety, quotations, invoices, receipts and customer commitments. "
            "Access customer information only through an authorised connection and only for that relationship. Do "
            "not copy, disclose or use another contractor's data or contact users for unrelated marketing."
        ),
    },
    "PAINTER": {
        "title": "Paint Applicator responsibilities",
        "body": (
            "Provide truthful identity, skills, availability, wage and experience information. Apply only for work "
            "you can safely perform, honour accepted assignments, communicate promptly, protect customer property "
            "and never transfer access or assignments outside approved Platform workflows. Employment and payment "
            "terms are agreed with the engaging contractor unless expressly stated otherwise."
        ),
    },
}


PRIVACY_SECTIONS = [
    {
        "title": "1. Personal data collected",
        "body": (
            "Depending on your role and use, the Platform may process name, mobile number, email, account and "
            "recovery details; Bharath ID and QR profile; business, tax and professional details; skills, wages and "
            "availability; customer, property, address, room and measurement data; quotations, approvals, schedules, "
            "invoices, receipts and payment references; messages, photos, documents and support records; approximate "
            "or precise location when you actively permit it; and device, IP, browser, authentication, security and "
            "activity logs. Passwords and OTPs are protected and must never be included in support messages."
        ),
    },
    {
        "title": "2. Why data is processed",
        "body": (
            "Data is processed to register and secure accounts; issue role IDs and QR profiles; connect customers "
            "with authorised contractors; support quotations, area calculations, work, staffing, billing and "
            "communications; provide location-based job functions when enabled; prevent fraud and abuse; investigate "
            "safety or security reports; provide support; maintain records; comply with law; and improve reliability. "
            "Data will not be used for an unrelated purpose without an appropriate notice or lawful basis."
        ),
    },
    {
        "title": "3. Consent and choices",
        "body": (
            "Where processing relies on consent, it should be free, specific, informed, unconditional and capable of "
            "withdrawal with comparable ease. You may deny optional location, profile-sharing or communication "
            "permissions, although the related feature may then be unavailable. Withdrawing consent does not make "
            "earlier lawful processing invalid and does not prevent retention required by law or an active transaction."
        ),
    },
    {
        "title": "4. Sharing and relationship isolation",
        "body": (
            "Information is shared only as needed with users you connect or transact with, authorised administrators, "
            "and vetted hosting, email, map, messaging, payment, analytics, security and support providers acting for "
            "the Platform. Contractors must not see another contractor's private measurements, pricing, quotations, "
            "projects, notes or files. Data may be disclosed to authorities or advisers when lawfully required, to "
            "protect rights and safety, or during a properly safeguarded business reorganisation."
        ),
    },
    {
        "title": "5. Retention and deletion",
        "body": (
            "Account and operational data is retained only as long as reasonably necessary for the stated purpose, "
            "security, disputes, tax/accounting obligations and applicable law. Some transaction and audit records may "
            "remain after account closure. Data scheduled for deletion may persist briefly in protected backups until "
            "normal backup expiry. Anonymised information that no longer identifies a person may be retained."
        ),
    },
    {
        "title": "6. Security safeguards and incidents",
        "body": (
            "Bharath Painters uses access controls, role and relationship permissions, password hashing, OTP controls, "
            "encrypted transport, logging, backups, dependency maintenance and incident-response measures appropriate "
            "to the service. No system is risk-free. Suspected compromise should be reported immediately. Security and "
            "personal-data incidents will be assessed, contained and notified to affected persons and authorities where "
            "applicable law requires."
        ),
    },
    {
        "title": "7. Your rights and duties",
        "body": (
            "Subject to applicable law, you may request information about processing, correction, completion, updating "
            "or erasure of personal data, withdraw consent, nominate another person where legally available, and use "
            "the grievance process. You must provide authentic information, avoid impersonation, respect other users' "
            "rights and not file false or frivolous complaints. Identity verification may be required before action."
        ),
    },
    {
        "title": "8. Children, cross-border processing and contact",
        "body": (
            f"The Platform is intended for adults and must not knowingly be used to register a child. Service providers "
            "may process data from locations permitted under Indian law with contractual and security safeguards. For "
            f"privacy questions, rights requests or grievances, contact {LEGAL_CONTACT_EMAIL}. Keep a copy of this "
            "notice and the policy version shown with your acceptance."
        ),
    },
]


REFERENCES = [
    {"label": "Digital Personal Data Protection Act, 2023", "url": "https://www.meity.gov.in/static/uploads/2024/02/Digital-Personal-Data-Protection-Act-2023.pdf"},
    {"label": "Digital Personal Data Protection Rules, 2025", "url": "https://www.meity.gov.in/documents/act-and-policies/digital-personal-data-protection-rules-2025-gDOxUjMtQWa"},
    {"label": "Information Technology Act, 2000", "url": "https://www.indiacode.nic.in/handle/123456789/1999"},
    {"label": "CERT-In Directions", "url": "https://www.cert-in.org.in/Directions70B.jsp"},
]


def registration_legal_payload(role):
    normalized_role = str(role or "").upper()
    role_section = ROLE_TERMS.get(normalized_role)
    terms = [*COMMON_TERMS]
    if role_section:
        terms.insert(2, role_section)
    return {
        "policy_version": POLICY_VERSION,
        "effective_date": EFFECTIVE_DATE,
        "role": normalized_role,
        "operator_name": LEGAL_OPERATOR_NAME,
        "operator_address": LEGAL_OPERATOR_ADDRESS,
        "terms_title": "Bharath Painters Terms of Use",
        "terms_sections": terms,
        "privacy_title": "Privacy and Data Protection Notice",
        "privacy_sections": PRIVACY_SECTIONS,
        "contact_email": LEGAL_CONTACT_EMAIL,
        "references": REFERENCES,
    }


def document_hashes(role):
    payload = registration_legal_payload(role)
    terms = json.dumps(payload["terms_sections"], sort_keys=True, separators=(",", ":"))
    privacy = json.dumps(payload["privacy_sections"], sort_keys=True, separators=(",", ":"))
    return (
        hashlib.sha256(terms.encode("utf-8")).hexdigest(),
        hashlib.sha256(privacy.encode("utf-8")).hexdigest(),
    )
