export const CUSTOMER_STATUSES = ["NEW", "CONTACTED", "FOLLOW_UP", "SITE_VISIT", "QUOTATION_SENT", "NEGOTIATION", "WON", "LOST", "CANCELLED"];
export const CUSTOMER_SOURCES = ["WEBSITE", "PHONE", "WHATSAPP", "FACEBOOK", "INSTAGRAM", "GOOGLE", "REFERRAL", "WALK_IN", "OTHER"];
