# Generated by Django 5.2.17 on 2026-08-13 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=20)),
                ('number_of_painters', models.PositiveIntegerField(default=1)),
                ('required_experience', models.PositiveIntegerField(default=0)),
                ('required_skills', models.TextField(blank=True)),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekly_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('estimated_days', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Filled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('COMPLETED', 'Completed')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'painter')},
            },
        ),
    ]
