# Generated by Django 5.2.17 on 2026-09-07 13:24

from django.db import migrations, models


def backfill_advance_receipts(apps, schema_editor):
    WorkSchedule = apps.get_model('jobs', 'WorkSchedule')
    for schedule in WorkSchedule.objects.filter(payment_status='CONFIRMED', advance_amount__gt=0):
        schedule.advance_receipt_number = f"ADV-{schedule.payment_confirmed_at or schedule.updated_at:%Y%m%d}-{schedule.id:04d}"
        schedule.save(update_fields=('advance_receipt_number',))


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_workschedulepainter_on_the_way_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='advance_receipt_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(backfill_advance_receipts, migrations.RunPython.noop),
    ]
