# Generated by Django 5.2.17 on 2026-09-10 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_workschedule_advance_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_photos/%Y/%m/')),
                ('stage', models.CharField(choices=[('BEFORE', 'Before work'), ('PROGRESS', 'Work in progress'), ('AFTER', 'After completion')], default='PROGRESS', max_length=20)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_photos', to='jobs.workschedule')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
    ]
