# Generated by Django 5.2.17 on 2026-09-10 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_workphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contractorapplicatorteam',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code', ''), _negated=True), fields=('contractor', 'employee_code'), name='unique_employee_code_per_contractor'),
        ),
    ]
