import { useCallback, useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import { Check, Edit3, Plus, Power, Trash2, X } from "lucide-react";
import api from "../api/client";
import useAuth from "../context/useAuth";

const emptyForm = { name:"", audience:"CONTRACTOR", billing_cycle:"MONTHLY", validity:"ONE_MONTH", price:"0", discount_percentage:"0", job_post_limit:"", quotation_limit:"", employee_limit:"", applicator_access:"NONE", measurement_access:false, register_applicator_access:false, ratings_reviews_access:false, work_schedules_access:false, seeking_applicators_access:false, property_creation_access:false, messages_access:false, job_seeking_post_limit:"", contractor_job_access:false, contractor_visibility:false, booking_requests:false, availability_calendar:false, location_limit:"", features:"", is_active:true };
const numberOrNull = value => value === "" ? null : Number(value);

export default function Billing(){
  const {user}=useAuth(); const [plans,setPlans]=useState([]); const [form,setForm]=useState(null); const [editing,setEditing]=useState(null); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{const{data}=await api.get("/billing/plans/");setPlans(data);setError("")}catch{setError("Packages could not be loaded.")}},[]);
  useEffect(()=>{if(user?.role==="ADMIN")load()},[load,user]);
  if(user?.role!=="ADMIN")return <Navigate to="/dashboard" replace/>;
  const openCreate=()=>{setEditing(null);setForm({...emptyForm});setError("")};
  const openEdit=plan=>{setEditing(plan.id);setForm({...emptyForm,...plan,price:String(plan.price),discount_percentage:String(plan.discount_percentage||0),job_post_limit:plan.job_post_limit??"",quotation_limit:plan.quotation_limit??"",employee_limit:plan.employee_limit??"",job_seeking_post_limit:plan.job_seeking_post_limit??"",location_limit:plan.location_limit??"",features:(plan.features||[]).join("\n")})};
  const save=async e=>{e.preventDefault();setSaving(true);setError("");const payload={...form,billing_cycle:"MONTHLY",price:form.price||0,job_post_limit:numberOrNull(form.job_post_limit),quotation_limit:numberOrNull(form.quotation_limit),employee_limit:numberOrNull(form.employee_limit),job_seeking_post_limit:numberOrNull(form.job_seeking_post_limit),location_limit:numberOrNull(form.location_limit)};try{if(editing)await api.patch(`/billing/plans/${editing}/`,payload);else await api.post("/billing/plans/",payload);setForm(null);setMessage(editing?"Subscription package updated.":"Subscription package created.");await load()}catch(err){const data=err.response?.data||{};setError(data.detail||Object.values(data).flat().join(" ")||"Package could not be saved.")}finally{setSaving(false)}};
  const toggle=async plan=>{await api.patch(`/billing/plans/${plan.id}/`,{is_active:!plan.is_active});setMessage(plan.is_active?"Package deactivated.":"Package activated.");load()};
  const remove=async plan=>{if(!window.confirm(`Delete ${plan.name}?`))return;try{const{data}=await api.delete(`/billing/plans/${plan.id}/`);setMessage(data?.detail||"Package deleted.");load()}catch(err){setError(err.response?.data?.detail||"Package could not be deleted.")}};
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-amber-600">Package configuration</p><h1 className="mt-1 text-3xl font-bold">Packages</h1><p className="mt-2 text-slate-500">Create and manage package prices, validity and feature limits.</p></div><button onClick={openCreate} className="flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white"><Plus className="h-5 w-5"/>Create package</button></header>
    {message&&<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</p>}{error&&<p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Package</th><th className="px-5 py-4">Portal</th><th className="px-5 py-4">Validity</th><th className="px-5 py-4">Price / Discount</th><th className="px-5 py-4">Controls</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{plans.map(plan=><tr key={plan.id} className={!plan.is_active?"opacity-55":""}><td className="px-5 py-4 font-bold">{plan.name}</td><td className="px-5 py-4">{plan.audience==="PAINTER"?"Paint Applicator":"Contractor"}</td><td className="px-5 py-4">{validityLabel(plan.validity)}</td><td className="px-5 py-4"><p className="font-semibold">{Number(plan.discounted_price)===0?"Free":`₹${Number(plan.discounted_price).toLocaleString("en-IN")}`}</p>{Number(plan.discount_percentage)>0&&<p className="mt-1 text-xs text-slate-500"><span className="line-through">₹{Number(plan.price).toLocaleString("en-IN")}</span> · {Number(plan.discount_percentage)}% off</p>}</td><td className="max-w-md px-5 py-4 text-slate-600">{controlSummary(plan)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${plan.is_active!==false?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{plan.is_active!==false?"Active":"Inactive"}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><IconButton title="Edit" onClick={()=>openEdit(plan)} icon={Edit3}/><IconButton title={plan.is_active!==false?"Deactivate":"Activate"} onClick={()=>toggle(plan)} icon={Power}/><IconButton danger title="Delete" onClick={()=>remove(plan)} icon={Trash2}/></div></td></tr>)}</tbody></table></div>{!plans.length&&<p className="p-10 text-center text-slate-400">No packages created.</p>}</div>
    {form&&<PackageForm form={form} setForm={setForm} editing={editing} saving={saving} save={save} close={()=>setForm(null)}/>} 
  </div>;
}

function PackageForm({form,setForm,editing,saving,save,close}){const set=(key,value)=>setForm({...form,[key]:value});return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={save} className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-amber-600">{editing?"Edit":"New"} monthly package</p><h2 className="text-2xl font-bold">Subscription controls</h2></div><button type="button" onClick={close} className="rounded-lg p-2 hover:bg-slate-100"><X/></button></div>
  <div className="grid gap-5 md:grid-cols-2"><Field label="Package name"><input required value={form.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Portal"><select value={form.audience} onChange={e=>set("audience",e.target.value)}><option value="CONTRACTOR">Contractor</option><option value="PAINTER">Paint Applicator</option></select></Field><Field label="Validity"><select value={form.validity} onChange={e=>set("validity",e.target.value)}><option value="ONE_MONTH">1 month</option><option value="THREE_MONTHS">3 months</option><option value="SIX_MONTHS">6 months</option><option value="ONE_YEAR">1 year</option><option value="CUSTOM_DATES">Custom dates</option></select></Field><Field label="Original monthly price (₹)"><input type="number" min="0" step="0.01" value={form.price} onChange={e=>set("price",e.target.value)}/></Field><Field label="Discount (%)" hint="Enter any value from 0 to 100"><input type="number" min="0" max="100" step="0.01" value={form.discount_percentage} onChange={e=>set("discount_percentage",e.target.value)}/></Field><div className="rounded-xl bg-emerald-50 p-4"><p className="text-sm text-emerald-700">Final monthly price</p><p className="mt-1 text-2xl font-bold text-emerald-900">₹{Math.max(0,Number(form.price||0)*(100-Number(form.discount_percentage||0))/100).toLocaleString("en-IN",{maximumFractionDigits:2})}</p></div></div>
  <section className="mt-6 rounded-2xl bg-slate-50 p-5"><h3 className="font-bold">{form.audience==="CONTRACTOR"?"Contractor controls":"Paint Applicator controls"}</h3><p className="mt-1 text-xs text-slate-500">Leave a numeric limit empty for unlimited access.</p><div className="mt-4 grid gap-5 md:grid-cols-2">{form.audience==="CONTRACTOR"?<><Limit label="Job post limit" value={form.job_post_limit} set={v=>set("job_post_limit",v)}/><Limit label="Quotation limit" value={form.quotation_limit} set={v=>set("quotation_limit",v)}/><Limit label="In-house employee limit" value={form.employee_limit} set={v=>set("employee_limit",v)}/><Field label="Paint Applicator access"><select value={form.applicator_access} onChange={e=>set("applicator_access",e.target.value)}><option value="NONE">No access</option><option value="VIEW">View availability</option><option value="CONTACT">View and contact</option><option value="BOOK">View, contact and book</option></select></Field><Toggle label="Area Calculator access" checked={form.measurement_access} set={v=>set("measurement_access",v)}/><Toggle label="Register Applicator" checked={form.register_applicator_access} set={v=>set("register_applicator_access",v)}/><Toggle label="Ratings & Reviews" checked={form.ratings_reviews_access} set={v=>set("ratings_reviews_access",v)}/><Toggle label="Work schedules" checked={form.work_schedules_access} set={v=>set("work_schedules_access",v)}/><Toggle label="Paint Applicators seeking work" checked={form.seeking_applicators_access} set={v=>set("seeking_applicators_access",v)}/><Toggle label="Property creation" checked={form.property_creation_access} set={v=>set("property_creation_access",v)}/><Toggle label="Messages" checked={form.messages_access} set={v=>set("messages_access",v)}/></>:<><Limit label="Job-seeking post limit" value={form.job_seeking_post_limit} set={v=>set("job_seeking_post_limit",v)}/><Limit label="Work-location PIN code limit" value={form.location_limit} set={v=>set("location_limit",v)}/><Toggle label="View and apply for contractor jobs" checked={form.contractor_job_access} set={v=>set("contractor_job_access",v)}/><Toggle label="Profile visible to contractors" checked={form.contractor_visibility} set={v=>set("contractor_visibility",v)}/><Toggle label="Receive booking requests" checked={form.booking_requests} set={v=>set("booking_requests",v)}/><Toggle label="Availability calendar" checked={form.availability_calendar} set={v=>set("availability_calendar",v)}/></>}</div></section>
  {form.validity==="CUSTOM_DATES"&&<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Start and end dates will be selected when this package is assigned or purchased.</p>}
  <div className="mt-5"><Field label="Additional benefits" hint="Enter one benefit on each line"><textarea rows="4" value={form.features} onChange={e=>set("features",e.target.value)}/></Field></div><Toggle label="Package is active" checked={form.is_active} set={v=>set("is_active",v)}/><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl border px-5 py-3 font-semibold">Cancel</button><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white disabled:opacity-50"><Check className="h-5 w-5"/>{saving?"Saving...":"Save package"}</button></div></form></div>}
function Field({label,hint,children}){return <label className="block"><span className="mb-2 block font-semibold">{label}</span>{children}{hint&&<span className="mt-1 block text-xs text-slate-400">{hint}</span>}</label>}
function Limit({label,value,set}){return <Field label={label} hint="Empty = Unlimited"><input type="number" min="1" value={value} onChange={e=>set(e.target.value)} placeholder="Unlimited"/></Field>}
function Toggle({label,checked,set}){return <label className="flex items-center gap-3 rounded-xl border bg-white p-4"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)} className="h-5 w-5"/><span className="font-semibold">{label}</span></label>}
function IconButton({icon:Icon,...props}){const{danger,...buttonProps}=props;return <button {...buttonProps} className={`rounded-lg border p-2 ${danger?"text-red-600 hover:bg-red-50":"hover:bg-slate-50"}`}><Icon className="h-4 w-4"/></button>}
function validityLabel(value){return({ONE_MONTH:"1 month",THREE_MONTHS:"3 months",SIX_MONTHS:"6 months",ONE_YEAR:"1 year",CUSTOM_DATES:"Custom dates"})[value]||"1 month"}
function limit(value){return value==null?"Unlimited":value}
function controlSummary(plan){return plan.audience==="CONTRACTOR"?`${limit(plan.job_post_limit)} job posts · ${limit(plan.quotation_limit)} quotations · ${limit(plan.employee_limit)} employees · ${plan.measurement_access?"Area Calculator enabled":"No Area Calculator access"} · ${String(plan.applicator_access||"NONE").toLowerCase().replaceAll("_"," ")}`:`${limit(plan.job_seeking_post_limit)} seeking posts · ${limit(plan.location_limit)} PIN codes · ${plan.contractor_job_access?"Job access":"No job access"}`}
