import { useCallback, useEffect, useState } from "react";
import { Check, Download, PackageCheck, X } from "lucide-react";
import api from "../api/client";
import useAuth from "../context/useAuth";
import { previewPdf } from "../components/PdfPreview";

export default function ContractorPackages(){
  const {user}=useAuth(); const [data,setData]=useState(null); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [selected,setSelected]=useState(null); const [payment,setPayment]=useState(null); const [months,setMonths]=useState(1);
  const load=useCallback(()=>api.get("/billing/contractor-packages/").then(({data})=>{setData(data);setError("")}).catch(()=>setError("Subscriptions could not be loaded.")),[]); useEffect(()=>{load()},[load]);
  const register=async e=>{e.preventDefault();setError("");try{const{data:r}=await api.post("/billing/contractor-packages/",{plan_id:selected.id,duration_months:months});setMessage(r.message);setSelected(null);await load();if(r.request?.payment_status==="AWAITING")setPayment({...r.request,payment_mode:"UPI",payment_reference:"",payment_note:""})}catch(err){const d=err.response?.data||{};setError(d.detail||d.duration_months||d.plan_id||"Registration could not be completed.")}};
  const submitPayment=async e=>{e.preventDefault();try{const{data:r}=await api.post(`/billing/package-requests/${payment.id}/payment/`,payment);setMessage(r.message);setPayment(null);load()}catch(err){const d=err.response?.data||{};setError(d.detail||d.payment_mode||d.payment_reference||"Payment could not be submitted.")}};
  const document=async id=>{try{const r=await api.get(`/billing/package-requests/${id}/document/`,{responseType:"blob"});previewPdf(r.data,"billing-document.pdf")}catch{setError("Billing document could not be previewed.")}};
  if(!data)return <div className="p-12 text-center text-slate-500">{error||"Loading plans..."}</div>; const current=data.current?.plan; const roleName=user?.role==="PAINTER"?"Paint Applicator":"Contractor";
  return <div className="space-y-6"><header><p className="text-sm font-semibold text-amber-600">{roleName} services</p><h1 className="mt-1 text-3xl font-bold">Subscription</h1><p className="mt-2 text-slate-500">Choose, pay, activate, and renew the subscription that suits your work.</p></header>
    {message&&<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</p>}{error&&<p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <section className="rounded-2xl bg-slate-900 p-6 text-white"><p className="text-sm text-slate-300">Current plan</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">{current?.name||"No active plan"}</h2>{data.current.subscription&&<p className="mt-2 text-sm text-slate-300">Valid {data.current.subscription.start_date} to {data.current.subscription.end_date||"ongoing"}</p>}</div><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-sm font-bold text-emerald-300">Active</span></div>{data.current.usage?.quotations&&<p className="mt-3 text-sm text-slate-300">{data.current.usage.quotations.used} quotations used · {data.current.usage.employees.used} employees registered</p>}</section>
    {data.current.notifications?.length>0&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold">Billing notifications</h2>{data.current.notifications.map(n=><p key={n.id} className="mt-2 text-sm"><b>{n.title}:</b> {n.message}</p>)}</section>}
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.plans.map(plan=>{const active=current?.id===plan.id;const pending=data.requests.some(r=>r.plan_id===plan.id&&["PENDING","AWAITING_PAYMENT","PAYMENT_SUBMITTED"].includes(r.status));const payable=Number(plan.discounted_price??plan.price);return <article key={plan.id} className={`rounded-2xl border bg-white p-6 ${active?"border-emerald-400 ring-2 ring-emerald-100":""}`}><div className="flex justify-between"><div><h2 className="text-xl font-bold">{plan.name}</h2><p className="text-sm text-slate-500">Monthly package</p></div>{active&&<PackageCheck className="text-emerald-600"/>}</div><p className="mt-5 text-3xl font-bold">{payable===0?"Free":`₹${payable.toLocaleString("en-IN")}`}<span className="text-sm font-normal text-slate-500"> / month</span></p>{Number(plan.discount_percentage)>0&&<p className="mt-1 text-sm text-emerald-700"><span className="mr-2 text-slate-400 line-through">₹{Number(plan.price).toLocaleString("en-IN")}</span>{Number(plan.discount_percentage)}% discount</p>}<div className="mt-5 space-y-2 text-sm text-slate-600">{plan.quotation_limit!=null&&<Benefit text={`${plan.quotation_limit} quotations`}/>} {plan.employee_limit!=null&&<Benefit text={`${plan.employee_limit} employees`}/>} {plan.audience==="CONTRACTOR"&&<Benefit text={plan.measurement_access?"Area Calculator included":"Area Calculator not included"}/>} {plan.features.map(x=><Benefit key={x} text={x}/>)}</div><button disabled={pending} onClick={()=>{setSelected(plan);setMonths(1)}} className="mt-6 w-full rounded-xl bg-slate-900 px-4 py-3 font-bold text-white disabled:bg-slate-200 disabled:text-slate-500">{pending?"Action pending":active?"Renew plan":payable===0?"Activate plan":"Choose plan"}</button></article>})}</div>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Billing history</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y bg-slate-50"><tr><th className="p-3">Invoice</th><th className="p-3">Plan and period</th><th className="p-3">Amount</th><th className="p-3">Payment</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody className="divide-y">{data.requests.map(r=><tr key={r.id}><td className="p-3">{r.invoice_number||"—"}</td><td className="p-3"><b>{r.plan_name}</b><small className="block text-slate-500">{r.start_date||"—"} to {r.end_date||"ongoing"}</small></td><td className="p-3">₹{Number(r.amount||0).toLocaleString("en-IN")}</td><td className="p-3">{r.payment_status}</td><td className="p-3">{r.status}</td><td className="p-3"><div className="flex gap-2">{r.payment_status==="AWAITING"&&<button onClick={()=>setPayment({...r,payment_mode:"UPI",payment_reference:"",payment_note:""})} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold">Submit payment</button>}{r.invoice_number&&<button onClick={()=>document(r.id)} className="rounded-lg border p-2" title="Download invoice or receipt"><Download className="h-4 w-4"/></button>}</div></td></tr>)}</tbody></table></div></section>
    {selected&&<Modal title={`${current?.id===selected.id?"Renew":"Choose"} ${selected.name}`} close={()=>setSelected(null)}><form onSubmit={register} className="space-y-4"><Field label="Subscription period"><select value={months} onChange={e=>setMonths(Number(e.target.value))}>{Array.from({length:12},(_,index)=>index+1).map(value=><option key={value} value={value}>{value} {value===1?"month":"months"}</option>)}</select></Field><p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Your subscription starts when the package is activated. The valid-until date is calculated automatically.</p><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-slate-500">Total amount</p><p className="mt-1 text-2xl font-bold">₹{(Number(selected.discounted_price??selected.price)*months).toLocaleString("en-IN")}</p><p className="mt-1 text-xs text-slate-500">₹{Number(selected.discounted_price??selected.price).toLocaleString("en-IN")} × {months} {months===1?"month":"months"}{Number(selected.discount_percentage)>0?` · ${Number(selected.discount_percentage)}% discount applied`:""}</p></div><button className="w-full rounded-xl bg-slate-900 py-3 font-bold text-white">Continue</button></form></Modal>}
    {payment&&<Modal title="Submit payment details" close={()=>setPayment(null)}><form onSubmit={submitPayment} className="space-y-4"><p className="rounded-xl bg-amber-50 p-4">Invoice {payment.invoice_number}<br/><b>Amount: ₹{Number(payment.amount).toLocaleString("en-IN")}</b></p><Field label="Payment mode"><select value={payment.payment_mode} onChange={e=>setPayment({...payment,payment_mode:e.target.value})}><option value="UPI">UPI</option><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="OTHER">Other</option></select></Field><Field label="Transaction/reference number"><input required={payment.payment_mode!=="CASH"} value={payment.payment_reference} onChange={e=>setPayment({...payment,payment_reference:e.target.value})}/></Field><Field label="Note"><textarea rows="3" value={payment.payment_note} onChange={e=>setPayment({...payment,payment_note:e.target.value})}/></Field><button className="w-full rounded-xl bg-slate-900 py-3 font-bold text-white">Send for confirmation</button></form></Modal>}
  </div>;
}
function Benefit({text}){return <p className="flex gap-2"><Check className="h-4 w-4 text-emerald-600"/>{text}</p>}
function Field({label,children}){return <label className="block"><span className="mb-2 block font-semibold">{label}</span>{children}</label>}
function Modal({title,close,children}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
