import { useCallback,useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { CalendarCheck,Plus,Users } from "lucide-react";
import api from "../api/client";
import useAuth from "../context/useAuth";

const today=new Date().toLocaleDateString("en-CA"), currentMonth=today.slice(0,7);
const errorText=(e,f)=>e.response?.data?.detail||Object.values(e.response?.data||{}).flat().join(" ")||f;
export default function InHouseApplicators(){const {user}=useAuth();return user.role==="PAINTER"?<SelfAttendance/>:<Directory/>}

function Directory(){const [items,setItems]=useState([]),[error,setError]=useState("");useEffect(()=>{api.get("/jobs/in-house-applicators/").then(r=>setItems(r.data)).catch(e=>setError(errorText(e,"Employees could not be loaded.")));},[]);return <div className="space-y-6"><Header action={<Link to="/in-house-applicators/new" className="flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 font-semibold text-white"><Plus className="h-4 w-4"/>Create employee</Link>}/>{error&&<Error text={error}/>}<section className="overflow-hidden rounded-2xl border bg-white">{items.length?<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Employee ID</th><th className="px-5 py-3">Mobile</th><th className="px-5 py-3">Joining date</th><th className="px-5 py-3">Salary type</th><th className="px-5 py-3" data-no-sort="true">Action</th></tr></thead><tbody className="divide-y">{items.map(item=><tr key={item.membership_id} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold">{item.name}</td><td className="px-5 py-4 text-slate-600">{item.employee_code||"ID pending"}</td><td className="px-5 py-4">{item.mobile||"—"}</td><td className="px-5 py-4" data-sort-value={item.joined_on||""}>{item.joined_on||"—"}</td><td className="px-5 py-4">{item.salary_basis||"—"}</td><td className="px-5 py-4"><Link to={`/in-house-applicators/${item.membership_id}`} className="inline-flex rounded-lg border px-3 py-2 font-semibold">View</Link></td></tr>)}</tbody></table></div>:<div className="p-14 text-center text-slate-400"><Users className="mx-auto h-10 w-10"/><p className="mt-3">Create your first employee.</p></div>}</section></div>}

function SelfAttendance(){const [data,setData]=useState(null),[month,setMonth]=useState(currentMonth),[site,setSite]=useState(""),[error,setError]=useState("");const load=useCallback(async()=>{try{setData((await api.get(`/jobs/my-in-house-employment/?month=${month}`)).data);setError("");}catch(e){setError(errorText(e,"Employment record could not be loaded."));}},[month]);useEffect(()=>{load();},[load]);async function present(){try{await api.post(`/jobs/in-house-applicators/${data.membership_id}/attendance/`,{date:today,status:"PRESENT",schedule:site});await load();}catch(e){setError(errorText(e,"Attendance could not be marked."));}}return <div className="space-y-6"><Header/>{error&&<Error text={error}/>} {data&&<><section className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-500">{data.employee_code}</p><h2 className="text-2xl font-bold">{data.name}</h2></div><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-xl border px-4 py-3"/></div><Summary data={data.attendance_summary}/></section><section className="rounded-2xl border bg-white p-6"><h2 className="flex items-center gap-2 font-bold"><CalendarCheck className="h-5 w-5"/>Today’s site check-in</h2><p className="mt-1 text-sm text-slate-500">After reaching the site, select it and mark yourself Present.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select value={site} onChange={e=>setSite(e.target.value)} className="flex-1 rounded-xl border px-4 py-3"><option value="">Select assigned site</option>{data.assignments.map(x=><option key={x.id} value={x.schedule}>{x.quotation_number} · {x.property_name}</option>)}</select><button disabled={!site} onClick={present} className="rounded-xl bg-emerald-600 px-6 py-3 font-semibold text-white disabled:opacity-40">Mark Present</button></div></section><Attendance rows={data.attendance} month={month}/></>}</div>}
export function Summary({data={}}){return <div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-5">{[["Present",data.present,"emerald"],["Half-day",data.half_day,"amber"],["Absent",data.absent,"red"],["Leave",data.leave,"blue"],["Overtime",`${data.overtime_hours||0} hrs`,"violet"]].map(([a,b,c])=><div key={a} className={`rounded-xl bg-${c}-50 p-4`}><p className="text-xs text-slate-500">{a}</p><p className="mt-1 text-2xl font-bold">{b||0}</p></div>)}</div>}
export function Attendance({rows=[],month=currentMonth,onSelect}){const [year,number]=month.split("-").map(Number);const first=new Date(year,number-1,1),offset=(first.getDay()+6)%7,days=new Date(year,number,0).getDate();const cells=Array.from({length:42},(_,i)=>{const day=i-offset+1;return day>0&&day<=days?day:null});const records=new Map(rows.map(row=>[Number(row.date.slice(8,10)),row]));const styles={PRESENT:"bg-emerald-100 text-emerald-800",HALF_DAY:"bg-amber-100 text-amber-800",ABSENT:"bg-red-100 text-red-700",LEAVE:"bg-blue-100 text-blue-700"};return <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Attendance calendar</h2><p className="text-sm text-slate-500">{first.toLocaleDateString("en-GB",{month:"long",year:"numeric"})}</p></div><div className="flex flex-wrap gap-3 text-xs"><Key color="bg-emerald-500" text="Present"/><Key color="bg-amber-500" text="Half-day"/><Key color="bg-red-500" text="Absent"/><Key color="bg-blue-500" text="Leave"/></div></div><div className="mx-auto mt-5 max-w-xl"><div className="grid grid-cols-7 text-center text-xs font-bold text-slate-500">{["Mo","Tu","We","Th","Fr","Sa","Su"].map(x=><span key={x} className="py-2">{x}</span>)}</div><div className="grid grid-cols-7 gap-2">{cells.map((day,index)=>{const row=records.get(day);return day?<button type="button" key={day} onClick={()=>onSelect?.(row||{date:`${month}-${String(day).padStart(2,"0")}`,status:"PRESENT",overtime_hours:0,note:""})} className={`relative mx-auto grid h-11 w-11 place-items-center rounded-full text-sm font-semibold ${row?styles[row.status]:"text-slate-500 hover:bg-slate-100"}`} title={row?`${row.status}${Number(row.overtime_hours)>0?` · ${row.overtime_hours} overtime hours`:""}`:"No attendance"}>{day}{Number(row?.overtime_hours)>0&&<i className="absolute -right-1 -top-1 grid h-4 min-w-4 place-items-center rounded-full bg-violet-600 px-1 text-[9px] not-italic text-white">OT</i>}</button>:<span key={`empty-${index}`} className="h-11"/>})}</div></div></section>}
function Key({color,text}){return <span className="flex items-center gap-1.5"><i className={`h-2.5 w-2.5 rounded-full ${color}`}/>{text}</span>}
function Header({action}){return <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-amber-600">Permanent workforce</p><h1 className="mt-1 text-3xl font-bold">In-house Employees</h1><p className="mt-2 text-slate-500">Employee profiles and attendance, kept separate from marketplace applicators.</p></div>{action}</header>}
function Error({text}){return <p className="rounded-xl bg-red-50 p-4 text-red-700">{text}</p>}
