import QuotationDiscountControls from "../components/QuotationDiscountControls.jsx";
import { quotationTotals } from "../utils/quotationPricing.js";
import {useEffect,useMemo,useRef,useState} from "react";
import {Link,useLocation,useNavigate,useSearchParams} from "react-router-dom";
import {ArrowLeft,Plus,Search,Trash2} from "lucide-react";
import api from "../api/client";
import {goBackFromBuilder} from "../utils/navigation";
const fresh=()=>({measurement_id:"",room_name:"",category:"Painting",service_name:"Painting",line_type:"SERVICE_MATERIAL",product_type:"",description:"",brand:"",unit_name:"Sq ft",quantity:1,rate:"",promote_to_master:false});
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v||0));
const initial={customer:"",property:"",valid_until:"",discount_mode:"OVERALL",discount_type:"FIXED",discount_value:0,gst_mode:"GST_EXTRA",gst_percentage:18,notes:"",terms_conditions:"",prepared_by:"",inspected_by:"",payment_terms:"",product_details:"",work_duration:"",work_procedures:""};
export default function ManualQuotationBuilder(){
 const nav=useNavigate(),loc=useLocation(),[params]=useSearchParams();
 const restored=useRef(false),exteriorLoaded=useRef(""),draftKey="bharath-quotation-draft";
 const [m,setM]=useState({customers:[],properties:[],rooms:[],categories:[],services:[],descriptions:[],products:[],brands:[],units:[]}),[propertyRooms,setPropertyRooms]=useState([]),[measurements,setMeasurements]=useState([]),[measurementSource,setMeasurementSource]=useState(""),[form,setForm]=useState(initial),[lines,setLines]=useState([fresh()]),[mobileIndex,setMobileIndex]=useState(null),[search,setSearch]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false),[draftNotice,setDraftNotice]=useState(false);
 useEffect(()=>{if(restored.current)return;restored.current=true;try{const saved=JSON.parse(localStorage.getItem(draftKey));if(saved?.form&&saved?.lines?.length){setForm(saved.form);setLines(saved.lines);setSearch(saved.search||"");setDraftNotice(true)}}catch{/* ignore invalid local draft */}},[]);
 useEffect(()=>{if(!restored.current)return;const timer=window.setTimeout(()=>localStorage.setItem(draftKey,JSON.stringify({form,lines,search,saved_at:new Date().toISOString()})),500);return()=>window.clearTimeout(timer)},[form,lines,search]);
 useEffect(()=>{Promise.all(["customers","properties","areas","service-categories","service-types","work-descriptions","paint-types","brands","units"].map(x=>api.get(`/quotations/${x}/`))).then(rs=>{const list=r=>r.data.results||r.data,[customers,properties,rooms,categories,services,descriptions,products,brands,units]=rs.map(list);setM({customers,properties,rooms,categories:uniqueNames(categories),services,descriptions,products,brands,units:uniqueNames(units)});const c=customers.find(x=>String(x.id)===params.get("customer"));if(c){setForm(f=>({...f,customer:c.id}));setSearch(`${c.bharath_id} · ${c.name} · ${c.mobile}`)}}).catch(()=>setError("Quotation master data could not be loaded."))},[params]);
 useEffect(()=>{const requested=params.get("property");if(requested&&m.properties.some(x=>String(x.id)===requested)){setForm(f=>String(f.property)===requested?f:{...f,property:requested});exteriorLoaded.current=""}},[m.properties,params]);
 useEffect(()=>{setMeasurementSource("");if(!form.property){setPropertyRooms([]);setMeasurements([]);return}Promise.all([api.get(`/quotations/properties/${form.property}/rooms/`),api.get(`/quotations/properties/${form.property}/measurements/`)]).then(([r,s])=>{setPropertyRooms(r.data.results||r.data);setMeasurements(s.data.results||s.data)}).catch(()=>setError("Saved property Area Calculations could not be loaded."))},[form.property]);
 const update=(k,v)=>setForm(f=>({...f,[k]:v})),lineUpdate=(i,k,v)=>setLines(ls=>ls.map((x,n)=>{if(n!==i)return x;const product=k==="product_type"?m.products.find(item=>String(item.name||"").toLowerCase()===String(v||"").toLowerCase()):null;return{...x,[k]:v,...(k==="category"?{service_name:"",product_type:"",description:"",measurement_id:"",room_name:isExteriorPainting(v)?"Exterior":x.room_name}:{}),...(k==="room_name"?{measurement_id:"",quantity:1}:{}),...(product?.default_price!==null&&product?.default_price!==undefined?{rate:String(product.default_price)}:{})}}));
 const matches=useMemo(()=>{const q=search.toLowerCase().trim();return m.customers.filter(x=>!q||[x.name,x.mobile,x.bharath_id].some(v=>String(v||"").toLowerCase().includes(q))).slice(0,12)},[m.customers,search]);
 const properties=m.properties.filter(x=>String(x.customer)===String(form.customer)),hasInterior=measurements.some(item=>item.work_area==="INTERIOR"),hasExterior=measurements.some(item=>item.work_area==="EXTERIOR"),exteriorMode=measurementSource==="EXTERIOR";
 const totals=quotationTotals(lines,form),{subtotal,discount,gst}=totals,grand=totals.total;
 const measurementOptions=useMemo(()=>buildMeasurements(propertyRooms,measurements,m.services),[propertyRooms,measurements,m.services]);
 const selectedProductDetails=useMemo(()=>uniqueProductDetails(lines,m.products,m.brands),[lines,m.products,m.brands]);
 function chooseMeasurementSource(value){
  setMeasurementSource(value);setDraftNotice(false);localStorage.removeItem(draftKey);
  if(value==="MANUAL"){setLines([fresh()]);return}
  const wanted=measurementOptions.filter(option=>value==="BOTH"||(value==="EXTERIOR"?String(option.id).startsWith("exterior"):!String(option.id).startsWith("exterior")));
  setLines(wanted.length?wanted.map(option=>({...fresh(),...option,measurement_id:option.id,category:String(option.id).startsWith("exterior")?"Exterior Painting":"Interior Painting",room_name:String(option.id).startsWith("exterior")?"Exterior":option.room_name,unit_name:"Sq ft"})):[fresh()]);
 }
 const applyMeasurement=(index,id)=>{const option=measurementOptions.find(x=>x.id===id);setLines(ls=>ls.map((line,n)=>n===index?(option?{...line,...option,measurement_id:id,category:line.category,unit_name:"Sq ft"}:{...line,measurement_id:"",quantity:1}):line))};
 const roomOptions=useMemo(()=>uniqueNames([...propertyRooms,...m.rooms]),[propertyRooms,m.rooms]);
 const addLine=()=>{setLines(ls=>[...ls,{...fresh(),room_name:exteriorMode?"Exterior":"",category:exteriorMode?"Exterior Painting":"Painting"}]);setMobileIndex(lines.length)};
 async function submit(e){
  e.preventDefault();
  if(!form.customer||!form.property)return setError("Select customer and property.");
  if(lines.some(x=>!x.room_name.trim()||!x.category.trim()||!x.service_name.trim()||!x.description.trim()||!x.unit_name.trim()||Number(x.quantity)<=0||Number(x.rate)<0))return setError("Complete room, service, description, MOU, quantity and rate for every line.");
  setSaving(true);setError("");
  try{
   const rooms=[...new Set(lines.map(x=>x.room_name.trim()))];
   const exact=(list,name)=>list.find(x=>x.name.toLowerCase()===name.trim().toLowerCase());
   const items=lines.map(x=>{
    const c=exact(m.categories,x.category);
    const s=m.services.find(v=>v.name.toLowerCase()===x.service_name.trim().toLowerCase()&&(!c||categoryFamily(v.category||"")===categoryFamily(c.name)||String(v.category_master)===String(c.id)));
    const p=exact(m.products,x.product_type),b=exact(m.brands,x.brand),u=exact(m.units,x.unit_name);
    return{room_index:rooms.indexOf(x.room_name.trim()),service_category:c?.id||null,custom_service_category:c?"":x.category.trim(),service_type:s?.id||null,custom_service_type:s?"":x.service_name.trim(),line_type:x.line_type,paint_type:p?.id||null,custom_product_type:p?"":x.product_type.trim(),description:x.description.trim(),paint_brand:b?.id||null,custom_brand:b?"":x.brand.trim(),unit:u?.id||null,custom_unit:u?"":x.unit_name.trim(),promote_to_master:x.promote_to_master,calculation_method:"MANUAL",is_additional_service:!usesPaintingMeasurement(x.category),coats:1,discount_type:x.discount_type || "FIXED",discount_value:Number(x.discount_value)||0,quantity:Number(x.quantity),rate:Number(x.rate)||0};
   });
   const lead=params.get("lead");
   const payload={...form,lead:lead?Number(lead):null,quotation_type:"MANUAL_LUMPSUM",customer:Number(form.customer),property:Number(form.property),valid_until:form.valid_until||null,discount_value:Number(form.discount_value)||0,gst_percentage:Number(form.gst_percentage)||0,rooms:rooms.map(name=>({name})),items};
   const{data}=await api.post("/quotations/create/",payload);localStorage.removeItem(draftKey);nav(`/quotations/${data.id}`);
  }catch(e){setError(Object.entries(e.response?.data||{}).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(" "):JSON.stringify(v)}`).join(" ")||"Quotation could not be created.")}finally{setSaving(false)}
 }
 return <form onSubmit={submit} className={`space-y-6 ${exteriorMode?"exterior-quotation":""}`}><style>{`.exterior-quotation table th:nth-child(3),.exterior-quotation table td:nth-child(3){display:none}.exterior-quotation .fixed .space-y-4>label:first-child{display:none}`}</style><button type="button" onClick={()=>goBackFromBuilder(loc,nav,"/quotations")} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft className="h-4 w-4"/>Back to quotations</button><header><p className="text-sm font-semibold text-amber-600">Quick quotation</p><h1 className="mt-1 text-3xl font-bold">Create detailed quotation</h1><p className="mt-2 text-slate-500">{exteriorMode?"Exterior quotation uses the selected property's saved Area Calculation. Rooms are not required.":"Select a master value or type a new value directly. Your draft is saved automatically."}</p></header>{draftNotice&&<div className="flex items-center justify-between rounded-xl bg-blue-50 p-4 text-sm text-blue-800"><span>A saved quotation draft was recovered.</span><button type="button" onClick={()=>{localStorage.removeItem(draftKey);setForm(initial);setLines([fresh()]);setSearch("");setDraftNotice(false)}} className="font-bold">Discard draft</button></div>}{error&&<p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
 <section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">1. Customer, property and Area Calculation source</h2><div className="mt-4 grid gap-4 lg:grid-cols-4"><label className="relative text-sm font-semibold">Customer *<span className="mt-2 flex items-center gap-2 rounded-xl border px-3 py-3"><Search className="h-4 w-4"/><input value={search} onChange={e=>{setSearch(e.target.value);update("customer","");update("property","")}} className="w-full outline-none" placeholder="Search customer"/></span>{!form.customer&&<span className="absolute z-20 mt-1 max-h-60 w-full overflow-auto rounded-xl border bg-white p-1 shadow-xl">{matches.map(x=><button key={x.id} type="button" onClick={()=>{update("customer",x.id);setSearch(`${x.bharath_id} · ${x.name} · ${x.mobile}`)}} className="block w-full rounded-lg p-3 text-left hover:bg-slate-50"><b>{x.name}</b><small className="block">{x.bharath_id} · {x.mobile}</small></button>)}</span>}</label><Field label="Property *"><select required value={form.property} onChange={e=>update("property",e.target.value)}><option value="">Select property</option>{properties.map(x=><option key={x.id} value={x.id}>{x.name||x.property_type} · {x.city}</option>)}</select></Field><Field label="Use Area Calculation *"><select required disabled={!form.property} value={measurementSource} onChange={e=>chooseMeasurementSource(e.target.value)}><option value="">Choose source</option>{hasInterior&&<option value="INTERIOR">Interior Area Calculation</option>}{hasExterior&&<option value="EXTERIOR">Exterior Area Calculation</option>}{hasInterior&&hasExterior&&<option value="BOTH">Interior + Exterior Area Calculations</option>}<option value="MANUAL">Create manually without Area Calculation</option></select></Field><Field label="Valid until"><input type="date" value={form.valid_until} onChange={e=>update("valid_until",e.target.value)}/></Field></div>{form.property&&!measurements.length&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">No saved Area Calculations were found. Choose manual quotation.</p>}</section>
 <section className="rounded-2xl border bg-white p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">2. Quotation line items</h2></div><div className="flex flex-wrap gap-2"><Link to="/master-services" className="rounded-lg border px-2.5 py-2 text-xs font-semibold sm:rounded-xl sm:px-4 sm:py-2.5 sm:text-sm"><span className="sm:hidden">Master</span><span className="hidden sm:inline">Manage master data</span></Link><button type="button" onClick={addLine} className="flex items-center gap-1 rounded-lg bg-slate-950 px-2.5 py-2 text-xs font-semibold text-white sm:gap-2 sm:rounded-xl sm:px-4 sm:py-2.5 sm:text-sm"><Plus className="h-3.5 w-3.5 sm:h-4 sm:w-4"/><span className="sm:hidden">Add</span><span className="hidden sm:inline">Add line</span></button></div></div>
 <div className="mt-5 space-y-3 md:hidden">{lines.map((item,index)=><button type="button" key={index} onClick={()=>setMobileIndex(index)} className="w-full rounded-xl border p-4 text-left"><div className="flex justify-between"><b>Line {index+1}: {item.room_name||"Select room"}</b><span className="font-bold">{money(Number(item.quantity||0)*Number(item.rate||0))}</span></div><p className="mt-2 text-sm text-slate-500">{item.category||"Type of service"} · {item.product_type||"Product pending"}</p><p className="mt-1 text-xs font-semibold text-amber-700">Tap to complete or edit</p></button>)}</div>
 <div className="mt-5 hidden overflow-x-auto rounded-xl border md:block"><table className="w-full min-w-[2050px] text-sm"><thead className="bg-slate-100 text-left text-xs uppercase text-slate-500"><tr>{["Sl.","Type of service","Room / Area","Area Calculation","Service type","Product type","Product description","Brand","MOU","Quantity","Rate","Total price","Add to master",""] .map((h,i)=><th key={`${h}-${i}`} className="p-3">{h}</th>)}</tr></thead><tbody>{lines.map((x,i)=><Line key={i} x={x} i={i} m={m} roomOptions={roomOptions} measurementOptions={measurementOptions} applyMeasurement={applyMeasurement} update={lineUpdate} remove={()=>setLines(ls=>ls.filter((_,n)=>n!==i))} removable={lines.length>1}/>)}</tbody></table></div>
 {mobileIndex!==null&&lines[mobileIndex]&&<MobileLine item={lines[mobileIndex]} index={mobileIndex} m={m} roomOptions={roomOptions} measurementOptions={measurementOptions} applyMeasurement={applyMeasurement} update={lineUpdate} remove={()=>{setLines(ls=>ls.filter((_,n)=>n!==mobileIndex));setMobileIndex(null)}} close={()=>setMobileIndex(null)} removable={lines.length>1}/>}</section>
 <section className="grid gap-6 rounded-2xl border bg-white p-6 lg:grid-cols-2"><div className="grid gap-4 sm:grid-cols-2"><QuotationDiscountControls form={form} onChange={update} items={lines} onLineChange={(item,field,value)=>lineUpdate(lines.indexOf(item),field,value)} />{[["Prepared by","prepared_by"],["Inspected by","inspected_by"],["Work duration","work_duration"]].map(([l,k])=><Field key={k} label={l}><input value={form[k]} onChange={e=>update(k,e.target.value)}/></Field>)}{[["Notes","notes"],["Payment terms","payment_terms"],["Product details","product_details"],["Work procedures and safety","work_procedures"],["Terms and conditions","terms_conditions"]].map(([l,k])=><Field key={k} label={l} wide><textarea rows="3" value={form[k]} onChange={e=>update(k,e.target.value)}/></Field>)}<div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm sm:col-span-2"><b>Selected product details</b>{selectedProductDetails?<p className="mt-2 whitespace-pre-wrap leading-6 text-slate-600">{selectedProductDetails}</p>:null}</div></div><div className="h-fit rounded-xl bg-slate-950 p-6 text-white"><h2 className="font-bold">Quotation total</h2><div className="mt-5 space-y-3"><Row label="Subtotal" value={money(subtotal)}/><Row label="Discount" value={`- ${money(discount)}`}/><Row label="GST" value={money(gst)}/><div className="border-t border-white/20 pt-4"><Row label="Grand total" value={money(grand)} large/></div></div><button disabled={saving} className="mt-6 w-full rounded-xl bg-white py-3 font-bold text-slate-950 disabled:opacity-50">{saving?"Creating quotation...":"Create quotation"}</button></div></section></form>}
function Line({x,i,m,roomOptions,measurementOptions,applyMeasurement,update,remove,removable}){
 const services=servicesFor(m.services,m.categories,x.category),measured=usesPaintingMeasurement(x.category),choices=measurementChoices(x.category,measurementOptions,x.room_name),products=byService(m.products,m.categories,x.category),descriptions=byService(m.descriptions,m.categories,x.category),exterior=isExteriorPainting(x.category);
 return <tr className="border-t align-top"><td className="p-3 font-bold">{i+1}</td>
  <Cell><Suggest value={x.category} set={v=>update(i,"category",v)} options={uniqueNames(m.categories)} placeholder="Search type of service"/></Cell>
  <Cell>{exterior?<span className="block rounded-lg bg-slate-100 px-3 py-2 font-semibold">Exterior</span>:<Suggest value={x.room_name} set={v=>update(i,"room_name",v)} options={roomOptions} placeholder="Room / Area"/>}</Cell>
  <Cell>{measured?<select value={x.measurement_id} onChange={e=>applyMeasurement(i,e.target.value)}><option value="">Manual area / quantity</option>{choices.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select>:<span className="text-xs text-slate-400">Use MOU and quantity</span>}</Cell>
  <Cell><select value={x.line_type} onChange={e=>update(i,"line_type",e.target.value)}><option value="SERVICE_MATERIAL">Service + Material</option><option value="SERVICE">Service only</option><option value="MATERIAL">Material only</option><option value="REPAIR">Repair</option></select><Suggest value={x.service_name} set={v=>update(i,"service_name",v)} options={services} placeholder="Service"/></Cell>
  <Cell><Suggest value={x.product_type} set={v=>update(i,"product_type",v)} options={products} placeholder="Product type"/></Cell><Cell><Suggest value={x.description} set={v=>update(i,"description",v)} options={descriptions} placeholder="Description"/></Cell><Cell><Suggest value={x.brand} set={v=>update(i,"brand",v)} options={m.brands} placeholder="Brand"/></Cell>
  <Cell><select required value={x.unit_name} onChange={e=>update(i,"unit_name",e.target.value)}><option value="">Select MOU</option>{m.units.map(v=><option key={v.id} value={v.name}>{v.name}</option>)}</select></Cell><Cell><input type="number" min="0.01" step="0.01" value={x.quantity} readOnly={Boolean(x.measurement_id)} onChange={e=>update(i,"quantity",e.target.value)}/></Cell><Cell><input type="number" min="0" step="0.01" value={x.rate} onChange={e=>update(i,"rate",e.target.value)}/></Cell><td className="p-3 text-right font-bold">{money(Number(x.quantity||0)*Number(x.rate||0))}</td><td className="p-3 text-center"><input type="checkbox" checked={x.promote_to_master} onChange={e=>update(i,"promote_to_master",e.target.checked)}/></td><td className="p-3"><button type="button" disabled={!removable} onClick={remove} className="rounded-lg border p-2 text-red-600 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></td></tr>
}
function MobileLine({item,index,m,roomOptions,measurementOptions,applyMeasurement,update,remove,close,removable}){
 const measured=usesPaintingMeasurement(item.category),choices=measurementChoices(item.category,measurementOptions,item.room_name),exterior=isExteriorPainting(item.category),services=servicesFor(m.services,m.categories,item.category),products=byService(m.products,m.categories,item.category),descriptions=byService(m.descriptions,m.categories,item.category),input="mt-1.5 w-full rounded-xl border px-3 py-3";
 return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/50 sm:items-center sm:justify-center"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 sm:max-w-lg sm:rounded-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-amber-600">Quotation line {index+1}</p><h3 className="text-xl font-bold">Service details</h3></div><button type="button" onClick={close} className="rounded-lg border px-3 py-2">Close</button></div><div className="mt-5 space-y-4">
  <MobileSuggest label="Type of service" value={item.category} set={v=>update(index,"category",v)} options={uniqueNames(m.categories)}/>
  {!exterior&&<label className="block text-sm font-semibold">Room / Area<Suggest value={item.room_name} set={v=>update(index,"room_name",v)} options={roomOptions} placeholder="Room / Area"/></label>}
  {measured&&<label className="block text-sm font-semibold">Area Calculation<select className={input} value={item.measurement_id} onChange={e=>applyMeasurement(index,e.target.value)}><option value="">Manual area / quantity</option>{choices.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label>}
  <label className="block text-sm font-semibold">Service type<select className={input} value={item.line_type} onChange={e=>update(index,"line_type",e.target.value)}><option value="SERVICE_MATERIAL">Service + Material</option><option value="SERVICE">Service only</option><option value="MATERIAL">Material only</option><option value="REPAIR">Repair</option></select></label>
  <MobileSuggest label="Service" value={item.service_name} set={v=>update(index,"service_name",v)} options={services}/><MobileSuggest label="Product type" value={item.product_type} set={v=>update(index,"product_type",v)} options={products}/><MobileSuggest label="Product description" value={item.description} set={v=>update(index,"description",v)} options={descriptions}/><MobileSuggest label="Brand" value={item.brand} set={v=>update(index,"brand",v)} options={m.brands}/><label className="block text-sm font-semibold">MOU<select className={input} value={item.unit_name} onChange={e=>update(index,"unit_name",e.target.value)}>{m.units.map(v=><option key={v.id}>{v.name}</option>)}</select></label><label className="block text-sm font-semibold">Quantity<input className={input} type="number" min="0.01" step="0.01" readOnly={Boolean(item.measurement_id)} value={item.quantity} onChange={e=>update(index,"quantity",e.target.value)}/></label><label className="block text-sm font-semibold">Rate<input className={input} type="number" min="0" step="0.01" value={item.rate} onChange={e=>update(index,"rate",e.target.value)}/></label><div className="rounded-xl bg-slate-950 p-4 text-white"><span className="text-sm">Total price</span><b className="float-right">{money(Number(item.quantity||0)*Number(item.rate||0))}</b></div><label className="flex items-center gap-3 rounded-xl border p-4 text-sm font-semibold"><input type="checkbox" checked={item.promote_to_master} onChange={e=>update(index,"promote_to_master",e.target.checked)}/>Add new values to Master Data</label></div><div className="mt-5 grid grid-cols-2 gap-3">{removable?<button type="button" onClick={remove} className="rounded-xl border border-red-200 py-3 font-semibold text-red-600">Delete line</button>:<span/>}<button type="button" onClick={close} className="rounded-xl bg-slate-950 py-3 font-semibold text-white">Save line</button></div></div></div>
}
function MobileSuggest({label,value,set,options}){const id=`mobile-${label.replace(/\W/g,"")}`;return <label className="block text-sm font-semibold">{label}<input className="mt-1.5 w-full rounded-xl border px-3 py-3" list={id} value={value} onChange={e=>set(e.target.value)}/><datalist id={id}>{options.map(v=><option key={v.id} value={v.name}/>)}</datalist></label>}
function uniqueProductDetails(lines,products,brands){const seen=new Set();return lines.reduce((result,line)=>{const product=products.find(item=>String(item.name||"").toLowerCase()===String(line.product_type||"").toLowerCase());if(!product?.name||!String(product.key_features||"").trim())return result;const brand=brands.find(item=>String(item.name||"").toLowerCase()===String(line.brand||"").toLowerCase());const key=`${product.name}|${brand?.name||""}|${product.key_features}`.toLowerCase();if(seen.has(key))return result;seen.add(key);result.push(`${product.name}${brand?.name?` (${brand.name})`:""}: ${product.key_features}`);return result},[]).join("\n")}
function buildMeasurements(rooms,surfaces,services){const options=[];const add=(id,room,kind,label,quantity,finish="")=>{if(quantity<=0)return;const service=services.find(s=>s.calculation_type===kind);options.push({id,label:`${room} - ${label} (${quantity.toFixed(0)} sq ft)`,room_name:room,service_name:service?.name||`${label} Painting`,description:[label,finish].filter(Boolean).join(" - "),quantity:quantity.toFixed(2)})};rooms.forEach(room=>{const own=surfaces.filter(s=>s.room===room.id),walls=own.filter(s=>s.surface_type==="WALL"),netWall=Math.max(0,walls.reduce((n,s)=>n+Number(s.gross_area||0)-Number(s.deduction_area||0)+Number(s.addition_area||0),0)),ceiling=own.filter(s=>s.surface_type==="CEILING").reduce((n,s)=>n+Number(s.net_area||0),0);add(`${room.id}-WALL`,room.name,"WALL","Net Wall Area",netWall);add(`${room.id}-CEILING`,room.name,"CEILING","Ceiling Area",ceiling);own.filter(s=>["DOOR","WINDOW","WARDROBE"].includes(s.surface_type)).forEach(s=>add(`surface-${s.id}`,room.name,s.surface_type,s.name||s.surface_type,Number(s.net_area||0),s.finish))});const exterior=surfaces.filter(s=>s.work_area==="EXTERIOR");const walls=exterior.filter(s=>s.surface_type==="WALL");const netWalls=walls.reduce((n,s)=>n+Number(s.net_area||0),0);add("exterior-walls","Exterior","WALL","Net exterior wall area",netWalls,"Water-based exterior paint");exterior.filter(s=>s.surface_type!=="WALL").forEach(s=>add(`exterior-${s.id}`,"Exterior",s.surface_type,s.name||s.surface_type,Number(s.net_area||0),s.finish));return options}
function usesPaintingMeasurement(value){const name=String(value||"").toLowerCase();return name.includes("painting")||name.includes("wallpaper")||name.includes("wall paper")||name.includes("texture")}
function isExteriorPainting(value){const name=String(value||"").toLowerCase();return name.includes("exterior")&&name.includes("painting")}
function measurementChoices(category,options,roomName){
 const exterior=isExteriorPainting(category);
 let choices=exterior?options.filter(item=>String(item.id).startsWith("exterior")):options.filter(item=>!String(item.id).startsWith("exterior"));
 const room=String(roomName||"").trim().toLowerCase();
 if(!exterior&&room)choices=choices.filter(item=>String(item.room_name||"").trim().toLowerCase()===room);
 return choices;
}
function uniqueNames(items){const seen=new Set();return items.filter(item=>{const name=String(item.name||"").trim().toLowerCase();if(!name||seen.has(name))return false;seen.add(name);return true})}
function categoryFamily(name){const value=String(name||"").toLowerCase();return value.includes("painting")?"painting":value.includes("wallpaper")||value.includes("wall paper")?"wallpaper":value.includes("texture")?"texture":value}
function relatedCategoryIds(categories,name){const exact=categories.find(value=>value.name.toLowerCase()===String(name||"").toLowerCase()),family=categoryFamily(name);return new Set(categories.filter(value=>value.id===exact?.id||categoryFamily(value.name)===family).map(value=>Number(value.id)))}
function servicesFor(items,categories,name){const ids=relatedCategoryIds(categories,name),family=categoryFamily(name);return items.filter(item=>ids.has(Number(item.category_master))||categoryFamily(item.category)===family)}
function byService(items,categories,name){const ids=relatedCategoryIds(categories,name);return items.filter(item=>ids.has(Number(item.service_category))||(!item.service_category&&categoryFamily(name)==="painting"))}
function Suggest({value,set,options,placeholder}){const id=`${placeholder.replace(/\W/g,"")}-${options.length}`;return <><input className="mt-1.5 w-full rounded-xl border px-3 py-3" list={id} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/><datalist id={id}>{options.map(x=><option key={x.id} value={x.name}/>)}</datalist></>}
function Field({label,wide,children}){return <label className={`text-sm font-semibold ${wide?"sm:col-span-2":""}`}>{label}<span className="mt-2 block [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:px-3 [&>*]:py-3">{children}</span></label>}
function Cell({children}){return <td className="min-w-36 p-2 [&_input]:mb-1 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:px-3 [&_input]:py-2 [&_select]:mb-1 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:px-3 [&_select]:py-2">{children}</td>}
function Row({label,value,large}){return <p className={`flex justify-between ${large?"text-xl":"text-sm"}`}><span>{label}</span><b>{value}</b></p>}
