import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, Ruler, Search, X } from "lucide-react";
import api from "../api/client";
import useAuth from "../context/useAuth";
import { useNavigate } from "react-router-dom";

export default function MeasurementAccess() {
  const { user } = useAuth(); const customerMode = user?.role === "CUSTOMER";
  const navigate = useNavigate();
  const [requests,setRequests]=useState([]),[customers,setCustomers]=useState([]),[customer,setCustomer]=useState(""),[customerSearch,setCustomerSearch]=useState(""),[available,setAvailable]=useState([]),[view,setView]=useState(null),[error,setError]=useState("");
  const [properties,setProperties]=useState([]),[contractorSearch,setContractorSearch]=useState(""),[contractorMatches,setContractorMatches]=useState([]),[selectedContractor,setSelectedContractor]=useState(null),[shareProperty,setShareProperty]=useState("");
  const load=useCallback(async()=>{try{const calls=[api.get("/quotations/measurement-access/"),customerMode?api.get("/quotations/customer-portal/properties/"):api.get("/quotations/customers/")];const[r,c]=await Promise.all(calls);setRequests(r.data);if(customerMode)setProperties((c.data||[]).filter(item=>item.surfaces>0));else setCustomers(c.data.results||c.data);setError("");window.dispatchEvent(new Event("portal-counts-changed"));}catch{setError("Area Calculation sharing details could not be loaded.");}},[customerMode]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{if(!customerMode||contractorSearch.trim().length<3){setContractorMatches([]);return;}const timer=setTimeout(()=>api.get("/quotations/measurement-access/contractors/",{params:{search:contractorSearch}}).then(({data})=>setContractorMatches(data)).catch(()=>setContractorMatches([])),300);return()=>clearTimeout(timer);},[contractorSearch,customerMode]);
  const customerMatches=useMemo(()=>{const term=customerSearch.trim().toLowerCase();if(!term)return customers;return customers.filter(item=>[item.name,item.mobile,item.email,item.city,item.bharath_id].some(value=>String(value||"").toLowerCase().includes(term)));},[customerSearch,customers]);
  const recentCustomers=customerSearch.trim()?[]:customerMatches.slice(0,5);
  async function chooseCustomer(value){setCustomer(value);if(!value)return setAvailable([]);try{const{data}=await api.get("/quotations/measurement-access/availability/",{params:{customer:value}});setAvailable(data);}catch(e){setError(e.response?.data?.detail||"Area Calculations could not be checked.");}}
  function selectCustomer(item){setCustomerSearch(`${item.name} · ${item.mobile}`);chooseCustomer(item.id);}
  async function requestAccess(property){try{const{data}=await api.post("/quotations/measurement-access/",{customer,source_property:property.id,request_message:"Requesting approval to reuse a previous Area Calculation."});setRequests(items=>[data,...items.filter(item=>item.id!==data.id)]);setAvailable(items=>items.filter(item=>item.id!==property.id));}catch(e){setError(e.response?.data?.detail||"Request could not be sent.");}}
  async function shareMeasurement(event){event.preventDefault();if(!selectedContractor||!shareProperty)return;try{const{data}=await api.post("/quotations/measurement-access/",{contractor:selectedContractor.id,source_property:shareProperty,customer_note:"Shared by customer."});setRequests(items=>[data,...items.filter(item=>item.id!==data.id)]);setSelectedContractor(null);setContractorSearch("");setShareProperty("");setError("");}catch(e){setError(e.response?.data?.detail||"Area Calculation could not be shared.");}}
  async function decide(item,status){try{const{data}=await api.patch(`/quotations/measurement-access/${item.id}/`,{status});setRequests(items=>items.map(entry=>entry.id===data.id?data:entry));}catch{setError("Decision could not be saved.");}}
  async function viewMeasurement(item){try{const{data}=await api.get(`/quotations/measurement-access/${item.id}/measurements/`);setView(data);}catch{setError("Approved Area Calculations could not be loaded.");}}
  async function createQuotation(item){try{const{data}=await api.post(`/quotations/measurement-access/${item.id}/prepare-quotation/`);navigate(`/quotations/new?customer=${data.customer}&property=${data.property}`);}catch(e){setError(e.response?.data?.detail||"Quotation could not be prepared from this Area Calculation.");}}
  return <div className="space-y-6">
    <header><p className="text-sm font-semibold text-amber-600">Customer-controlled sharing</p><h1 className="mt-1 text-3xl font-bold">{customerMode ? "Share Area Calculation" : "Area Calculator"}</h1><p className="mt-2 text-slate-500">{customerMode?"Share a property's Area Calculation with a registered verified contractor.":"Request customer permission to reuse a previous Area Calculation."}</p></header>
    {error&&<p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    {customerMode&&<form onSubmit={shareMeasurement} className="rounded-2xl border bg-white p-4 sm:p-5"><h2 className="font-bold">Share Area Calculation</h2><p className="mt-1 text-sm text-slate-500">The contractor receives read-only dimensions for the selected property.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Property with Area Calculation"><select required value={shareProperty} onChange={e=>setShareProperty(e.target.value)}><option value="">Select property</option>{properties.map(item=><option key={item.id} value={item.id}>{item.name} · {item.address||item.city||item.property_type}</option>)}</select></Field><div className="relative"><label className="text-sm font-semibold">Registered contractor<div className="mt-2 flex items-center gap-2 rounded-xl border px-3 py-3"><Search className="h-4 w-4 text-slate-400"/><input value={contractorSearch} onChange={e=>{setContractorSearch(e.target.value);setSelectedContractor(null);}} placeholder="Mobile number or Contractor ID" className="w-full font-normal outline-none"/></div></label>{contractorMatches.length>0&&!selectedContractor&&<div className="absolute z-20 mt-1 w-full overflow-hidden rounded-xl border bg-white shadow-xl">{contractorMatches.map(item=><button type="button" key={item.id} onClick={()=>{setSelectedContractor(item);setContractorSearch(`${item.name} · ${item.bharath_id||item.mobile}`);setContractorMatches([]);}} className="block w-full border-b px-4 py-3 text-left hover:bg-slate-50"><b className="text-sm">{item.name}</b><p className="text-xs text-slate-500">{item.mobile} · {item.bharath_id}</p></button>)}</div>}</div></div><div className="mt-4 flex justify-end"><button disabled={!shareProperty||!selectedContractor} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">Share Area Calculation</button></div></form>}
    {!customerMode&&<section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Check previous Area Calculations</h2><div className="mt-4"><label className="text-sm font-semibold">Customer<span className="mt-2 flex items-center gap-2 rounded-xl border px-3 py-3"><Search className="h-4 w-4 text-slate-400"/><input value={customerSearch} onChange={e=>{setCustomerSearch(e.target.value);if(customer){setCustomer("");setAvailable([]);}}} placeholder="Search name, mobile, email, city or customer ID" className="w-full font-normal outline-none"/></span></label>{!customerSearch.trim()&&recentCustomers.length>0&&<div className="mt-3"><p className="mb-2 text-xs font-semibold text-slate-400">Recent customers</p><div className="flex flex-wrap gap-2">{recentCustomers.map(item=><button key={item.id} type="button" onClick={()=>selectCustomer(item)} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-200">{item.name} · {item.mobile}</button>)}</div></div>}{customerSearch.trim()&&!customer&&customerMatches.length>0&&<div className="mt-2 max-h-56 overflow-y-auto rounded-xl border bg-white p-1 shadow-sm">{customerMatches.slice(0,20).map(item=><button key={item.id} type="button" onClick={()=>selectCustomer(item)} className="block w-full rounded-lg px-3 py-2.5 text-left text-sm hover:bg-slate-100"><b>{item.name}</b><span className="ml-2 text-slate-500">{item.mobile}{item.city?" · "+item.city:""}</span></button>)}</div>}{customerSearch.trim()&&!customer&&!customerMatches.length&&<p className="mt-2 text-xs text-red-600">No matching customers found.</p>}</div>{customer&&<div className="mt-4 space-y-3">{available.length?available.map(item=><div key={item.id} className="flex flex-col gap-3 rounded-xl bg-slate-50 p-4 sm:flex-row sm:items-center"><Ruler className="h-5 w-5"/><div className="flex-1"><b>{item.name}</b><p className="text-xs text-slate-500">{item.property_type} · {item.rooms} rooms · {item.surfaces} surfaces</p></div><button onClick={()=>requestAccess(item)} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Request approval</button></div>):<p className="p-5 text-center text-sm text-slate-400">No previous Area Calculations available.</p>}</div>}</section>}
    <section className="overflow-hidden rounded-2xl border bg-white">{customerMode&&<header className="border-b p-4"><h2 className="font-bold">Shared properties and approval requests</h2></header>}{requests.length?<div className="divide-y">{requests.map(item=><div key={item.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><Ruler className="h-5 w-5 shrink-0"/><div className="min-w-0 flex-1"><b>{item.property_name}</b><p className="mt-1 text-xs text-slate-500">{customerMode?`Contractor: ${item.contractor_name} · ${item.contractor_bharath_id||item.contractor_mobile}`:`${item.customer_name} · ${item.measurement_type}`}</p><span className="mt-2 inline-block rounded-full bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700">{item.status === "FRESH_REQUESTED" ? "FRESH AREA CALCULATION REQUESTED" : item.status.replaceAll("_"," ")}</span></div>{customerMode&&item.status==="PENDING"?<div className="flex flex-wrap gap-2"><Small onClick={()=>decide(item,"APPROVED")}>Approve</Small><Small onClick={()=>decide(item,"FRESH_REQUESTED")}>Fresh Area Calculation</Small><Small onClick={()=>decide(item,"REJECTED")}>Reject</Small></div>:!customerMode&&item.status==="APPROVED"?<div className="flex flex-wrap gap-2"><Small onClick={()=>viewMeasurement(item)}><Eye className="h-4 w-4"/>View Area Calculation</Small><button onClick={()=>createQuotation(item)} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Create quotation</button></div>:null}</div>)}</div>:<p className="p-10 text-center text-sm text-slate-400">No Area Calculation sharing records.</p>}</section>
    {view&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-3"><div className="max-h-[92vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-4 sm:p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{view.property.name}</h2><p className="text-sm text-slate-500">{view.notice}</p></div><button onClick={()=>setView(null)}><X/></button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-100"><tr>{["Room","Surface","L","H/W","Gross","Deduction","Addition","Net sq ft"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{view.surfaces.map(s=><tr key={s.id} className="border-b"><td className="p-3">{s.room_name}</td><td className="p-3">{s.name}</td><td className="p-3">{s.length}</td><td className="p-3">{s.breadth}</td><td className="p-3">{s.gross_area}</td><td className="p-3">{s.deduction_area}</td><td className="p-3">{s.addition_area}</td><td className="p-3 font-bold">{s.net_area}</td></tr>)}</tbody></table></div></div></div>}
  </div>;
}
function Field({label,children}){return <label className="text-sm font-semibold">{label}<span className="mt-2 block [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:px-4 [&>*]:py-3 [&>*]:font-normal">{children}</span></label>}
function Small({children,...props}){return <button {...props} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold">{children}</button>}
