# Generated by Django 5.2.17 on 2026-10-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0001_initial'),
        ('quotations', '0115_quotation_line_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractquote',
            name='pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subcontractquoteline',
            name='discount_type',
            field=models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=12),
        ),
        migrations.AddField(
            model_name='subcontractquoteline',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subcontractquoteline',
            name='source_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced_lines', to='outsourcing.subcontractworkorderscope'),
        ),
        migrations.AddField(
            model_name='subcontractworkorder',
            name='material_mode',
            field=models.CharField(blank=True, choices=[('WITH_MATERIAL', 'With material'), ('WITHOUT_MATERIAL', 'Without material')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='subcontractworkorder',
            name='private_pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subcontractworkorderscope',
            name='source_quotation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_scopes', to='quotations.quotationitem'),
        ),
        migrations.AddField(
            model_name='subcontractworkorderscope',
            name='specification_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
