import { createContext, useContext, useEffect, useMemo, useState } from "react";

export const languages = [
  ["en", "English", "English"], ["kn", "ಕನ್ನಡ", "Kannada"], ["hi", "हिन्दी", "Hindi"],
  ["te", "తెలుగు", "Telugu"], ["ta", "தமிழ்", "Tamil"], ["ml", "മലയാളം", "Malayalam"],
  ["mr", "मराठी", "Marathi"], ["bn", "বাংলা", "Bengali"], ["gu", "ગુજરાતી", "Gujarati"],
  ["pa", "ਪੰਜਾਬੀ", "Punjabi"], ["or", "ଓଡ଼ିଆ", "Odia"], ["as", "অসমীয়া", "Assamese"],
];

const core = {
  kn: { Language:"ಭಾಷೆ", Dashboard:"ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", Work:"ಕೆಲಸ", People:"ಜನರು", Business:"ವ್ಯವಹಾರ", "Painter network":"ಅಪ್ಲಿಕೇಟರ್ ಜಾಲ", Support:"ಸಹಾಯ", Administration:"ನಿರ್ವಹಣೆ", "Available Jobs":"ಲಭ್ಯವಿರುವ ಕೆಲಸಗಳು", "Post Job Seeking":"ಕೆಲಸ ಹುಡುಕುವ ಪೋಸ್ಟ್", "My Profile":"ನನ್ನ ಪ್ರೊಫೈಲ್", "My Availability":"ನನ್ನ ಲಭ್ಯತೆ", "Booking Requests":"ಬುಕಿಂಗ್ ವಿನಂತಿಗಳು", Messages:"ಸಂದೇಶಗಳು", "Support Desk":"ಸಹಾಯ ಕೇಂದ್ರ", Verification:"ಪರಿಶೀಲನೆ", "Job Activity":"ಕೆಲಸದ ಚಟುವಟಿಕೆ", "My Assignments":"ನನ್ನ ನಿಯೋಜನೆಗಳು", "My Earnings":"ನನ್ನ ಆದಾಯ", Subscription:"ಚಂದಾದಾರಿಕೆ", "Ratings & Reviews":"ರೇಟಿಂಗ್ ಮತ್ತು ವಿಮರ್ಶೆಗಳು", "Work Photos":"ಕೆಲಸದ ಫೋಟೋಗಳು", "My Employment":"ನನ್ನ ಉದ್ಯೋಗ", Logout:"ಲಾಗ್ ಔಟ್", Notifications:"ಅಧಿಸೂಚನೆಗಳು", "Mark all read":"ಎಲ್ಲವನ್ನೂ ಓದಿದೆ ಎಂದು ಗುರುತಿಸಿ", "Profile settings":"ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು", "My account":"ನನ್ನ ಖಾತೆ", Customer:"ಗ್ರಾಹಕ", Property:"ಆಸ್ತಿ", Quotation:"ದರಪಟ್ಟಿ", Calculator:"ಕ್ಯಾಲ್ಕುಲೇಟರ್", "Job requirements":"ಕೆಲಸದ ಅವಶ್ಯಕತೆಗಳು", "Post requirement":"ಅವಶ್ಯಕತೆ ಪೋಸ್ಟ್ ಮಾಡಿ", "Find Paint Applicators":"ಪೇಂಟ್ ಅಪ್ಲಿಕೇಟರ್ ಹುಡುಕಿ", Apply:"ಅರ್ಜಿ ಸಲ್ಲಿಸಿ", Applied:"ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ" },
  hi: { Language:"भाषा", Dashboard:"डैशबोर्ड", Work:"काम", People:"लोग", Business:"व्यवसाय", "Painter network":"एप्लिकेटर नेटवर्क", Support:"सहायता", Administration:"प्रशासन", "Available Jobs":"उपलब्ध काम", "Post Job Seeking":"काम खोजने की पोस्ट", "My Profile":"मेरी प्रोफ़ाइल", "My Availability":"मेरी उपलब्धता", "Booking Requests":"बुकिंग अनुरोध", Messages:"संदेश", "Support Desk":"सहायता केंद्र", Verification:"सत्यापन", "Job Activity":"काम की गतिविधि", "My Assignments":"मेरे कार्य", "My Earnings":"मेरी कमाई", Subscription:"सदस्यता", "Ratings & Reviews":"रेटिंग और समीक्षा", "Work Photos":"काम की तस्वीरें", "My Employment":"मेरा रोजगार", Logout:"लॉग आउट", Notifications:"सूचनाएँ", "Mark all read":"सभी को पढ़ा हुआ करें", "Profile settings":"प्रोफ़ाइल सेटिंग", "My account":"मेरा खाता", Customer:"ग्राहक", Property:"संपत्ति", Quotation:"कोटेशन", Calculator:"कैलकुलेटर", "Job requirements":"काम की आवश्यकताएँ", "Post requirement":"आवश्यकता पोस्ट करें", "Find Paint Applicators":"पेंट एप्लिकेटर खोजें", Apply:"आवेदन करें", Applied:"आवेदन किया" },
  te: { Language:"భాష", Dashboard:"డాష్‌బోర్డ్", Work:"పని", People:"వ్యక్తులు", Business:"వ్యాపారం", "Painter network":"అప్లికేటర్ నెట్‌వర్క్", Support:"సహాయం", Administration:"నిర్వహణ", "Available Jobs":"అందుబాటులో ఉన్న పనులు", "Post Job Seeking":"పని కోసం పోస్ట్", "My Profile":"నా ప్రొఫైల్", "My Availability":"నా లభ్యత", "Booking Requests":"బుకింగ్ అభ్యర్థనలు", Messages:"సందేశాలు", "Support Desk":"సహాయ కేంద్రం", Verification:"ధృవీకరణ", "Job Activity":"పని కార్యకలాపాలు", "My Assignments":"నా అసైన్‌మెంట్లు", "My Earnings":"నా సంపాదన", Subscription:"చందా", "Ratings & Reviews":"రేటింగ్‌లు మరియు సమీక్షలు", "Work Photos":"పని ఫోటోలు", "My Employment":"నా ఉద్యోగం", Logout:"లాగ్ అవుట్", Notifications:"నోటిఫికేషన్లు", "Mark all read":"అన్నీ చదివినట్లు గుర్తించు", "Profile settings":"ప్రొఫైల్ సెట్టింగులు", "My account":"నా ఖాతా", Customer:"కస్టమర్", Property:"ఆస్తి", Quotation:"కొటేషన్", Calculator:"కాలిక్యులేటర్", "Job requirements":"పని అవసరాలు", "Post requirement":"అవసరాన్ని పోస్ట్ చేయండి", "Find Paint Applicators":"పెయింట్ అప్లికేటర్లను కనుగొనండి", Apply:"దరఖాస్తు చేయండి", Applied:"దరఖాస్తు చేశారు" },
  ta: { Language:"மொழி", Dashboard:"முகப்பு", "Available Jobs":"கிடைக்கும் வேலைகள்", "Post Job Seeking":"வேலை தேடல் பதிவு", "My Profile":"என் சுயவிவரம்", "My Availability":"என் கிடைக்கும் நாட்கள்", "Booking Requests":"முன்பதிவு கோரிக்கைகள்", Messages:"செய்திகள்", "Job Activity":"வேலை செயல்பாடு", Logout:"வெளியேறு" },
  ml: { Language:"ഭാഷ", Dashboard:"ഡാഷ്ബോർഡ്", "Available Jobs":"ലഭ്യമായ ജോലികൾ", "Post Job Seeking":"ജോലി തേടൽ പോസ്റ്റ്", "My Profile":"എന്റെ പ്രൊഫൈൽ", "My Availability":"എന്റെ ലഭ്യത", "Booking Requests":"ബുക്കിംഗ് അഭ്യർത്ഥനകൾ", Messages:"സന്ദേശങ്ങൾ", "Job Activity":"ജോലി പ്രവർത്തനം", Logout:"ലോഗൗട്ട്" },
  mr: { Language:"भाषा", Dashboard:"डॅशबोर्ड", "Available Jobs":"उपलब्ध कामे", "Post Job Seeking":"काम शोध पोस्ट", "My Profile":"माझे प्रोफाइल", "My Availability":"माझी उपलब्धता", "Booking Requests":"बुकिंग विनंत्या", Messages:"संदेश", "Job Activity":"कामाचा इतिहास", Logout:"लॉग आउट" },
  bn: { Language:"ভাষা", Dashboard:"ড্যাশবোর্ড", "Available Jobs":"উপলব্ধ কাজ", "Post Job Seeking":"কাজ খোঁজার পোস্ট", "My Profile":"আমার প্রোফাইল", "My Availability":"আমার উপলব্ধতা", "Booking Requests":"বুকিং অনুরোধ", Messages:"বার্তা", "Job Activity":"কাজের কার্যক্রম", Logout:"লগ আউট" },
  gu: { Language:"ભાષા", Dashboard:"ડેશબોર્ડ", "Available Jobs":"ઉપલબ્ધ કામ", "Post Job Seeking":"કામ શોધવાની પોસ્ટ", "My Profile":"મારી પ્રોફાઇલ", "My Availability":"મારી ઉપલબ્ધતા", "Booking Requests":"બુકિંગ વિનંતીઓ", Messages:"સંદેશા", "Job Activity":"કામની પ્રવૃત્તિ", Logout:"લૉગ આઉટ" },
  pa: { Language:"ਭਾਸ਼ਾ", Dashboard:"ਡੈਸ਼ਬੋਰਡ", "Available Jobs":"ਉਪਲਬਧ ਕੰਮ", "Post Job Seeking":"ਕੰਮ ਖੋਜ ਪੋਸਟ", "My Profile":"ਮੇਰੀ ਪ੍ਰੋਫ਼ਾਈਲ", "My Availability":"ਮੇਰੀ ਉਪਲਬਧਤਾ", "Booking Requests":"ਬੁਕਿੰਗ ਬੇਨਤੀਆਂ", Messages:"ਸੁਨੇਹੇ", "Job Activity":"ਕੰਮ ਦੀ ਗਤੀਵਿਧੀ", Logout:"ਲੌਗ ਆਉਟ" },
  or: { Language:"ଭାଷା", Dashboard:"ଡ୍ୟାସବୋର୍ଡ", "Available Jobs":"ଉପଲବ୍ଧ କାମ", "Post Job Seeking":"କାମ ଖୋଜିବା ପୋଷ୍ଟ", "My Profile":"ମୋ ପ୍ରୋଫାଇଲ୍", "My Availability":"ମୋ ଉପଲବ୍ଧତା", "Booking Requests":"ବୁକିଂ ଅନୁରୋଧ", Messages:"ସନ୍ଦେଶ", "Job Activity":"କାମ କାର୍ଯ୍ୟକଳାପ", Logout:"ଲଗ୍ ଆଉଟ୍" },
  as: { Language:"ভাষা", Dashboard:"ডেশ্ববৰ্ড", "Available Jobs":"উপলব্ধ কাম", "Post Job Seeking":"কাম বিচৰা পোষ্ট", "My Profile":"মোৰ প্ৰফাইল", "My Availability":"মোৰ উপলব্ধতা", "Booking Requests":"বুকিং অনুৰোধ", Messages:"বাৰ্তা", "Job Activity":"কামৰ কাৰ্যকলাপ", Logout:"লগ আউট" },
};

// Keep familiar application words and render them phonetically in the chosen
// script. This is easier for field users than formal translated terminology.
const phonetic = {
  te: {
    Language:"లాంగ్వేజ్", Dashboard:"డాష్‌బోర్డ్", Sales:"సేల్స్", Work:"వర్క్", People:"పీపుల్", Business:"బిజినెస్", "Painter network":"పెయింటర్ నెట్‌వర్క్", Support:"సపోర్ట్", Administration:"అడ్మినిస్ట్రేషన్", More:"మోర్",
    "CRM Dashboard":"సి ఆర్ ఎమ్ డాష్‌బోర్డ్", Opportunities:"ఆపర్చునిటీస్", Subscription:"సబ్‌స్క్రిప్షన్", Quotations:"కొటేషన్స్", Quotation:"కొటేషన్", Invoices:"ఇన్వాయిసెస్", "Revenue & Receipts":"రెవెన్యూ & రిసీప్ట్స్", Customers:"కస్టమర్స్", Customer:"కస్టమర్", "Post Job":"పోస్ట్ జాబ్", Tasks:"టాస్క్స్", Messages:"మెసేజెస్", Requests:"రిక్వెస్ట్స్", "Service Requests":"సర్వీస్ రిక్వెస్ట్స్", "Support Desk":"సపోర్ట్ డెస్క్", "Area Calculator":"ఏరియా కాలిక్యులేటర్", Properties:"ప్రాపర్టీస్", Property:"ప్రాపర్టీ", "Master Data":"మాస్టర్ డేటా", "Find Painter":"ఫైండ్ పెయింటర్", "Find Paint Applicators":"ఫైండ్ పెయింట్ అప్లికేటర్స్", "Register Applicator":"రిజిస్టర్ అప్లికేటర్", "Ratings & Reviews":"రేటింగ్స్ & రివ్యూస్", "In-house Applicators":"ఇన్-హౌస్ అప్లికేటర్స్", "Work Schedule":"వర్క్ షెడ్యూల్", Reschedule:"రీషెడ్యూల్", "Completed Work":"కంప్లీటెడ్ వర్క్", "Applicator Availability":"అప్లికేటర్ అవైలబిలిటీ", "Applicator Bookings":"అప్లికేటర్ బుకింగ్స్", "Work Photos":"వర్క్ ఫోటోస్", Reports:"రిపోర్ట్స్", "Activity Log":"యాక్టివిటీ లాగ్", "Available Jobs":"అవైలబుల్ జాబ్స్", "Post Job Seeking":"పోస్ట్ జాబ్ సీకింగ్", "My Employment":"మై ఎంప్లాయ్‌మెంట్", "My Earnings":"మై ఎర్నింగ్స్", "My Assignments":"మై అసైన్‌మెంట్స్", "My Profile":"మై ప్రొఫైల్", "My Availability":"మై అవైలబిలిటీ", "Booking Requests":"బుకింగ్ రిక్వెస్ట్స్", Verification:"వెరిఫికేషన్", "My Quotations":"మై కొటేషన్స్", "Payments & Invoices":"పేమెంట్స్ & ఇన్వాయిసెస్", "My Properties":"మై ప్రాపర్టీస్", "Share Area Calculation":"షేర్ ఏరియా కాలిక్యులేషన్", Packages:"ప్యాకేజెస్", Billing:"బిల్లింగ్", "Subscription Revenue":"సబ్‌స్క్రిప్షన్ రెవెన్యూ", "Paint Applicators":"పెయింట్ అప్లికేటర్స్", Contractors:"కాంట్రాక్టర్స్", "Job Activity":"జాబ్ యాక్టివిటీ", Settings:"సెట్టింగ్స్", Logout:"లాగ్ అవుట్", Notifications:"నోటిఫికేషన్స్", "Mark all read":"మార్క్ ఆల్ రీడ్", "Profile settings":"ప్రొఫైల్ సెట్టింగ్స్", "My account":"మై అకౌంట్", Calculator:"కాలిక్యులేటర్", "Job requirements":"జాబ్ రిక్వైర్‌మెంట్స్", "Post requirement":"పోస్ట్ రిక్వైర్‌మెంట్", Apply:"అప్లై", Applied:"అప్లైడ్",
  },
  kn: {
    Language:"ಲ್ಯಾಂಗ್ವೇಜ್", Dashboard:"ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", Sales:"ಸೇಲ್ಸ್", Work:"ವರ್ಕ್", People:"ಪೀಪಲ್", Business:"ಬಿಸಿನೆಸ್", "Painter network":"ಪೇಂಟರ್ ನೆಟ್‌ವರ್ಕ್", Support:"ಸಪೋರ್ಟ್", Administration:"ಅಡ್ಮಿನಿಸ್ಟ್ರೇಷನ್", More:"ಮೋರ್",
    "CRM Dashboard":"ಸಿ ಆರ್ ಎಂ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", Opportunities:"ಆಪರ್ಚುನಿಟೀಸ್", Subscription:"ಸಬ್‌ಸ್ಕ್ರಿಪ್ಷನ್", Quotations:"ಕೊಟೇಷನ್ಸ್", Quotation:"ಕೊಟೇಷನ್", Invoices:"ಇನ್‌ವಾಯ್ಸಸ್", "Revenue & Receipts":"ರೆವೆನ್ಯೂ & ರಿಸೀಪ್ಟ್ಸ್", Customers:"ಕಸ್ಟಮರ್ಸ್", Customer:"ಕಸ್ಟಮರ್", "Post Job":"ಪೋಸ್ಟ್ ಜಾಬ್", Tasks:"ಟಾಸ್ಕ್ಸ್", Messages:"ಮೆಸೇಜಸ್", Requests:"ರಿಕ್ವೆಸ್ಟ್ಸ್", "Service Requests":"ಸರ್ವೀಸ್ ರಿಕ್ವೆಸ್ಟ್ಸ್", "Support Desk":"ಸಪೋರ್ಟ್ ಡೆಸ್ಕ್", "Area Calculator":"ಏರಿಯಾ ಕ್ಯಾಲ್ಕುಲೇಟರ್", Properties:"ಪ್ರಾಪರ್ಟೀಸ್", Property:"ಪ್ರಾಪರ್ಟಿ", "Master Data":"ಮಾಸ್ಟರ್ ಡೇಟಾ", "Find Painter":"ಫೈಂಡ್ ಪೇಂಟರ್", "Find Paint Applicators":"ಫೈಂಡ್ ಪೇಂಟ್ ಅಪ್ಲಿಕೇಟರ್ಸ್", "Register Applicator":"ರಿಜಿಸ್ಟರ್ ಅಪ್ಲಿಕೇಟರ್", "Ratings & Reviews":"ರೇಟಿಂಗ್ಸ್ & ರಿವ್ಯೂಸ್", "In-house Applicators":"ಇನ್-ಹೌಸ್ ಅಪ್ಲಿಕೇಟರ್ಸ್", "Work Schedule":"ವರ್ಕ್ ಶೆಡ್ಯೂಲ್", Reschedule:"ರೀಶೆಡ್ಯೂಲ್", "Completed Work":"ಕಂಪ್ಲೀಟೆಡ್ ವರ್ಕ್", "Applicator Availability":"ಅಪ್ಲಿಕೇಟರ್ ಅವೈಲಬಿಲಿಟಿ", "Applicator Bookings":"ಅಪ್ಲಿಕೇಟರ್ ಬುಕ್ಕಿಂಗ್ಸ್", "Work Photos":"ವರ್ಕ್ ಫೋಟೋಸ್", Reports:"ರಿಪೋರ್ಟ್ಸ್", "Activity Log":"ಆಕ್ಟಿವಿಟಿ ಲಾಗ್", "Available Jobs":"ಅವೈಲಬಲ್ ಜಾಬ್ಸ್", "Post Job Seeking":"ಪೋಸ್ಟ್ ಜಾಬ್ ಸೀಕಿಂಗ್", "My Employment":"ಮೈ ಎಂಪ್ಲಾಯ್‌ಮೆಂಟ್", "My Earnings":"ಮೈ ಅರ್ನಿಂಗ್ಸ್", "My Assignments":"ಮೈ ಅಸೈನ್‌ಮೆಂಟ್ಸ್", "My Profile":"ಮೈ ಪ್ರೊಫೈಲ್", "My Availability":"ಮೈ ಅವೈಲಬಿಲಿಟಿ", "Booking Requests":"ಬುಕ್ಕಿಂಗ್ ರಿಕ್ವೆಸ್ಟ್ಸ್", Verification:"ವೆರಿಫಿಕೇಷನ್", "My Quotations":"ಮೈ ಕೊಟೇಷನ್ಸ್", "Payments & Invoices":"ಪೇಮೆಂಟ್ಸ್ & ಇನ್‌ವಾಯ್ಸಸ್", "My Properties":"ಮೈ ಪ್ರಾಪರ್ಟೀಸ್", "Share Area Calculation":"ಶೇರ್ ಏರಿಯಾ ಕ್ಯಾಲ್ಕುಲೇಷನ್", Packages:"ಪ್ಯಾಕೇಜಸ್", Billing:"ಬಿಲ್ಲಿಂಗ್", "Subscription Revenue":"ಸಬ್‌ಸ್ಕ್ರಿಪ್ಷನ್ ರೆವೆನ್ಯೂ", "Paint Applicators":"ಪೇಂಟ್ ಅಪ್ಲಿಕೇಟರ್ಸ್", Contractors:"ಕಾಂಟ್ರಾಕ್ಟರ್ಸ್", "Job Activity":"ಜಾಬ್ ಆಕ್ಟಿವಿಟಿ", Settings:"ಸೆಟ್ಟಿಂಗ್ಸ್", Logout:"ಲಾಗ್ ಔಟ್", Notifications:"ನೋಟಿಫಿಕೇಷನ್ಸ್", "Mark all read":"ಮಾರ್ಕ್ ಆಲ್ ರೀಡ್", "Profile settings":"ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್ಸ್", "My account":"ಮೈ ಅಕೌಂಟ್", Calculator:"ಕ್ಯಾಲ್ಕುಲೇಟರ್", "Job requirements":"ಜಾಬ್ ರಿಕ್ವೈರ್‌ಮೆಂಟ್ಸ್", "Post requirement":"ಪೋಸ್ಟ್ ರಿಕ್ವೈರ್‌ಮೆಂಟ್", Apply:"ಅಪ್ಲೈ", Applied:"ಅಪ್ಲೈಡ್",
  },
  hi: {
    Language:"लैंग्वेज", Dashboard:"डैशबोर्ड", Sales:"सेल्स", Work:"वर्क", People:"पीपल", Business:"बिज़नेस", "Painter network":"पेंटर नेटवर्क", Support:"सपोर्ट", Administration:"एडमिनिस्ट्रेशन", More:"मोर",
    "CRM Dashboard":"सी आर एम डैशबोर्ड", Opportunities:"ऑपर्च्युनिटीज़", Subscription:"सब्सक्रिप्शन", Quotations:"कोटेशन्स", Quotation:"कोटेशन", Invoices:"इनवॉइसेस", "Revenue & Receipts":"रेवेन्यू & रिसीट्स", Customers:"कस्टमर्स", Customer:"कस्टमर", "Post Job":"पोस्ट जॉब", Tasks:"टास्क्स", Messages:"मैसेजेस", Requests:"रिक्वेस्ट्स", "Service Requests":"सर्विस रिक्वेस्ट्स", "Support Desk":"सपोर्ट डेस्क", "Area Calculator":"एरिया कैलकुलेटर", Properties:"प्रॉपर्टीज़", Property:"प्रॉपर्टी", "Master Data":"मास्टर डेटा", "Find Painter":"फाइंड पेंटर", "Find Paint Applicators":"फाइंड पेंट एप्लिकेटर्स", "Register Applicator":"रजिस्टर एप्लिकेटर", "Ratings & Reviews":"रेटिंग्स & रिव्यूज़", "In-house Applicators":"इन-हाउस एप्लिकेटर्स", "Work Schedule":"वर्क शेड्यूल", Reschedule:"रीशेड्यूल", "Completed Work":"कम्प्लीटेड वर्क", "Applicator Availability":"एप्लिकेटर अवेलेबिलिटी", "Applicator Bookings":"एप्लिकेटर बुकिंग्स", "Work Photos":"वर्क फोटोज़", Reports:"रिपोर्ट्स", "Activity Log":"एक्टिविटी लॉग", "Available Jobs":"अवेलेबल जॉब्स", "Post Job Seeking":"पोस्ट जॉब सीकिंग", "My Employment":"माय एम्प्लॉयमेंट", "My Earnings":"माय अर्निंग्स", "My Assignments":"माय असाइनमेंट्स", "My Profile":"माय प्रोफाइल", "My Availability":"माय अवेलेबिलिटी", "Booking Requests":"बुकिंग रिक्वेस्ट्स", Verification:"वेरिफिकेशन", "My Quotations":"माय कोटेशन्स", "Payments & Invoices":"पेमेंट्स & इनवॉइसेस", "My Properties":"माय प्रॉपर्टीज़", "Share Area Calculation":"शेयर एरिया कैलकुलेशन", Packages:"पैकेजेस", Billing:"बिलिंग", "Subscription Revenue":"सब्सक्रिप्शन रेवेन्यू", "Paint Applicators":"पेंट एप्लिकेटर्स", Contractors:"कॉन्ट्रैक्टर्स", "Job Activity":"जॉब एक्टिविटी", Settings:"सेटिंग्स", Logout:"लॉग आउट", Notifications:"नोटिफिकेशन्स", "Mark all read":"मार्क ऑल रीड", "Profile settings":"प्रोफाइल सेटिंग्स", "My account":"माय अकाउंट", Calculator:"कैलकुलेटर", "Job requirements":"जॉब रिक्वायरमेंट्स", "Post requirement":"पोस्ट रिक्वायरमेंट", Apply:"अप्लाई", Applied:"अप्लाइड",
  },
  ta: {
    Language:"லேங்குவேஜ்", Dashboard:"டாஷ்போர்டு", Sales:"சேல்ஸ்", Work:"வொர்க்", People:"பீப்பிள்", Business:"பிசினஸ்", "Painter network":"பெயிண்டர் நெட்வொர்க்", Support:"சப்போர்ட்", Administration:"அட்மினிஸ்ட்ரேஷன்", More:"மோர்",
    "CRM Dashboard":"சி ஆர் எம் டாஷ்போர்டு", Opportunities:"ஆப்பர்ச்சூனிட்டீஸ்", Subscription:"சப்ஸ்கிரிப்ஷன்", Quotations:"கொட்டேஷன்ஸ்", Quotation:"கொட்டேஷன்", Invoices:"இன்வாய்ஸ்கள்", "Revenue & Receipts":"ரெவின்யூ & ரிசீப்ட்ஸ்", Customers:"கஸ்டமர்ஸ்", Customer:"கஸ்டமர்", "Post Job":"போஸ்ட் ஜாப்", Tasks:"டாஸ்க்ஸ்", Messages:"மெசேஜஸ்", Requests:"ரிக்வெஸ்ட்ஸ்", "Service Requests":"சர்வீஸ் ரிக்வெஸ்ட்ஸ்", "Support Desk":"சப்போர்ட் டெஸ்க்", "Area Calculator":"ஏரியா கால்குலேட்டர்", Properties:"ப்ராப்பர்டீஸ்", Property:"ப்ராப்பர்டி", "Master Data":"மாஸ்டர் டேட்டா", "Find Painter":"ஃபைண்ட் பெயிண்டர்", "Find Paint Applicators":"ஃபைண்ட் பெயிண்ட் அப்ளிகேட்டர்ஸ்", "Register Applicator":"ரெஜிஸ்டர் அப்ளிகேட்டர்", "Ratings & Reviews":"ரேட்டிங்ஸ் & ரிவ்யூஸ்", "In-house Applicators":"இன்-ஹவுஸ் அப்ளிகேட்டர்ஸ்", "Work Schedule":"வொர்க் ஷெட்யூல்", Reschedule:"ரீஷெட்யூல்", "Completed Work":"கம்ப்ளீட்டட் வொர்க்", "Applicator Availability":"அப்ளிகேட்டர் அவைலபிலிட்டி", "Applicator Bookings":"அப்ளிகேட்டர் புக்கிங்ஸ்", "Work Photos":"வொர்க் போட்டோஸ்", Reports:"ரிப்போர்ட்ஸ்", "Activity Log":"ஆக்டிவிட்டி லாக்", "Available Jobs":"அவைலபிள் ஜாப்ஸ்", "Post Job Seeking":"போஸ்ட் ஜாப் சீக்கிங்", "My Employment":"மை எம்ப்ளாய்மெண்ட்", "My Earnings":"மை ஏர்னிங்ஸ்", "My Assignments":"மை அசைன்மெண்ட்ஸ்", "My Profile":"மை ப்ரொஃபைல்", "My Availability":"மை அவைலபிலிட்டி", "Booking Requests":"புக்கிங் ரிக்வெஸ்ட்ஸ்", Verification:"வெரிஃபிகேஷன்", "My Quotations":"மை கொட்டேஷன்ஸ்", "Payments & Invoices":"பேமெண்ட்ஸ் & இன்வாய்ஸ்கள்", "My Properties":"மை ப்ராப்பர்டீஸ்", "Share Area Calculation":"ஷேர் ஏரியா கால்குலேஷன்", Packages:"பேக்கேஜஸ்", Billing:"பில்லிங்", "Subscription Revenue":"சப்ஸ்கிரிப்ஷன் ரெவின்யூ", "Paint Applicators":"பெயிண்ட் அப்ளிகேட்டர்ஸ்", Contractors:"கான்ட்ராக்டர்ஸ்", "Job Activity":"ஜாப் ஆக்டிவிட்டி", Settings:"செட்டிங்ஸ்", Logout:"லாக் அவுட்", Notifications:"நோட்டிஃபிகேஷன்ஸ்", "Mark all read":"மார்க் ஆல் ரீட்", "Profile settings":"ப்ரொஃபைல் செட்டிங்ஸ்", "My account":"மை அக்கவுண்ட்", Calculator:"கால்குலேட்டர்", "Job requirements":"ஜாப் ரிக்வையர்மெண்ட்ஸ்", "Post requirement":"போஸ்ட் ரிக்வையர்மெண்ட்", Apply:"அப்ளை", Applied:"அப்ளைட்",
  },
  ml: {
    Language:"ലാംഗ്വേജ്", Dashboard:"ഡാഷ്ബോർഡ്", Sales:"സെയിൽസ്", Work:"വർക്ക്", People:"പീപ്പിൾ", Business:"ബിസിനസ്", "Painter network":"പെയിന്റർ നെറ്റ്‌വർക്ക്", Support:"സപ്പോർട്ട്", Administration:"അഡ്മിനിസ്ട്രേഷൻ", More:"മോർ",
    "CRM Dashboard":"സി ആർ എം ഡാഷ്ബോർഡ്", Opportunities:"ഓപ്പർച്യൂണിറ്റീസ്", Subscription:"സബ്സ്ക്രിപ്ഷൻ", Quotations:"ക്വട്ടേഷനുകൾ", Quotation:"ക്വട്ടേഷൻ", Invoices:"ഇൻവോയ്സുകൾ", "Revenue & Receipts":"റെവന്യൂ & റസീപ്റ്റ്സ്", Customers:"കസ്റ്റമേഴ്സ്", Customer:"കസ്റ്റമർ", "Post Job":"പോസ്റ്റ് ജോബ്", Tasks:"ടാസ്ക്സ്", Messages:"മെസേജസ്", Requests:"റിക്വസ്റ്റ്സ്", "Service Requests":"സർവീസ് റിക്വസ്റ്റ്സ്", "Support Desk":"സപ്പോർട്ട് ഡെസ്ക്", "Area Calculator":"ഏരിയ കാൽക്കുലേറ്റർ", Properties:"പ്രോപ്പർട്ടീസ്", Property:"പ്രോപ്പർട്ടി", "Master Data":"മാസ്റ്റർ ഡാറ്റ", "Find Painter":"ഫൈൻഡ് പെയിന്റർ", "Find Paint Applicators":"ഫൈൻഡ് പെയിന്റ് ആപ്ലിക്കേറ്റേഴ്സ്", "Register Applicator":"രജിസ്റ്റർ ആപ്ലിക്കേറ്റർ", "Ratings & Reviews":"റേറ്റിംഗ്സ് & റിവ്യൂസ്", "In-house Applicators":"ഇൻ-ഹൗസ് ആപ്ലിക്കേറ്റേഴ്സ്", "Work Schedule":"വർക്ക് ഷെഡ്യൂൾ", Reschedule:"റീഷെഡ്യൂൾ", "Completed Work":"കംപ്ലീറ്റഡ് വർക്ക്", "Applicator Availability":"ആപ്ലിക്കേറ്റർ അവൈലബിലിറ്റി", "Applicator Bookings":"ആപ്ലിക്കേറ്റർ ബുക്കിംഗ്സ്", "Work Photos":"വർക്ക് ഫോട്ടോസ്", Reports:"റിപ്പോർട്ട്സ്", "Activity Log":"ആക്ടിവിറ്റി ലോഗ്", "Available Jobs":"അവൈലബിൾ ജോബ്സ്", "Post Job Seeking":"പോസ്റ്റ് ജോബ് സീക്കിംഗ്", "My Employment":"മൈ എംപ്ലോയ്‌മെന്റ്", "My Earnings":"മൈ ഏണിംഗ്സ്", "My Assignments":"മൈ അസൈൻമെന്റ്സ്", "My Profile":"മൈ പ്രൊഫൈൽ", "My Availability":"മൈ അവൈലബിലിറ്റി", "Booking Requests":"ബുക്കിംഗ് റിക്വസ്റ്റ്സ്", Verification:"വെരിഫിക്കേഷൻ", "My Quotations":"മൈ ക്വട്ടേഷനുകൾ", "Payments & Invoices":"പേയ്മെന്റ്സ് & ഇൻവോയ്സുകൾ", "My Properties":"മൈ പ്രോപ്പർട്ടീസ്", "Share Area Calculation":"ഷെയർ ഏരിയ കാൽക്കുലേഷൻ", Packages:"പാക്കേജസ്", Billing:"ബില്ലിംഗ്", "Subscription Revenue":"സബ്സ്ക്രിപ്ഷൻ റെവന്യൂ", "Paint Applicators":"പെയിന്റ് ആപ്ലിക്കേറ്റേഴ്സ്", Contractors:"കോൺട്രാക്ടേഴ്സ്", "Job Activity":"ജോബ് ആക്ടിവിറ്റി", Settings:"സെറ്റിംഗ്സ്", Logout:"ലോഗ് ഔട്ട്", Notifications:"നോട്ടിഫിക്കേഷനുകൾ", "Mark all read":"മാർക്ക് ഓൾ റീഡ്", "Profile settings":"പ്രൊഫൈൽ സെറ്റിംഗ്സ്", "My account":"മൈ അക്കൗണ്ട്", Calculator:"കാൽക്കുലേറ്റർ", "Job requirements":"ജോബ് റിക്വയർമെന്റ്സ്", "Post requirement":"പോസ്റ്റ് റിക്വയർമെന്റ്", Apply:"അപ്ലൈ", Applied:"അപ്ലൈഡ്",
  },
  mr: {
    Language:"लँग्वेज", Dashboard:"डॅशबोर्ड", Sales:"सेल्स", Work:"वर्क", People:"पीपल", Business:"बिझनेस", "Painter network":"पेंटर नेटवर्क", Support:"सपोर्ट", Administration:"ॲडमिनिस्ट्रेशन", More:"मोर",
    "CRM Dashboard":"सी आर एम डॅशबोर्ड", Opportunities:"ऑपर्च्युनिटीज", Subscription:"सबस्क्रिप्शन", Quotations:"कोटेशन्स", Quotation:"कोटेशन", Invoices:"इनव्हॉइसेस", "Revenue & Receipts":"रेव्हेन्यू & रिसीट्स", Customers:"कस्टमर्स", Customer:"कस्टमर", "Post Job":"पोस्ट जॉब", Tasks:"टास्क्स", Messages:"मेसेजेस", Requests:"रिक्वेस्ट्स", "Service Requests":"सर्विस रिक्वेस्ट्स", "Support Desk":"सपोर्ट डेस्क", "Area Calculator":"एरिया कॅल्क्युलेटर", Properties:"प्रॉपर्टीज", Property:"प्रॉपर्टी", "Master Data":"मास्टर डेटा", "Find Painter":"फाइंड पेंटर", "Find Paint Applicators":"फाइंड पेंट ॲप्लिकेटर्स", "Register Applicator":"रजिस्टर ॲप्लिकेटर", "Ratings & Reviews":"रेटिंग्स & रिव्ह्यूज", "In-house Applicators":"इन-हाऊस ॲप्लिकेटर्स", "Work Schedule":"वर्क शेड्यूल", Reschedule:"रीशेड्यूल", "Completed Work":"कम्प्लीटेड वर्क", "Applicator Availability":"ॲप्लिकेटर अव्हेलेबिलिटी", "Applicator Bookings":"ॲप्लिकेटर बुकिंग्स", "Work Photos":"वर्क फोटोज", Reports:"रिपोर्ट्स", "Activity Log":"ॲक्टिव्हिटी लॉग", "Available Jobs":"अव्हेलेबल जॉब्स", "Post Job Seeking":"पोस्ट जॉब सीकिंग", "My Employment":"माय एम्प्लॉयमेंट", "My Earnings":"माय अर्निंग्स", "My Assignments":"माय असाइनमेंट्स", "My Profile":"माय प्रोफाइल", "My Availability":"माय अव्हेलेबिलिटी", "Booking Requests":"बुकिंग रिक्वेस्ट्स", Verification:"व्हेरिफिकेशन", "My Quotations":"माय कोटेशन्स", "Payments & Invoices":"पेमेंट्स & इनव्हॉइसेस", "My Properties":"माय प्रॉपर्टीज", "Share Area Calculation":"शेअर एरिया कॅल्क्युलेशन", Packages:"पॅकेजेस", Billing:"बिलिंग", "Subscription Revenue":"सबस्क्रिप्शन रेव्हेन्यू", "Paint Applicators":"पेंट ॲप्लिकेटर्स", Contractors:"कॉन्ट्रॅक्टर्स", "Job Activity":"जॉब ॲक्टिव्हिटी", Settings:"सेटिंग्स", Logout:"लॉग आउट", Notifications:"नोटिफिकेशन्स", "Mark all read":"मार्क ऑल रीड", "Profile settings":"प्रोफाइल सेटिंग्स", "My account":"माय अकाउंट", Calculator:"कॅल्क्युलेटर", "Job requirements":"जॉब रिक्वायरमेंट्स", "Post requirement":"पोस्ट रिक्वायरमेंट", Apply:"ॲप्लाय", Applied:"ॲप्लाइड",
  },
  bn: {
    Language:"ল্যাঙ্গুয়েজ", Dashboard:"ড্যাশবোর্ড", Sales:"সেলস", Work:"ওয়ার্ক", People:"পিপল", Business:"বিজনেস", "Painter network":"পেইন্টার নেটওয়ার্ক", Support:"সাপোর্ট", Administration:"অ্যাডমিনিস্ট্রেশন", More:"মোর",
    "CRM Dashboard":"সি আর এম ড্যাশবোর্ড", Opportunities:"অপরচুনিটিজ", Subscription:"সাবস্ক্রিপশন", Quotations:"কোটেশনস", Quotation:"কোটেশন", Invoices:"ইনভয়েসেস", "Revenue & Receipts":"রেভিনিউ & রিসিপ্টস", Customers:"কাস্টমার্স", Customer:"কাস্টমার", "Post Job":"পোস্ট জব", Tasks:"টাস্কস", Messages:"মেসেজেস", Requests:"রিকোয়েস্টস", "Service Requests":"সার্ভিস রিকোয়েস্টস", "Support Desk":"সাপোর্ট ডেস্ক", "Area Calculator":"এরিয়া ক্যালকুলেটর", Properties:"প্রপার্টিজ", Property:"প্রপার্টি", "Master Data":"মাস্টার ডাটা", "Find Painter":"ফাইন্ড পেইন্টার", "Find Paint Applicators":"ফাইন্ড পেইন্ট অ্যাপ্লিকেটর্স", "Register Applicator":"রেজিস্টার অ্যাপ্লিকেটর", "Ratings & Reviews":"রেটিংস & রিভিউস", "In-house Applicators":"ইন-হাউস অ্যাপ্লিকেটর্স", "Work Schedule":"ওয়ার্ক শিডিউল", Reschedule:"রিশিডিউল", "Completed Work":"কমপ্লিটেড ওয়ার্ক", "Applicator Availability":"অ্যাপ্লিকেটর অ্যাভেইলেবিলিটি", "Applicator Bookings":"অ্যাপ্লিকেটর বুকিংস", "Work Photos":"ওয়ার্ক ফটোস", Reports:"রিপোর্টস", "Activity Log":"অ্যাক্টিভিটি লগ", "Available Jobs":"অ্যাভেইলেবল জবস", "Post Job Seeking":"পোস্ট জব সিকিং", "My Employment":"মাই এমপ্লয়মেন্ট", "My Earnings":"মাই আর্নিংস", "My Assignments":"মাই অ্যাসাইনমেন্টস", "My Profile":"মাই প্রোফাইল", "My Availability":"মাই অ্যাভেইলেবিলিটি", "Booking Requests":"বুকিং রিকোয়েস্টস", Verification:"ভেরিফিকেশন", "My Quotations":"মাই কোটেশনস", "Payments & Invoices":"পেমেন্টস & ইনভয়েসেস", "My Properties":"মাই প্রপার্টিজ", "Share Area Calculation":"শেয়ার এরিয়া ক্যালকুলেশন", Packages:"প্যাকেজেস", Billing:"বিলিং", "Subscription Revenue":"সাবস্ক্রিপশন রেভিনিউ", "Paint Applicators":"পেইন্ট অ্যাপ্লিকেটর্স", Contractors:"কন্ট্রাক্টর্স", "Job Activity":"জব অ্যাক্টিভিটি", Settings:"সেটিংস", Logout:"লগ আউট", Notifications:"নোটিফিকেশনস", "Mark all read":"মার্ক অল রিড", "Profile settings":"প্রোফাইল সেটিংস", "My account":"মাই অ্যাকাউন্ট", Calculator:"ক্যালকুলেটর", "Job requirements":"জব রিকোয়ারমেন্টস", "Post requirement":"পোস্ট রিকোয়ারমেন্ট", Apply:"অ্যাপ্লাই", Applied:"অ্যাপ্লাইড",
  },
  gu: {
    Language:"લેંગ્વેજ", Dashboard:"ડેશબોર્ડ", Sales:"સેલ્સ", Work:"વર્ક", People:"પીપલ", Business:"બિઝનેસ", "Painter network":"પેઇન્ટર નેટવર્ક", Support:"સપોર્ટ", Administration:"એડમિનિસ્ટ્રેશન", More:"મોર",
    "CRM Dashboard":"સી આર એમ ડેશબોર્ડ", Opportunities:"ઓપર્ચ્યુનિટીઝ", Subscription:"સબ્સ્ક્રિપ્શન", Quotations:"કોટેશન્સ", Quotation:"કોટેશન", Invoices:"ઇનવોઇસેસ", "Revenue & Receipts":"રેવેન્યુ & રિસીપ્ટ્સ", Customers:"કસ્ટમર્સ", Customer:"કસ્ટમર", "Post Job":"પોસ્ટ જોબ", Tasks:"ટાસ્ક્સ", Messages:"મેસેજેસ", Requests:"રિક્વેસ્ટ્સ", "Service Requests":"સર્વિસ રિક્વેસ્ટ્સ", "Support Desk":"સપોર્ટ ડેસ્ક", "Area Calculator":"એરિયા કેલ્ક્યુલેટર", Properties:"પ્રોપર્ટીઝ", Property:"પ્રોપર્ટી", "Master Data":"માસ્ટર ડેટા", "Find Painter":"ફાઇન્ડ પેઇન્ટર", "Find Paint Applicators":"ફાઇન્ડ પેઇન્ટ એપ્લિકેટર્સ", "Register Applicator":"રજિસ્ટર એપ્લિકેટર", "Ratings & Reviews":"રેટિંગ્સ & રિવ્યૂઝ", "In-house Applicators":"ઇન-હાઉસ એપ્લિકેટર્સ", "Work Schedule":"વર્ક શેડ્યૂલ", Reschedule:"રીશેડ્યૂલ", "Completed Work":"કમ્પ્લીટેડ વર્ક", "Applicator Availability":"એપ્લિકેટર અવેલેબિલિટી", "Applicator Bookings":"એપ્લિકેટર બુકિંગ્સ", "Work Photos":"વર્ક ફોટોઝ", Reports:"રિપોર્ટ્સ", "Activity Log":"એક્ટિવિટી લોગ", "Available Jobs":"અવેલેબલ જોબ્સ", "Post Job Seeking":"પોસ્ટ જોબ સીકિંગ", "My Employment":"માય એમ્પ્લોયમેન્ટ", "My Earnings":"માય અર્નિંગ્સ", "My Assignments":"માય અસાઇનમેન્ટ્સ", "My Profile":"માય પ્રોફાઇલ", "My Availability":"માય અવેલેબિલિટી", "Booking Requests":"બુકિંગ રિક્વેસ્ટ્સ", Verification:"વેરિફિકેશન", "My Quotations":"માય કોટેશન્સ", "Payments & Invoices":"પેમેન્ટ્સ & ઇનવોઇસેસ", "My Properties":"માય પ્રોપર્ટીઝ", "Share Area Calculation":"શેર એરિયા કેલ્ક્યુલેશન", Packages:"પેકેજેસ", Billing:"બિલિંગ", "Subscription Revenue":"સબ્સ્ક્રિપ્શન રેવેન્યુ", "Paint Applicators":"પેઇન્ટ એપ્લિકેટર્સ", Contractors:"કોન્ટ્રાક્ટર્સ", "Job Activity":"જોબ એક્ટિવિટી", Settings:"સેટિંગ્સ", Logout:"લોગ આઉટ", Notifications:"નોટિફિકેશન્સ", "Mark all read":"માર્ક ઓલ રીડ", "Profile settings":"પ્રોફાઇલ સેટિંગ્સ", "My account":"માય અકાઉન્ટ", Calculator:"કેલ્ક્યુલેટર", "Job requirements":"જોબ રિક્વાયરમેન્ટ્સ", "Post requirement":"પોસ્ટ રિક્વાયરમેન્ટ", Apply:"એપ્લાય", Applied:"એપ્લાઇડ",
  },
  pa: {
    Language:"ਲੈਂਗਵੇਜ", Dashboard:"ਡੈਸ਼ਬੋਰਡ", Sales:"ਸੇਲਜ਼", Work:"ਵਰਕ", People:"ਪੀਪਲ", Business:"ਬਿਜ਼ਨਸ", "Painter network":"ਪੇਂਟਰ ਨੈੱਟਵਰਕ", Support:"ਸਪੋਰਟ", Administration:"ਐਡਮਿਨਿਸਟ੍ਰੇਸ਼ਨ", More:"ਮੋਰ",
    "CRM Dashboard":"ਸੀ ਆਰ ਐਮ ਡੈਸ਼ਬੋਰਡ", Opportunities:"ਅਪਰਚੂਨਿਟੀਜ਼", Subscription:"ਸਬਸਕ੍ਰਿਪਸ਼ਨ", Quotations:"ਕੋਟੇਸ਼ਨਜ਼", Quotation:"ਕੋਟੇਸ਼ਨ", Invoices:"ਇਨਵੌਇਸਜ਼", "Revenue & Receipts":"ਰੈਵੇਨਿਊ & ਰਿਸੀਟਸ", Customers:"ਕਸਟਮਰਜ਼", Customer:"ਕਸਟਮਰ", "Post Job":"ਪੋਸਟ ਜੌਬ", Tasks:"ਟਾਸਕਸ", Messages:"ਮੈਸੇਜਸ", Requests:"ਰਿਕਵੈਸਟਸ", "Service Requests":"ਸਰਵਿਸ ਰਿਕਵੈਸਟਸ", "Support Desk":"ਸਪੋਰਟ ਡੈਸਕ", "Area Calculator":"ਏਰੀਆ ਕੈਲਕੁਲੇਟਰ", Properties:"ਪ੍ਰਾਪਰਟੀਜ਼", Property:"ਪ੍ਰਾਪਰਟੀ", "Master Data":"ਮਾਸਟਰ ਡਾਟਾ", "Find Painter":"ਫਾਈਂਡ ਪੇਂਟਰ", "Find Paint Applicators":"ਫਾਈਂਡ ਪੇਂਟ ਐਪਲੀਕੇਟਰਜ਼", "Register Applicator":"ਰਜਿਸਟਰ ਐਪਲੀਕੇਟਰ", "Ratings & Reviews":"ਰੇਟਿੰਗਸ & ਰਿਵਿਊਜ਼", "In-house Applicators":"ਇਨ-ਹਾਊਸ ਐਪਲੀਕੇਟਰਜ਼", "Work Schedule":"ਵਰਕ ਸ਼ੈਡਿਊਲ", Reschedule:"ਰੀਸ਼ੈਡਿਊਲ", "Completed Work":"ਕੰਪਲੀਟਡ ਵਰਕ", "Applicator Availability":"ਐਪਲੀਕੇਟਰ ਅਵੇਲੇਬਿਲਟੀ", "Applicator Bookings":"ਐਪਲੀਕੇਟਰ ਬੁਕਿੰਗਸ", "Work Photos":"ਵਰਕ ਫੋਟੋਜ਼", Reports:"ਰਿਪੋਰਟਸ", "Activity Log":"ਐਕਟਿਵਿਟੀ ਲੌਗ", "Available Jobs":"ਅਵੇਲੇਬਲ ਜੌਬਸ", "Post Job Seeking":"ਪੋਸਟ ਜੌਬ ਸੀਕਿੰਗ", "My Employment":"ਮਾਈ ਐਮਪਲੌਇਮੈਂਟ", "My Earnings":"ਮਾਈ ਅਰਨਿੰਗਸ", "My Assignments":"ਮਾਈ ਅਸਾਈਨਮੈਂਟਸ", "My Profile":"ਮਾਈ ਪ੍ਰੋਫਾਈਲ", "My Availability":"ਮਾਈ ਅਵੇਲੇਬਿਲਟੀ", "Booking Requests":"ਬੁਕਿੰਗ ਰਿਕਵੈਸਟਸ", Verification:"ਵੈਰੀਫਿਕੇਸ਼ਨ", "My Quotations":"ਮਾਈ ਕੋਟੇਸ਼ਨਜ਼", "Payments & Invoices":"ਪੇਮੈਂਟਸ & ਇਨਵੌਇਸਜ਼", "My Properties":"ਮਾਈ ਪ੍ਰਾਪਰਟੀਜ਼", "Share Area Calculation":"ਸ਼ੇਅਰ ਏਰੀਆ ਕੈਲਕੁਲੇਸ਼ਨ", Packages:"ਪੈਕੇਜਸ", Billing:"ਬਿਲਿੰਗ", "Subscription Revenue":"ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਰੈਵੇਨਿਊ", "Paint Applicators":"ਪੇਂਟ ਐਪਲੀਕੇਟਰਜ਼", Contractors:"ਕੌਂਟਰੈਕਟਰਜ਼", "Job Activity":"ਜੌਬ ਐਕਟਿਵਿਟੀ", Settings:"ਸੈਟਿੰਗਸ", Logout:"ਲੌਗ ਆਉਟ", Notifications:"ਨੋਟੀਫਿਕੇਸ਼ਨਜ਼", "Mark all read":"ਮਾਰਕ ਆਲ ਰੀਡ", "Profile settings":"ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਸ", "My account":"ਮਾਈ ਅਕਾਊਂਟ", Calculator:"ਕੈਲਕੁਲੇਟਰ", "Job requirements":"ਜੌਬ ਰਿਕਵਾਇਰਮੈਂਟਸ", "Post requirement":"ਪੋਸਟ ਰਿਕਵਾਇਰਮੈਂਟ", Apply:"ਅਪਲਾਈ", Applied:"ਅਪਲਾਈਡ",
  },
  or: {
    Language:"ଲ୍ୟାଙ୍ଗୁଏଜ୍", Dashboard:"ଡ୍ୟାସବୋର୍ଡ", Sales:"ସେଲ୍ସ", Work:"ୱର୍କ", People:"ପିପଲ୍", Business:"ବିଜନେସ୍", "Painter network":"ପେଣ୍ଟର ନେଟୱର୍କ", Support:"ସପୋର୍ଟ", Administration:"ଆଡମିନିଷ୍ଟ୍ରେସନ୍", More:"ମୋର",
    "CRM Dashboard":"ସି ଆର ଏମ ଡ୍ୟାସବୋର୍ଡ", Opportunities:"ଅପର୍ଚୁନିଟିଜ୍", Subscription:"ସବସ୍କ୍ରିପ୍ସନ୍", Quotations:"କୋଟେସନ୍ସ", Quotation:"କୋଟେସନ୍", Invoices:"ଇନଭଏସେସ୍", "Revenue & Receipts":"ରେଭେନ୍ୟୁ & ରିସିପ୍ଟ୍ସ", Customers:"କଷ୍ଟମର୍ସ", Customer:"କଷ୍ଟମର୍", "Post Job":"ପୋଷ୍ଟ ଜବ୍", Tasks:"ଟାସ୍କ୍ସ", Messages:"ମେସେଜେସ୍", Requests:"ରିକ୍ୱେଷ୍ଟ୍ସ", "Service Requests":"ସର୍ଭିସ୍ ରିକ୍ୱେଷ୍ଟ୍ସ", "Support Desk":"ସପୋର୍ଟ ଡେସ୍କ", "Area Calculator":"ଏରିଆ କ୍ୟାଲକୁଲେଟର୍", Properties:"ପ୍ରପର୍ଟିଜ୍", Property:"ପ୍ରପର୍ଟି", "Master Data":"ମାଷ୍ଟର ଡାଟା", "Find Painter":"ଫାଇଣ୍ଡ ପେଣ୍ଟର", "Find Paint Applicators":"ଫାଇଣ୍ଡ ପେଣ୍ଟ ଆପ୍ଲିକେଟର୍ସ", "Register Applicator":"ରେଜିଷ୍ଟର ଆପ୍ଲିକେଟର୍", "Ratings & Reviews":"ରେଟିଙ୍ଗ୍ସ & ରିଭ୍ୟୁସ୍", "In-house Applicators":"ଇନ୍-ହାଉସ୍ ଆପ୍ଲିକେଟର୍ସ", "Work Schedule":"ୱର୍କ ସେଡ୍ୟୁଲ୍", Reschedule:"ରିସେଡ୍ୟୁଲ୍", "Completed Work":"କମ୍ପ୍ଲିଟେଡ୍ ୱର୍କ", "Applicator Availability":"ଆପ୍ଲିକେଟର୍ ଆଭେଲେବିଲିଟି", "Applicator Bookings":"ଆପ୍ଲିକେଟର୍ ବୁକିଙ୍ଗ୍ସ", "Work Photos":"ୱର୍କ ଫୋଟୋସ୍", Reports:"ରିପୋର୍ଟ୍ସ", "Activity Log":"ଆକ୍ଟିଭିଟି ଲଗ୍", "Available Jobs":"ଆଭେଲେବଲ୍ ଜବ୍ସ", "Post Job Seeking":"ପୋଷ୍ଟ ଜବ୍ ସିକିଙ୍ଗ୍", "My Employment":"ମାଇ ଏମ୍ପ୍ଲୟମେଣ୍ଟ", "My Earnings":"ମାଇ ଆର୍ନିଙ୍ଗ୍ସ", "My Assignments":"ମାଇ ଆସାଇନମେଣ୍ଟ୍ସ", "My Profile":"ମାଇ ପ୍ରୋଫାଇଲ୍", "My Availability":"ମାଇ ଆଭେଲେବିଲିଟି", "Booking Requests":"ବୁକିଙ୍ଗ୍ ରିକ୍ୱେଷ୍ଟ୍ସ", Verification:"ଭେରିଫିକେସନ୍", "My Quotations":"ମାଇ କୋଟେସନ୍ସ", "Payments & Invoices":"ପେମେଣ୍ଟ୍ସ & ଇନଭଏସେସ୍", "My Properties":"ମାଇ ପ୍ରପର୍ଟିଜ୍", "Share Area Calculation":"ସେୟାର ଏରିଆ କ୍ୟାଲକୁଲେସନ୍", Packages:"ପ୍ୟାକେଜେସ୍", Billing:"ବିଲିଙ୍ଗ୍", "Subscription Revenue":"ସବସ୍କ୍ରିପ୍ସନ୍ ରେଭେନ୍ୟୁ", "Paint Applicators":"ପେଣ୍ଟ ଆପ୍ଲିକେଟର୍ସ", Contractors:"କଣ୍ଟ୍ରାକ୍ଟର୍ସ", "Job Activity":"ଜବ୍ ଆକ୍ଟିଭିଟି", Settings:"ସେଟିଙ୍ଗ୍ସ", Logout:"ଲଗ୍ ଆଉଟ୍", Notifications:"ନୋଟିଫିକେସନ୍ସ", "Mark all read":"ମାର୍କ ଅଲ୍ ରିଡ୍", "Profile settings":"ପ୍ରୋଫାଇଲ୍ ସେଟିଙ୍ଗ୍ସ", "My account":"ମାଇ ଆକାଉଣ୍ଟ", Calculator:"କ୍ୟାଲକୁଲେଟର୍", "Job requirements":"ଜବ୍ ରିକ୍ୱାୟରମେଣ୍ଟ୍ସ", "Post requirement":"ପୋଷ୍ଟ ରିକ୍ୱାୟରମେଣ୍ଟ", Apply:"ଆପ୍ଲାଇ", Applied:"ଆପ୍ଲାଇଡ୍",
  },
  as: {
    Language:"লেংগুৱেজ", Dashboard:"ডেশ্ববৰ্ড", Sales:"ছেলছ", Work:"ৱৰ্ক", People:"পিপল", Business:"বিজনেছ", "Painter network":"পেইণ্টাৰ নেটৱৰ্ক", Support:"চাপোৰ্ট", Administration:"এডমিনিষ্ট্ৰেচন", More:"ম'ৰ",
    "CRM Dashboard":"চি আৰ এম ডেশ্ববৰ্ড", Opportunities:"অপৰচুনিটিজ", Subscription:"চাবস্ক্ৰিপচন", Quotations:"কোটেচনছ", Quotation:"কোটেচন", Invoices:"ইনভইচেছ", "Revenue & Receipts":"ৰেভিনিউ & ৰিচিপ্টছ", Customers:"কাষ্টমাৰ্ছ", Customer:"কাষ্টমাৰ", "Post Job":"পোষ্ট জব", Tasks:"টাস্কছ", Messages:"মেছেজেছ", Requests:"ৰিকুৱেষ্টছ", "Service Requests":"চাৰ্ভিচ ৰিকুৱেষ্টছ", "Support Desk":"চাপোৰ্ট ডেস্ক", "Area Calculator":"এৰিয়া কেলকুলেটৰ", Properties:"প্ৰপাৰ্টিজ", Property:"প্ৰপাৰ্টি", "Master Data":"মাষ্টাৰ ডাটা", "Find Painter":"ফাইণ্ড পেইণ্টাৰ", "Find Paint Applicators":"ফাইণ্ড পেইণ্ট এপ্লিকেটৰ্ছ", "Register Applicator":"ৰেজিষ্টাৰ এপ্লিকেটৰ", "Ratings & Reviews":"ৰেটিংছ & ৰিভিউজ", "In-house Applicators":"ইন-হাউচ এপ্লিকেটৰ্ছ", "Work Schedule":"ৱৰ্ক শ্বেডিউল", Reschedule:"ৰিশ্বেডিউল", "Completed Work":"কমপ্লিটেড ৱৰ্ক", "Applicator Availability":"এপ্লিকেটৰ এভেইলেবিলিটি", "Applicator Bookings":"এপ্লিকেটৰ বুকিংছ", "Work Photos":"ৱৰ্ক ফটোছ", Reports:"ৰিপোৰ্টছ", "Activity Log":"এক্টিভিটি লগ", "Available Jobs":"এভেইলেবল জবছ", "Post Job Seeking":"পোষ্ট জব চিকিং", "My Employment":"মাই এমপ্লয়মেণ্ট", "My Earnings":"মাই আৰ্নিংছ", "My Assignments":"মাই এছাইনমেণ্টছ", "My Profile":"মাই প্ৰফাইল", "My Availability":"মাই এভেইলেবিলিটি", "Booking Requests":"বুকিং ৰিকুৱেষ্টছ", Verification:"ভেৰিফিকেচন", "My Quotations":"মাই কোটেচনছ", "Payments & Invoices":"পেমেণ্টছ & ইনভইচেছ", "My Properties":"মাই প্ৰপাৰ্টিজ", "Share Area Calculation":"শ্বেয়াৰ এৰিয়া কেলকুলেচন", Packages:"পেকেজেছ", Billing:"বিলিং", "Subscription Revenue":"চাবস্ক্ৰিপচন ৰেভিনিউ", "Paint Applicators":"পেইণ্ট এপ্লিকেটৰ্ছ", Contractors:"কণ্ট্ৰেক্টৰ্ছ", "Job Activity":"জব এক্টিভিটি", Settings:"ছেটিংছ", Logout:"লগ আউট", Notifications:"নোটিফিকেচনছ", "Mark all read":"মাৰ্ক অল ৰিড", "Profile settings":"প্ৰফাইল ছেটিংছ", "My account":"মাই একাউণ্ট", Calculator:"কেলকুলেটৰ", "Job requirements":"জব ৰিকুৱায়াৰমেণ্টছ", "Post requirement":"পোষ্ট ৰিকুৱায়াৰমেণ্ট", Apply:"এপ্লাই", Applied:"এপ্লাইড",
  },
};

const LanguageContext = createContext(null);
export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem("bp-language") || "en");
  const setLanguage = (value) => { setLanguageState(value); localStorage.setItem("bp-language", value); };
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({ language, setLanguage, t: (text) => phonetic[language]?.[text] || core[language]?.[text] || text }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage() { return useContext(LanguageContext); }
